project:
  type: book
  output-dir: publish

book:
  title: "The Regression Cookbook"
  subtitle: "Now with Machine Learning and Stats Flavours!"
  author: "G. Alexi Rodríguez-Arelis"
  date: today
  abstract: "This book aims to set a common ground between Machine Learning and Statistics regarding regression techniques, using `Python` and `R`, under two perspectives: **inference** and **prediction**."
  keyword: regression analysis, statistical inference, statistical analysis, statistical learning, machine learning
  url: https://alexrod61.github.io/regression-cookbook/
  sidebar: 
    background: "#FCF3CF"
    search: true
  repo-url: https://github.com/alexrod61/regression-cookbook
  repo-subdir: book
  repo-branch: main
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]
 
  chapters:
    - index.qmd
    - book/intro.qmd
    - book/summary.qmd
    - book/references.qmd

bibliography: book/references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

