project:
  type: book
  output-dir: docs

book:
  title: "The Regression Cookbook (in development)"
  author:
    - name: 
      - G. Alexi Rodríguez-Arelis
      email: alexrod@stat.ubc.ca
      attributes:
        corresponding: true
    - name: 
      - Andy Tai
      email: andy.tai@stat.ubc.ca
    - name: Ben Chen
  date: today
  abstract: "This book aims to set a common ground between machine learning and statistics regarding linear regression techniques, using `Python` and `R`, under two perspectives: **inference** and **prediction**."
  keyword: regression analysis, statistical inference, statistical analysis, statistical learning, machine learning
  url: https://alexrod61.github.io/regression-cookbook/
  sidebar: 
    background: "#FCF3CF"
    logo: img/cookbook.png
    search: true
  site-url: https://alexrod61.github.io/regression-cookbook/
  repo-url: https://github.com/alexrod61/regression-cookbook
  repo-branch: main
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]
  comments:
    giscus:
      repo: alexrod61/regression-cookbook
  page-footer: 
    left: |
      Copyright 2025; G. Alexi Rodríguez-Arelis, Andy Tai, and Ben Chen
  page-navigation: true
  navbar:
    search: true
    foreground: "#f35c24"
    background: "#f8c471"

  chapters:
    - index.qmd
    - book/privacy-policy.qmd
    - book/audience-scope.qmd
    - book/01-intro.qmd
    - book/02-stats-review.qmd
    - part: book/continuous-zone.qmd
      chapters: 
        - book/03-ols.qmd
        - book/04-gamma.qmd
        - book/05-beta.qmd
        - book/06-parametric-survival.qmd
        - book/07-semiparametric-survival.qmd
    - part: book/discrete-zone.qmd
      chapters: 
        - book/08-binary-logistic.qmd
        - book/09-binomial-logistic.qmd
        - book/10-classical-poisson.qmd
        - book/11-negative-binomial.qmd
        - book/12-zero-inflated-poisson.qmd
        - book/13-generalized-poisson.qmd
        - book/14-multinomial-logistic.qmd
        - book/15-ordinal-logistic.qmd
    - book/references.qmd
  appendices:
    - book/A-dictionary.qmd
    - book/B-greek-alphabet.qmd
    - book/C-distributional-mind-map.qmd
    - book/D-regression-mind-map.qmd

bibliography: book/references.bib

format:
  html:
    theme: cosmo
    css: custom.css
    fontsize: 1.2em
    linestretch: 1.65
    toc: true
    toc-location: right
    toc-depth: 4
    toc-title: The recipe
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    code-link: true
    html-math-method: mathjax
    linkcolor: rgb(214, 122, 127)
    number-sections: true
    number-depth: 3
    grid:
      sidebar-width: 300px
      body-width: 960px
      margin-width: 275px
      gutter-width: 1.2em

  pdf:
    documentclass: scrreprt
    include-in-header: preamble.tex
