project:
  type: book
  output-dir: docs

book:
  title: "The Regression Cookbook"
  subtitle: "**Now with Machine Learning and Stats Flavours!**"
  author:
  - name: G. Alexi Rodríguez-Arelis
    email: alexrod@stat.ubc.ca
    affiliation:
      - Department of Statistics <br>
        Faculty of Science <br> 
        *The University of British Columbia*
    degrees: PhD
  date: today
  abstract: "This book aims to set a common ground between Machine Learning and Statistics regarding regression techniques, using `Python` and `R`, under two perspectives: **inference** and **prediction**."
  keyword: regression analysis, statistical inference, statistical analysis, statistical learning, machine learning
  url: https://alexrod61.github.io/regression-cookbook/
  sidebar: 
    background: "#FCF3CF"
    logo: book/img/cookbook.png
    search: true
  repo-url: https://github.com/alexrod61/regression-cookbook
  repo-branch: main
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]
  comments:
    giscus:
      repo: alexrod61/regression-cookbook
  page-footer: 
    left: |
      Copyright 2024, G. Alexi Rodríguez-Arelis
  page-navigation: true
 
  chapters:
    - index.qmd
    - book/audience-scope.qmd
    - book/book-structure.qmd
    - book/intro.qmd
    - book/summary.qmd
    - book/references.qmd

bibliography: book/references.bib

format:
  html:
    theme: cosmo
    css: custom.css
    fontsize: 1.2em
    linestretch: 1.65
    toc: true
    toc-depth: 3
    toc-title: On this page
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    code-link: true
    html-math-method: mathjax
    linkcolor: rgb(214, 122, 127)
    number-sections: true
    number-depth: 3
    grid:
      sidebar-width: 300px
      body-width: 960px
      margin-width: 275px
      gutter-width: 1.2em
    
  pdf:
    documentclass: scrreprt
