# Preface {.unnumbered}

> **Let the regression cooking begin!**

Throughout my journey as a postdoctoral fellow in the [Master of Data Science (MDS)](https://masterdatascience.ubc.ca/) at the University of British Columbia, I became aware of the fascinating overlap between **machine learning** and **statistics**. Many data science students usually come across common machine learning/statistics concepts or ideas that might only differ in names. For instance, simple terms such as weights in **supervised learning** (and their equivalent statistical counterpart as regression coefficients) might be misleading for students starting their data science formation. On the other hand, from an instructor's perspective in a data science program that subsets its courses in machine learning in `Python` and statistics in `R`, regression courses in `R` also demand the inclusion of `Python`-related packages as alternative tools. In my data science teaching experience, this is especially critical for students whose career plan leans towards industry where `Python` is more heavily used.

As a data science educator, I view this field as a **substantial synergy** between machine learning and statistics. Nevertheless, many gaps between both disciplines still need to be addressed. Thus, closing these critical gaps is imperative in a domain with accelerated growth, such as data science. In this regard, the [MDS Stat-ML dictionary](https://ubc-mds.github.io/resources_pages/terminology/) inspired me to write this textbook. It basically consists of **common ground** between **foundational supervised learning models** from machine learning and **regression models** commonly used in statistics. I strive to explore **linear modelling approaches** as a primary step while highlighting different terminology found in both fields. Furthermore, this discussion is more comprehensive than a simple conceptual exploration. Hence, the second step is **hands-on practice** via the corresponding `Python` packages for machine learning and `R` for statistics.

::: {.callout-warning icon=false}

## Fun fact!

While thinking about possible names for this work, I was planning to name it "*Machine Learning and Statistics: A Common Ground.*" Nevertheless, it was quite plain and boring! That said, this whole textbook idea sounded analogous to a **cookbook**[^1], given its heavily applied focus.\

**Hence, the cookbook name idea**!
:::

[^1]: Special thanks to *Jonathan Graves*, who mentioned this term in our very first chat back when I was conceptualizing this textbook.


