<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.53">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>3&nbsp; Zestylicious Ordinary Least-squares Regression – The Regression Cookbook</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../book/04-gamma.html" rel="next">
<link href="../book/continuous-zone.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><style>html{ scroll-behavior: smooth; }</style>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script><script src="../site_libs/quarto-diagram/mermaid-init.js"></script><link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="../custom.css">
</head>
<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">The Regression Cookbook</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
    <a href="https://github.com/alexrod61/regression-cookbook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://www.facebook.com/sharer/sharer.php?u=%7Curl%7C">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://www.linkedin.com/sharing/share-offsite/?url=%7Curl%7C">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../book/continuous-zone.html">Continuous Cuisine</a></li><li class="breadcrumb-item"><a href="../book/03-ols.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Zestylicious Ordinary Least-squares Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../img/cookbook.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none"></a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/privacy-policy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Website Privacy Policy</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/audience-scope.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Audience and Scope</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting Ready for Regression Cooking!</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/02-stats-review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Basic Cuisine: A Review on Probability and Frequentist Statistical Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../book/continuous-zone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Continuous Cuisine</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/03-ols.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Zestylicious Ordinary Least-squares Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/04-gamma.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Smoketastic Gamma Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/05-beta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Soup-erb Beta Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/06-parametric-survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Crunchified Parametric Survival Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/07-semiparametric-survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Butteryfied Semiparametric Survival Regression</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../book/discrete-zone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Discrete Cuisine</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/08-binary-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Sauce-sational Binary Logistic Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/09-binomial-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Cheesified Binomial Logistic Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/10-classical-poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Bubblarious Classical Poisson Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/11-negative-binomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Umami-zing Negative Binomial Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/12-zero-inflated-poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Spicetacular Zero-Inflated Poisson Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/13-generalized-poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Herbalicious Generalized Poisson Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/14-multinomial-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Picklified Multinomial Logistic Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/15-ordinal-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Tang-tastic Ordinal Logistic Regression</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/A-dictionary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">The Fusionified ML-Stats Dictionary</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/B-greek-alphabet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">The Snazzalicious Greek Alphabet</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/C-distributional-mind-map.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">The Chocolified Distributional Mind Map</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/D-regression-mind-map.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">The Sugartastic Regression Mind Map</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">The recipe</h2>
   
  <ul>
<li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">3.1</span> Introduction</a></li>
  <li><a href="#what-is-ordinary-least-squares-ols" id="toc-what-is-ordinary-least-squares-ols" class="nav-link" data-scroll-target="#what-is-ordinary-least-squares-ols"><span class="header-section-number">3.2</span> What is Ordinary Least Squares (OLS)?</a></li>
  <li>
<a href="#the-best-line" id="toc-the-best-line" class="nav-link" data-scroll-target="#the-best-line"><span class="header-section-number">3.3</span> The “Best Line”</a>
  <ul>
<li><a href="#understanding-residuals" id="toc-understanding-residuals" class="nav-link" data-scroll-target="#understanding-residuals"><span class="header-section-number">3.3.1</span> Understanding Residuals</a></li>
  <li><a href="#quantifying-the-fit-with-sse" id="toc-quantifying-the-fit-with-sse" class="nav-link" data-scroll-target="#quantifying-the-fit-with-sse"><span class="header-section-number">3.3.2</span> Quantifying the Fit with SSE</a></li>
  <li><a href="#why-squared-errors" id="toc-why-squared-errors" class="nav-link" data-scroll-target="#why-squared-errors"><span class="header-section-number">3.3.3</span> Why Squared Errors?</a></li>
  <li><a href="#the-mathematical-formulation-of-the-ols-model" id="toc-the-mathematical-formulation-of-the-ols-model" class="nav-link" data-scroll-target="#the-mathematical-formulation-of-the-ols-model"><span class="header-section-number">3.3.4</span> The Mathematical Formulation of the OLS Model</a></li>
  </ul>
</li>
  <li>
<a href="#case-study-understanding-financial-behaviors" id="toc-case-study-understanding-financial-behaviors" class="nav-link" data-scroll-target="#case-study-understanding-financial-behaviors"><span class="header-section-number">3.4</span> Case Study: Understanding Financial Behaviors</a>
  <ul>
<li><a href="#the-dataset" id="toc-the-dataset" class="nav-link" data-scroll-target="#the-dataset"><span class="header-section-number">3.4.1</span> The Dataset</a></li>
  <li><a href="#the-problem-were-trying-to-solve" id="toc-the-problem-were-trying-to-solve" class="nav-link" data-scroll-target="#the-problem-were-trying-to-solve"><span class="header-section-number">3.4.2</span> The Problem We’re Trying to Solve</a></li>
  <li>
<a href="#study-design" id="toc-study-design" class="nav-link" data-scroll-target="#study-design"><span class="header-section-number">3.4.3</span> Study Design</a>
  <ul class="collapse">
<li><a href="#inferential-vs.-predictive-analysis" id="toc-inferential-vs.-predictive-analysis" class="nav-link" data-scroll-target="#inferential-vs.-predictive-analysis">Inferential vs.&nbsp;Predictive Analysis</a></li>
  </ul>
</li>
  <li><a href="#applying-study-design-to-our-case-study" id="toc-applying-study-design-to-our-case-study" class="nav-link" data-scroll-target="#applying-study-design-to-our-case-study"><span class="header-section-number">3.4.4</span> Applying Study Design to Our Case Study</a></li>
  </ul>
</li>
  <li>
<a href="#data-collection-and-wrangling" id="toc-data-collection-and-wrangling" class="nav-link" data-scroll-target="#data-collection-and-wrangling"><span class="header-section-number">3.5</span> Data Collection and Wrangling</a>
  <ul>
<li><a href="#data-collection" id="toc-data-collection" class="nav-link" data-scroll-target="#data-collection"><span class="header-section-number">3.5.1</span> Data Collection</a></li>
  <li>
<a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling"><span class="header-section-number">3.5.2</span> Data Wrangling</a>
  <ul class="collapse">
<li><a href="#handling-missing-data" id="toc-handling-missing-data" class="nav-link" data-scroll-target="#handling-missing-data">Handling Missing Data</a></li>
  <li><a href="#encoding-categorical-variables" id="toc-encoding-categorical-variables" class="nav-link" data-scroll-target="#encoding-categorical-variables">Encoding Categorical Variables</a></li>
  <li><a href="#detecting-and-handling-outliers" id="toc-detecting-and-handling-outliers" class="nav-link" data-scroll-target="#detecting-and-handling-outliers">Detecting and Handling Outliers</a></li>
  <li><a href="#splitting-the-data-for-model-training" id="toc-splitting-the-data-for-model-training" class="nav-link" data-scroll-target="#splitting-the-data-for-model-training">Splitting the Data for Model Training</a></li>
  </ul>
</li>
  </ul>
</li>
  <li>
<a href="#exploratory-data-analysis-eda" id="toc-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda"><span class="header-section-number">3.6</span> Exploratory Data Analysis (EDA)</a>
  <ul>
<li><a href="#classifying-variables" id="toc-classifying-variables" class="nav-link" data-scroll-target="#classifying-variables"><span class="header-section-number">3.6.1</span> Classifying Variables</a></li>
  <li>
<a href="#visualizing-variable-distributions" id="toc-visualizing-variable-distributions" class="nav-link" data-scroll-target="#visualizing-variable-distributions"><span class="header-section-number">3.6.2</span> Visualizing Variable Distributions</a>
  <ul class="collapse">
<li><a href="#continuous-variables" id="toc-continuous-variables" class="nav-link" data-scroll-target="#continuous-variables">Continuous Variables</a></li>
  <li><a href="#categorical-and-ordinal-variables" id="toc-categorical-and-ordinal-variables" class="nav-link" data-scroll-target="#categorical-and-ordinal-variables">Categorical and Ordinal Variables</a></li>
  <li><a href="#exploring-relationships-between-variables" id="toc-exploring-relationships-between-variables" class="nav-link" data-scroll-target="#exploring-relationships-between-variables">Exploring Relationships Between Variables</a></li>
  <li><a href="#scatterplots" id="toc-scatterplots" class="nav-link" data-scroll-target="#scatterplots">Scatterplots</a></li>
  <li><a href="#summary-statistics" id="toc-summary-statistics" class="nav-link" data-scroll-target="#summary-statistics">Summary Statistics</a></li>
  </ul>
</li>
  <li><a href="#key-takeaways-from-eda" id="toc-key-takeaways-from-eda" class="nav-link" data-scroll-target="#key-takeaways-from-eda"><span class="header-section-number">3.6.3</span> Key Takeaways from EDA</a></li>
  </ul>
</li>
  <li>
<a href="#data-modelling" id="toc-data-modelling" class="nav-link" data-scroll-target="#data-modelling"><span class="header-section-number">3.7</span> Data Modelling</a>
  <ul>
<li><a href="#choosing-a-suitable-regression-model" id="toc-choosing-a-suitable-regression-model" class="nav-link" data-scroll-target="#choosing-a-suitable-regression-model"><span class="header-section-number">3.7.1</span> Choosing a Suitable Regression Model</a></li>
  <li>
<a href="#defining-modeling-parameters" id="toc-defining-modeling-parameters" class="nav-link" data-scroll-target="#defining-modeling-parameters"><span class="header-section-number">3.7.2</span> Defining Modeling Parameters</a>
  <ul class="collapse">
<li><a href="#response-variable-y" id="toc-response-variable-y" class="nav-link" data-scroll-target="#response-variable-y">Response Variable (Y):</a></li>
  <li><a href="#predictor-variables-x" id="toc-predictor-variables-x" class="nav-link" data-scroll-target="#predictor-variables-x">Predictor Variables (X):</a></li>
  </ul>
</li>
  <li><a href="#setting-up-the-modeling-equation" id="toc-setting-up-the-modeling-equation" class="nav-link" data-scroll-target="#setting-up-the-modeling-equation"><span class="header-section-number">3.7.3</span> Setting Up the Modeling Equation</a></li>
  </ul>
</li>
  <li>
<a href="#estimation" id="toc-estimation" class="nav-link" data-scroll-target="#estimation"><span class="header-section-number">3.8</span> Estimation</a>
  <ul>
<li><a href="#fitting-the-model" id="toc-fitting-the-model" class="nav-link" data-scroll-target="#fitting-the-model"><span class="header-section-number">3.8.1</span> Fitting the Model</a></li>
  <li><a href="#interpreting-the-coefficients" id="toc-interpreting-the-coefficients" class="nav-link" data-scroll-target="#interpreting-the-coefficients"><span class="header-section-number">3.8.2</span> Interpreting the Coefficients</a></li>
  </ul>
</li>
  <li>
<a href="#goodness-of-fit" id="toc-goodness-of-fit" class="nav-link" data-scroll-target="#goodness-of-fit"><span class="header-section-number">3.9</span> Goodness of Fit</a>
  <ul>
<li>
<a href="#checking-model-assumptions" id="toc-checking-model-assumptions" class="nav-link" data-scroll-target="#checking-model-assumptions"><span class="header-section-number">3.9.1</span> Checking Model Assumptions</a>
  <ul class="collapse">
<li><a href="#linearity" id="toc-linearity" class="nav-link" data-scroll-target="#linearity">Linearity</a></li>
  <li><a href="#independence-of-errors" id="toc-independence-of-errors" class="nav-link" data-scroll-target="#independence-of-errors">Independence of Errors</a></li>
  <li><a href="#homoscedasticity-constant-variance-of-errors" id="toc-homoscedasticity-constant-variance-of-errors" class="nav-link" data-scroll-target="#homoscedasticity-constant-variance-of-errors">Homoscedasticity (Constant Variance of Errors)</a></li>
  <li><a href="#normality-of-residuals" id="toc-normality-of-residuals" class="nav-link" data-scroll-target="#normality-of-residuals">Normality of Residuals</a></li>
  </ul>
</li>
  <li>
<a href="#evaluating-model-fit" id="toc-evaluating-model-fit" class="nav-link" data-scroll-target="#evaluating-model-fit"><span class="header-section-number">3.9.2</span> Evaluating Model Fit</a>
  <ul class="collapse">
<li><a href="#r-squared" id="toc-r-squared" class="nav-link" data-scroll-target="#r-squared">R-Squared</a></li>
  <li><a href="#identifying-outliers-and-influential-points" id="toc-identifying-outliers-and-influential-points" class="nav-link" data-scroll-target="#identifying-outliers-and-influential-points">Identifying Outliers and Influential Points</a></li>
  </ul>
</li>
  </ul>
</li>
  <li>
<a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">3.10</span> Results</a>
  <ul>
<li>
<a href="#predictive-analysis" id="toc-predictive-analysis" class="nav-link" data-scroll-target="#predictive-analysis"><span class="header-section-number">3.10.1</span> Predictive Analysis</a>
  <ul class="collapse">
<li><a href="#performance-metrics" id="toc-performance-metrics" class="nav-link" data-scroll-target="#performance-metrics">Performance Metrics</a></li>
  </ul>
</li>
  <li>
<a href="#inferential-analysis" id="toc-inferential-analysis" class="nav-link" data-scroll-target="#inferential-analysis"><span class="header-section-number">3.10.2</span> Inferential Analysis</a>
  <ul class="collapse">
<li><a href="#insights-from-regression-coefficients" id="toc-insights-from-regression-coefficients" class="nav-link" data-scroll-target="#insights-from-regression-coefficients">Insights from Regression Coefficients</a></li>
  </ul>
</li>
  </ul>
</li>
  <li><a href="#storytelling" id="toc-storytelling" class="nav-link" data-scroll-target="#storytelling"><span class="header-section-number">3.11</span> Storytelling</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/alexrod61/regression-cookbook/edit/main/book/03-ols.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/alexrod61/regression-cookbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li><li><a href="https://github.com/alexrod61/regression-cookbook/blob/main/book/03-ols.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../book/continuous-zone.html">Continuous Cuisine</a></li><li class="breadcrumb-item"><a href="../book/03-ols.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Zestylicious Ordinary Least-squares Regression</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-ols" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Zestylicious Ordinary Least-squares Regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><!-- Google tag (gtag.js) --><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-7PRVEBE1EF"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-7PRVEBE1EF');
</script><div class="Warning">
<div class="Warning-header">
<p>Fun fact!</p>
</div>
<div class="Warning-container">
<p><strong>Zestylicious!</strong> That mouth-puckering, lemon-squirted, totally tangy kick!</p>
</div>
</div>
<div id="fig-ols-regression" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-ols-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"></figure><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Regression 
  Analysis)
    Continuous &lt;br/&gt;Outcome Y
      {{Unbounded &lt;br/&gt;Outcome Y}}
        )Chapter 3: &lt;br/&gt;Ordinary &lt;br/&gt;Least Squares &lt;br/&gt;Regression(
          (Normal &lt;br/&gt;Outcome Y)
    Discrete &lt;br/&gt;Outcome Y
</pre>
</div>
<p></p>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-ols-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.1
</figcaption></figure>
</div>
<div class="LO">
<div class="LO-header">
<p>Learning Objectives</p>
</div>
<div class="LO-container">
<p>By the end of this chapter, you will be able to:</p>
<ul>
<li>Explain how Ordinary Least-squares (OLS) estimates relationships by <strong>minimizing the sum of squared residuals</strong>.</li>
<li>Determine when OLS is an <strong>appropriate modeling choice</strong>.</li>
<li>Fit an OLS model using <code>Python</code> or <code>R</code>.</li>
<li>Interpret regression coefficients to assess <strong>the impact of predictors on the response variable</strong>.</li>
<li>Check <strong>key OLS assumptions</strong>, including: <strong>linearity</strong>, <strong>independence</strong>, <strong>homoscedasticity</strong>, and <strong>normality of residuals</strong>.</li>
<li>Evaluate <strong>model performance</strong> using <strong><span class="math inline">\(R\)</span>-squared</strong> and <strong>error metrics</strong> such as <strong>mean absolute error</strong> (MAE), <strong>mean squared error</strong> (MSE), and <strong>root mean squared error</strong> (RMSE).</li>
</ul>
</div>
</div>
<section id="introduction" class="level2" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="introduction">
<span class="header-section-number">3.1</span> Introduction</h2>
<p>When looking at data, we often want to know how different factors affect each other. For instance, if you have data on student finances, you might ask:</p>
<ul>
<li>How does having a job affect a student’s leftover money at the end of the month?</li>
<li>What impact does receiving a monthly allowance have on their net savings?</li>
</ul>
<p>Once you have this financial data, the next step is to analyze it to find answers. One straightforward method for doing this is through regression analysis, and the simplest form is called <strong>Ordinary Least Squares (OLS)</strong>.</p>
</section><section id="what-is-ordinary-least-squares-ols" class="level2" data-number="3.2"><h2 data-number="3.2" class="anchored" data-anchor-id="what-is-ordinary-least-squares-ols">
<span class="header-section-number">3.2</span> What is Ordinary Least Squares (OLS)?</h2>
<p><strong>Ordinary Least Squares (OLS)</strong> is a fundamental method in regression analysis for estimating the relationship between a dependent variable and one or more independent variables. In simple terms, OLS is like drawing the best straight line through a scatterplot of data points. Imagine you plotted students’ net savings on a graph, and each point represents a student’s financial outcome. OLS finds the line that best follows the trend of these points by minimizing the overall distance (error) between what the line predicts and what the actual data shows.</p>
<p>OLS is widely used because it is:</p>
<ul>
<li>
<strong>Simple</strong>: Easy to understand and compute.</li>
<li>
<strong>Clear</strong>: Provides straightforward numbers (coefficients) that tell you how much each factor influences the outcome.</li>
<li>
<strong>Versatile</strong>: Applicable in many fields, from economics to social sciences, to help make informed decisions.</li>
</ul>
<p>In this chapter, we will break down how OLS works in plain language, explore its underlying assumptions, and discuss its practical applications and limitations. This will give you a solid foundation in regression analysis, paving the way for more advanced techniques later on.</p>
</section><section id="the-best-line" class="level2" data-number="3.3"><h2 data-number="3.3" class="anchored" data-anchor-id="the-best-line">
<span class="header-section-number">3.3</span> The “Best Line”</h2>
<p>When using Ordinary Least Squares (OLS) to fit a regression line, our goal is to find the line that best represents the relationship between our dependent variable <span class="math inline">\(Y\)</span> and independent variable <span class="math inline">\(X\)</span>. But what does “best” mean?</p>
<p>Imagine you have a scatter plot of data points. Now, consider drawing two different lines through this plot. Each one of these lines represent a set of predictions. They also represent a way to represent the relationship between the dependent variable <span class="math inline">\(Y\)</span> and independent variable <span class="math inline">\(X\)</span></p>
<ul>
<li>
<strong>Line A (Blue)</strong>: A line that follows the general trend of the data very well.</li>
<li>
<strong>Line B (Red)</strong>: A line that doesn’t capture the trend as accurately.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03-ols_files/figure-html/two_lines-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"HelloWorld"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>HelloWorld</code></pre>
</div>
</div>
<section id="understanding-residuals" class="level3" data-number="3.3.1"><h3 data-number="3.3.1" class="anchored" data-anchor-id="understanding-residuals">
<span class="header-section-number">3.3.1</span> Understanding Residuals</h3>
<p>For each data point, the residual is the vertical distance between the actual <span class="math inline">\(Y\)</span> value and the predicted <span class="math inline">\(Y\)</span> value (denoted <span class="math inline">\(\hat{Y}\)</span>) on the line. In simple terms, it tells us how far off our prediction is for each point given the same <span class="math inline">\(X\)</span> value. If a line fits well, these residuals will be small, meaning our predictions of the <span class="math inline">\(Y\)</span> variable are close to the actual value.</p>
<p>OLS quantifies how well a line fits the data by calculating the Sum of Squared Errors (SSE). The SSE is obtained by:</p>
<ol type="1">
<li>Computing the residual for each data point.</li>
<li>Squaring each residual (this ensures that errors do not cancel each other out).</li>
<li>Summing all these squared values.</li>
</ol>
<p><span class="math display">\[
SSE=\sum_{i=1}^{n} (Y_i - \hat{Y}_i)^2
\]</span></p>
<p>A lower SSE indicates a line that is closer to the actual data points. OLS chooses the best line by finding the one with the smallest SSE.</p>
</section><section id="quantifying-the-fit-with-sse" class="level3" data-number="3.3.2"><h3 data-number="3.3.2" class="anchored" data-anchor-id="quantifying-the-fit-with-sse">
<span class="header-section-number">3.3.2</span> Quantifying the Fit with SSE</h3>
<p>We can compare the two lines by computing their SSE. The code below calculates and prints the SSE for each line:</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calculate the Sum of Squared Errors for the correct model (Blue)</span></span>
<span><span class="va">sse_correct</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">Price</span> <span class="op">-</span> <span class="va">df</span><span class="op">$</span><span class="va">Predicted_Correct</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Calculate the Sum of Squared Errors for the manually adjusted model (Red)</span></span>
<span><span class="va">sse_wrong</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">Price</span> <span class="op">-</span> <span class="va">df</span><span class="op">$</span><span class="va">Predicted_Wrong</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Print the SSEs for each line</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"SSE for Best-Fit Line (Blue line):"</span>, <span class="va">sse_correct</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>SSE for Best-Fit Line (Blue line): 83.23529 </code></pre>
</div>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"SSE for Worse-Fit Line (Red line):"</span>, <span class="va">sse_wrong</span>, <span class="st">"\n"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>SSE for Worse-Fit Line (Red line): 3972 </code></pre>
</div>
</div>
<p>When you run this code, you’ll observe that the blue line (Line A) has a much lower SSE compared to the red line (Line B). This tells us that the blue line is a better fit for the data because its predictions are, on average, closer to the actual values.</p>
<p>In summary, OLS selects the “best line” by minimizing the sum of squared errors, ensuring that the total error between predicted and actual values is as small as possible.</p>
</section><section id="why-squared-errors" class="level3" data-number="3.3.3"><h3 data-number="3.3.3" class="anchored" data-anchor-id="why-squared-errors">
<span class="header-section-number">3.3.3</span> Why Squared Errors?</h3>
<p>When measuring how far off our predictions are, errors can be positive (if our prediction is too low) or negative (if it’s too high). If we simply added these errors together, they could cancel each other out, hiding the true size of the mistakes. By squaring each error, we convert all numbers to positive values so that every mistake counts.</p>
<p>In addition, squaring makes big errors count a lot more than small ones. This means that a large mistake will have a much bigger impact on the overall error, encouraging the model to reduce those large errors and improve its overall accuracy.</p>
</section><section id="the-mathematical-formulation-of-the-ols-model" class="level3" data-number="3.3.4"><h3 data-number="3.3.4" class="anchored" data-anchor-id="the-mathematical-formulation-of-the-ols-model">
<span class="header-section-number">3.3.4</span> The Mathematical Formulation of the OLS Model</h3>
<p>Now that we understand how OLS finds the best-fitting line by minimizing the differences between the actual and predicted values, let’s look at the math behind it.</p>
<p>In a simple linear regression with one predictor, we express the relationship between the outcome <span class="math inline">\(Y\)</span> and the predictor <span class="math inline">\(X\)</span> using the following equation. Note that OLS fits a straight line to the data, which is why the equation takes the familiar form of a straight line:</p>
<p><span class="math display">\[
Y=\beta_0+\beta_1X+\epsilon
\]</span></p>
<p>Here’s what each part of the equation means:</p>
<ul>
<li>
<span class="math inline">\(Y\)</span> is the dependent variable or the outcome we want to predict.</li>
<li>
<span class="math inline">\(X\)</span> is the independent variable or the predictor that we believe influences <span class="math inline">\(Y\)</span>.</li>
<li>
<span class="math inline">\(\beta_0\)</span> is the <strong>intercept</strong>. It represents the predicted value of <span class="math inline">\(Y\)</span> when <span class="math inline">\(X=0\)</span>.</li>
<li>
<span class="math inline">\(\beta_1\)</span> is the <strong>slope</strong>. It tells us how much <span class="math inline">\(Y\)</span> is expected to change for each one-unit increase in <span class="math inline">\(X\)</span>.</li>
<li>
<span class="math inline">\(\epsilon\)</span> is the <strong>error term</strong>. It captures the random variation in <span class="math inline">\(Y\)</span> that cannot be explained by <span class="math inline">\(X\)</span>.</li>
</ul>
<p>This equation provides a clear mathematical framework for understanding how changes in <span class="math inline">\(X\)</span> are expected to affect <span class="math inline">\(Y\)</span>, while also accounting for random variation. In the upcoming section, we will explore our toy dataset to showcase this equation and OLS in action.</p>
</section></section><section id="case-study-understanding-financial-behaviors" class="level2" data-number="3.4"><h2 data-number="3.4" class="anchored" data-anchor-id="case-study-understanding-financial-behaviors">
<span class="header-section-number">3.4</span> Case Study: Understanding Financial Behaviors</h2>
<p>To demonstrate Ordinary Least Squares (OLS) in action, we will walk through a case study using a toy dataset. This case study will help us understand the financial behaviors of students and identify the factors that influence their <code>Net_Money</code>, the amount of money left over at the end of each month. We will approach this case study using the <a href="../book/01-intro.html">data science workflow</a> described in a previous chapter, ensuring a structured approach to problem-solving and model building.</p>
<section id="the-dataset" class="level3" data-number="3.4.1"><h3 data-number="3.4.1" class="anchored" data-anchor-id="the-dataset">
<span class="header-section-number">3.4.1</span> The Dataset</h3>
<p>Our dataset captures various aspects of students’ financial lives. Each row represents a student, and the columns describe different characteristics. Below is a breakdown of the variables:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 72%">
</colgroup>
<thead><tr class="header">
<th><strong>Variable Name</strong></th>
<th><strong>Description</strong></th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Has_Job</strong></td>
<td>Whether the student has a job (0 = No, 1 = Yes).</td>
</tr>
<tr class="even">
<td><strong>Year_of_Study</strong></td>
<td>The student’s current year of study (e.g., 1st year, 2nd year, etc.).</td>
</tr>
<tr class="odd">
<td><strong>Financially_Dependent</strong></td>
<td>Whether the student is financially dependent on someone else (0 = No, 1 = Yes).</td>
</tr>
<tr class="even">
<td><strong>Monthly_Allowance</strong></td>
<td>The amount of financial support the student receives each month.</td>
</tr>
<tr class="odd">
<td><strong>Cooks_at_Home</strong></td>
<td>Whether the student prepares their own meals (0 = No, 1 = Yes).</td>
</tr>
<tr class="even">
<td><strong>Living_Situation</strong></td>
<td>The student’s living arrangement (e.g., living with family, in a shared apartment, etc.).</td>
</tr>
<tr class="odd">
<td><strong>Housing_Type</strong></td>
<td>The type of housing the student lives in (e.g., rented, owned, dormitory).</td>
</tr>
<tr class="even">
<td><strong>Goes_Out_Spends_Money</strong></td>
<td>How frequently the student goes out and spends money (1 = rarely, 5 = very often).</td>
</tr>
<tr class="odd">
<td><strong>Drinks_Alcohol</strong></td>
<td>Whether the student drinks alcohol (0 = No, 1 = Yes).</td>
</tr>
<tr class="even">
<td><strong>Net_Money</strong></td>
<td>The amount of money the student has left at the end of the month after income and expenses.</td>
</tr>
<tr class="odd">
<td><strong>Monthly_Earnings</strong></td>
<td>The student’s earnings from any part-time jobs or other income sources.</td>
</tr>
</tbody>
</table>
<p>Here’s a sample of the dataset:</p>
<div style="overflow-x: auto; white-space: nowrap;">
<table class="caption-top table">
<colgroup>
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 9%">
</colgroup>
<thead><tr class="header">
<th><strong>Has_Job</strong></th>
<th><strong>Year_of_Study</strong></th>
<th><strong>Financially_Dependent</strong></th>
<th><strong>Monthly_Allowance</strong></th>
<th><strong>Cooks_at_Home</strong></th>
<th><strong>Living_Situation</strong></th>
<th><strong>Housing_Type</strong></th>
<th><strong>Goes_Out_Spends_Money</strong></th>
<th><strong>Drinks_Alcohol</strong></th>
<th><strong>Net_Money</strong></th>
<th><strong>Monthly_Earnings</strong></th>
</tr></thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>1</td>
<td>0</td>
<td>658.99</td>
<td>0</td>
<td>3</td>
<td>1</td>
<td>6</td>
<td>0</td>
<td>529.34</td>
<td>0.00</td>
</tr>
<tr class="even">
<td>1</td>
<td>3</td>
<td>0</td>
<td>592.55</td>
<td>0</td>
<td>3</td>
<td>2</td>
<td>3</td>
<td>1</td>
<td>992.72</td>
<td>941.92</td>
</tr>
<tr class="odd">
<td>1</td>
<td>4</td>
<td>1</td>
<td>602.54</td>
<td>0</td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>1</td>
<td>557.30</td>
<td>876.57</td>
</tr>
</tbody>
</table>
</div>
<p>This dataset provides a structured way to analyze the financial habits of students and determine which factors contribute most to their financial stability.</p>
</section><section id="the-problem-were-trying-to-solve" class="level3" data-number="3.4.2"><h3 data-number="3.4.2" class="anchored" data-anchor-id="the-problem-were-trying-to-solve">
<span class="header-section-number">3.4.2</span> The Problem We’re Trying to Solve</h3>
<p>Our goal in this case study is to understand which factors impact a student’s net money. Specifically, we aim to identify which characteristics, such as having a job, monthly earnings, or financial support, explain why some students have more money left over at the end of the month than others.</p>
<p>The key question we want to answer is:</p>
<blockquote class="blockquote">
<p><strong>Which factors have the biggest influence on a student’s net money?</strong></p>
</blockquote>
<p>By applying OLS to this dataset, we can:</p>
<ul>
<li>Measure how much each factor contributes to variations in net money. For example, we can determine the increase in net money associated with a one-unit increase in monthly earnings.</li>
<li>Identify whether each factor has a positive or negative effect on net money.</li>
<li>Understand the unique contribution of each variable while accounting for the influence of others. This helps us isolate the effect of, say, having a job from that of receiving financial support.</li>
<li>Predict a student’s net money based on their characteristics. These insights could help institutions design targeted financial literacy programs or interventions to improve financial stability.</li>
<li>Evaluate the overall performance of our model using statistical measures such as R-squared and p-values. This not only confirms the significance of our findings but also guides improvements in future analyses.</li>
</ul>
<p>In summary, using OLS in this case study allows us to break down complex financial behaviors into understandable components. This powerful tool provides clear, actionable insights into which factors are most important, paving the way for more informed decisions and targeted interventions.</p>
</section><section id="study-design" class="level3" data-number="3.4.3"><h3 data-number="3.4.3" class="anchored" data-anchor-id="study-design">
<span class="header-section-number">3.4.3</span> Study Design</h3>
<p>Now that we’ve introduced our case study and dataset, it’s time to follow the data science workflow step by step. The first step is to define the main statistical inquiries we want to address. As mentioned earlier, our key question is:</p>
<blockquote class="blockquote">
<p><strong>Which factors have the biggest influence on a student’s net money?</strong></p>
</blockquote>
<p>To answer this question, we will adopt an inferential analysis approach rather than a predictive analysis approach. Let’s quickly review the difference between these two methods:</p>
<section id="inferential-vs.-predictive-analysis" class="level4"><h4 class="anchored" data-anchor-id="inferential-vs.-predictive-analysis">Inferential vs.&nbsp;Predictive Analysis</h4>
<ul>
<li>
<strong>Inferential Analysis</strong> explores and quantifies the relationships between explanatory variables (e.g., student characteristics) and the response variable (Net Money). For example, we might ask: Does having a part-time job significantly affect a student’s net money, and by how much? The goal here is to understand these effects and assess their statistical significance.</li>
<li>
<strong>Predictive Analysis</strong> focuses on accurately forecasting the response variable using new data. In this case, the question could be: Can we predict a student’s net money based on factors like monthly earnings, living situation, and spending habits? The emphasis is on building a model that produces reliable predictions, even if it doesn’t fully explain the underlying relationships.</li>
</ul></section></section><section id="applying-study-design-to-our-case-study" class="level3" data-number="3.4.4"><h3 data-number="3.4.4" class="anchored" data-anchor-id="applying-study-design-to-our-case-study">
<span class="header-section-number">3.4.4</span> Applying Study Design to Our Case Study</h3>
<p>For our case study, we are interested in understanding how factors such as Has_Job, Monthly_Earnings, and Spending_Habits affect a student’s Net Money. This leads us to adopt an inferential approach. We aim to answer questions like:</p>
<ul>
<li>Does having a part-time job lead to significantly higher net money?</li>
<li>How much do a student’s monthly earnings influence their financial situation?</li>
<li>Do spending habits, like going out frequently, decrease a student’s net money?</li>
</ul>
<p>Using OLS, we will estimate the impact of each factor and determine whether these effects are statistically significant. This inferential analysis will help us understand which variables have the greatest influence on students’ financial outcomes.</p>
<p>If our goal were instead to predict a student’s future Net Money based on their characteristics, we would adopt a predictive approach. Although our focus here is on inference, it’s important to recognize that OLS is versatile and can be applied in both contexts.</p>
</section></section><section id="data-collection-and-wrangling" class="level2" data-number="3.5"><h2 data-number="3.5" class="anchored" data-anchor-id="data-collection-and-wrangling">
<span class="header-section-number">3.5</span> Data Collection and Wrangling</h2>
<p>With the statistical questions clearly defined, the next step is to ensure that the data is appropriately prepared for analysis. Although we already have the dataset, it is valuable to consider how this data could have been collected to better understand its context and potential limitations.</p>
<section id="data-collection" class="level3" data-number="3.5.1"><h3 data-number="3.5.1" class="anchored" data-anchor-id="data-collection">
<span class="header-section-number">3.5.1</span> Data Collection</h3>
<p>For a study like ours, data on students’ financial behaviors could have been collected through various methods:</p>
<ul>
<li>
<strong>Surveys</strong>: Students might have been asked about their employment status, earnings, and spending habits through structured questionnaires. While surveys can capture self-reported financial behaviors, they may suffer from recall bias or social desirability bias.</li>
<li>
<strong>Administrative Data</strong>: Universities or employers may maintain records on student income and employment, providing a more objective source of financial information. However, access to such data may be limited due to privacy regulations.</li>
<li>
<strong>Financial Tracking Apps</strong>: Digital financial management tools can offer detailed, real-time data on student income and spending patterns. While these apps provide high granularity, they may introduce selection bias, as only students who use such apps would be represented in the dataset.</li>
</ul>
<p>Regardless of the data collection method, each approach presents challenges, such as missing data, reporting errors, or sample biases. Addressing these issues is a critical aspect of data wrangling.</p>
</section><section id="data-wrangling" class="level3" data-number="3.5.2"><h3 data-number="3.5.2" class="anchored" data-anchor-id="data-wrangling">
<span class="header-section-number">3.5.2</span> Data Wrangling</h3>
<p>Now that our dataset is ready, the next step is to clean and organize it so that it’s in the best possible shape for analysis using OLS. Data wrangling involves several steps that ensure our data is accurate, consistent, and ready for modeling. Here are some key tasks:</p>
<section id="handling-missing-data" class="level4"><h4 class="anchored" data-anchor-id="handling-missing-data">Handling Missing Data</h4>
<p>The first task is to ensure data integrity by checking for missing values. Missing data can occur for various reasons, such as unrecorded responses or errors in data entry. When we find missing values—for example, if some students don’t have recorded earnings or net money—we must decide how to handle these gaps. Common strategies include:</p>
<ul>
<li>
<strong>Removing incomplete records</strong>: If the amount of missing data is minimal or missingness is random.</li>
<li>
<strong>Imputing missing values</strong>: Using logical estimates or averages if missingness follows a systematic pattern.</li>
</ul>
<p>In our toy dataset, there are no missing values, as confirmed by:</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colSums</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">data</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Has_Job         Year_of_Study Financially_Dependent 
                    0                     0                     0 
    Monthly_Allowance         Cooks_at_Home      Living_Situation 
                    0                     0                     0 
         Housing_Type Goes_Out_Spends_Money        Drinks_Alcohol 
                    0                     0                     0 
            Net_Money      Monthly_Earnings 
                    0                     0 </code></pre>
</div>
</div>
</section><section id="encoding-categorical-variables" class="level4"><h4 class="anchored" data-anchor-id="encoding-categorical-variables">Encoding Categorical Variables</h4>
<p>For regression analysis, we need to convert categorical variables into numerical representations. In R, binary variables like Has_Job and Drinks_Alcohol should be transformed into factors so that the model correctly interprets them as categorical data rather than continuous numbers. For example:</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Convert binary categorical variables to factors</span></span>
<span><span class="va">data</span> <span class="op">&lt;-</span> <span class="va">data</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span>Has_Job <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">Has_Job</span><span class="op">)</span>,</span>
<span>         Drinks_Alcohol <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">Drinks_Alcohol</span><span class="op">)</span>,</span>
<span>         Financially_Dependent <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">Financially_Dependent</span><span class="op">)</span>,</span>
<span>         Cooks_at_Home <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">Cooks_at_Home</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="detecting-and-handling-outliers" class="level4"><h4 class="anchored" data-anchor-id="detecting-and-handling-outliers">Detecting and Handling Outliers</h4>
<p>Outliers in continuous variables like Monthly_Earnings and Net_Money can distort the regression analysis by skewing results. We use the <strong>Interquartile Range (IQR)</strong> method to identify these extreme values. Specifically, any observation falling below 1.5 times the IQR below the first quartile (Q1) or above 1.5 times the IQR above the third quartile (Q3) is flagged as an outlier. These outliers are then treated as missing values and removed:</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Using IQR method to filter out extreme values in continuous variables</span></span>
<span><span class="va">remove_outliers</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">Q1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">x</span>, <span class="fl">0.25</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span>  <span class="va">Q3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">x</span>, <span class="fl">0.75</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span>  <span class="va">IQR</span> <span class="op">&lt;-</span> <span class="va">Q3</span> <span class="op">-</span> <span class="va">Q1</span></span>
<span>  <span class="va">x</span><span class="op">[</span><span class="va">x</span> <span class="op">&lt;</span> <span class="op">(</span><span class="va">Q1</span> <span class="op">-</span> <span class="fl">1.5</span> <span class="op">*</span> <span class="va">IQR</span><span class="op">)</span> <span class="op">|</span> <span class="va">x</span> <span class="op">&gt;</span> <span class="op">(</span><span class="va">Q3</span> <span class="op">+</span> <span class="fl">1.5</span> <span class="op">*</span> <span class="va">IQR</span><span class="op">)</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="cn">NA</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="va">data</span> <span class="op">&lt;-</span> <span class="va">data</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span><span class="fu">across</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">Monthly_Earnings</span>, <span class="va">Net_Money</span><span class="op">)</span>, <span class="va">remove_outliers</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Remove rows with newly introduced NAs due to outlier handling</span></span>
<span><span class="va">data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/na.fail.html">na.omit</a></span><span class="op">(</span><span class="va">data</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="splitting-the-data-for-model-training" class="level4"><h4 class="anchored" data-anchor-id="splitting-the-data-for-model-training">Splitting the Data for Model Training</h4>
<p>To ensure that our OLS model generalizes well to unseen data, we split the dataset into training and testing subsets. The training set is used to estimate the model parameters, and the testing set is used to evaluate the model’s performance. This split is typically done in an 80/20 ratio, as shown below:</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Splitting the dataset into training and testing sets</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span>  <span class="co"># For reproducibility</span></span>
<span><span class="va">train_indices</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_len</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">data</span><span class="op">)</span><span class="op">)</span>, size <span class="op">=</span> <span class="fl">0.8</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">data</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">train_data</span> <span class="op">&lt;-</span> <span class="va">data</span><span class="op">[</span><span class="va">train_indices</span>, <span class="op">]</span></span>
<span><span class="va">test_data</span> <span class="op">&lt;-</span> <span class="va">data</span><span class="op">[</span><span class="op">-</span><span class="va">train_indices</span>, <span class="op">]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>By following these steps, checking for missing values, encoding categorical variables, handling outliers, and splitting the data, we ensure that our dataset is clean, well-organized, and ready for regression analysis using OLS.</p>
<p>It’s important to note, however, that these are just a few of the many techniques available during the data wrangling stage. Depending on the dataset and the specific goals of your analysis, you might also consider additional strategies such as feature scaling, normalization, advanced feature engineering, handling duplicate records, or addressing imbalanced data. Each of these techniques comes with its own set of solutions, and the optimal approach will depend on the unique challenges and objectives of your case.</p>
</section></section></section><section id="exploratory-data-analysis-eda" class="level2" data-number="3.6"><h2 data-number="3.6" class="anchored" data-anchor-id="exploratory-data-analysis-eda">
<span class="header-section-number">3.6</span> Exploratory Data Analysis (EDA)</h2>
<p>Before diving into data modeling, it is crucial to develop a deep understanding of the relationships between variables in the dataset. This stage, known as Exploratory Data Analysis (EDA), helps us visualize and summarize the data, uncover patterns, detect anomalies, and test key assumptions that will inform our modeling decisions.</p>
<section id="classifying-variables" class="level3" data-number="3.6.1"><h3 data-number="3.6.1" class="anchored" data-anchor-id="classifying-variables">
<span class="header-section-number">3.6.1</span> Classifying Variables</h3>
<p>The first step in EDA is to classify variables according to their types. This classification guides the selection of appropriate visualization techniques and modeling strategies. In our toy dataset, we categorize variables as follows:</p>
<ul>
<li>
<code>Net_Money</code> serves as the response variable, representing a continuous outcome constrained by realistic income and expenses.</li>
</ul>
<p>The regressors include a mix of binary, categorical, ordinal, and continuous variables.</p>
<ul>
<li>Binary variables, such as Has_Job and Drinks_Alcohol, take on only two values and need to be encoded for modeling.</li>
<li>Categorical variables, like Living_Situation and Housing_Type, represent qualitative distinctions between different student groups.</li>
<li>Some predictors, like Year_of_Study and Goes_Out_Spends_Money, follow an ordinal structure, meaning they have a meaningful ranking but no consistent numerical spacing.</li>
<li>Finally, Monthly_Allowance and Monthly_Earnings are continuous variables, requiring attention to their distributions and potential outliers.</li>
</ul>
<p>By classifying variables correctly at the outset, we ensure that they are analyzed and interpreted appropriately throughout the modeling process.</p>
</section><section id="visualizing-variable-distributions" class="level3" data-number="3.6.2"><h3 data-number="3.6.2" class="anchored" data-anchor-id="visualizing-variable-distributions">
<span class="header-section-number">3.6.2</span> Visualizing Variable Distributions</h3>
<p>Once variables are classified, the next step is to explore their distributions. Understanding how variables are distributed is crucial for identifying potential issues such as skewness, outliers, or missing values. We employ different visualizations depending on the variable type:</p>
<section id="continuous-variables" class="level4"><h4 class="anchored" data-anchor-id="continuous-variables">Continuous Variables</h4>
<p>We begin by examining continuous variables, which are best visualized using histograms and boxplots.</p>
<section id="histograms" class="level5"><h5 class="anchored" data-anchor-id="histograms">Histograms</h5>
<p>Histograms display the frequency distribution of a continuous variable. They allow us to assess the overall shape, central tendency, and spread of the data. For example, the histogram of Net_Money helps us determine if the variable follows a roughly normal distribution or if it is skewed. A normal distribution often appears bell-shaped, while skewness can indicate that the data might benefit from transformations (like logarithmic transformations) to meet the assumptions of regression analysis. In our case, the histogram below shows that Net_Money appears roughly normal.</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Histogram of Net_Money</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/hist.html">hist</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">$</span><span class="va">Net_Money</span>, </span>
<span>     main <span class="op">=</span> <span class="st">"Distribution of Net Money"</span>, </span>
<span>     xlab <span class="op">=</span> <span class="st">"Net Money"</span>, </span>
<span>     col <span class="op">=</span> <span class="st">"blue"</span>, </span>
<span>     border <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03-ols_files/figure-html/eda-histogram-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section><section id="boxplots" class="level5"><h5 class="anchored" data-anchor-id="boxplots">Boxplots</h5>
<p>Boxplots provide a concise summary of a variable’s distribution by displaying its quartiles and highlighting potential outliers. Outliers are typically defined as data points that fall below Q1 - 1.5 * IQR or above Q3 + 1.5 * IQR. The boxplot below visualizes Net_Money and helps us quickly assess if there are any extreme values that might skew the analysis. In this case, the boxplot suggests that there are no significant outliers according to the IQR method (the method commonly used by ggplot to identify outliers).</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Boxplot of Net Money</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/boxplot.html">boxplot</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">$</span><span class="va">Net_Money</span>, </span>
<span>        main <span class="op">=</span> <span class="st">"Boxplot of Net Money"</span>, </span>
<span>        ylab <span class="op">=</span> <span class="st">"Net Money"</span>, </span>
<span>        col <span class="op">=</span> <span class="st">"lightblue"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03-ols_files/figure-html/eda-boxplot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>By visualizing the distribution of Net_Money with these plots, we gain valuable insights into its behavior. This understanding not only informs whether transformations are needed but also prepares us for deeper analysis as we move forward with regression modeling.</p>
</section></section><section id="categorical-and-ordinal-variables" class="level4"><h4 class="anchored" data-anchor-id="categorical-and-ordinal-variables">Categorical and Ordinal Variables</h4>
<p>Categorical variables require a different approach from continuous ones because they represent distinct groups rather than numerical values. For these variables, bar charts are very effective. They display the frequency of each category, helping us understand the distribution of qualitative attributes.</p>
<p>For example, consider the variable Living_Situation. The bar chart below shows how many students fall into each category. From the chart, we can see that category 1 is more heavily represented, while categories 2 and 3 have roughly similar counts. This insight can be critical—if a category is underrepresented, you might need to consider grouping it with similar categories or applying techniques such as one-hot encoding to ensure that each category contributes appropriately to the model.</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Bar plot of Living Situation</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">$</span><span class="va">Living_Situation</span><span class="op">)</span>, </span>
<span>        main <span class="op">=</span> <span class="st">"Living Situation Distribution"</span>, </span>
<span>        xlab <span class="op">=</span> <span class="st">"Living Situation"</span>, </span>
<span>        ylab <span class="op">=</span> <span class="st">"Frequency"</span>, </span>
<span>        col <span class="op">=</span> <span class="st">"purple"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03-ols_files/figure-html/eda-barcharts-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For ordinal variables (which have a natural order but not a fixed numerical interval), you might still use bar charts to show the ranking or frequency of each level. Additionally, understanding these distributions can help you decide whether to treat them as categorical variables or convert them into numeric scores for analysis.</p>
</section><section id="exploring-relationships-between-variables" class="level4"><h4 class="anchored" data-anchor-id="exploring-relationships-between-variables">Exploring Relationships Between Variables</h4>
<p>Beyond examining individual variables, it is crucial to explore how they interact with one another—especially the predictors and the response variable. Understanding these relationships helps identify which predictors might be influential in the model and whether any issues, like multicollinearity, could affect regression estimates.</p>
<section id="correlation-matrices" class="level5"><h5 class="anchored" data-anchor-id="correlation-matrices">Correlation Matrices</h5>
<p>For continuous variables, correlation matrices provide a numerical summary of how strongly pairs of variables are related. High correlations between predictors might signal multicollinearity, which can distort model estimates. For demonstration, consider the correlation matrix computed for Net_Money, Monthly_Allowance, and Monthly_Earnings:</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Correlation matrix</span></span>
<span><span class="va">cor_matrix</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Net_Money"</span>, <span class="st">"Monthly_Allowance"</span>, <span class="st">"Monthly_Earnings"</span><span class="op">)</span><span class="op">]</span>, use <span class="op">=</span> <span class="st">"complete.obs"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">cor_matrix</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  Net_Money Monthly_Allowance Monthly_Earnings
Net_Money         1.0000000        0.28835746       0.75743542
Monthly_Allowance 0.2883575        1.00000000      -0.03669097
Monthly_Earnings  0.7574354       -0.03669097       1.00000000</code></pre>
</div>
</div>
<p>In the output, we observe a strong positive correlation (corr = 0.757) between Monthly_Earnings and Net_Money. This result is intuitive. Higher earnings typically lead to more money left at the end of the month, resulting in a higher Net_Money.</p>
</section></section><section id="scatterplots" class="level4"><h4 class="anchored" data-anchor-id="scatterplots">Scatterplots</h4>
<p>Scatter plots visually depict the relationship between two continuous variables. For example, plotting Monthly_Allowance against Net_Money helps us assess whether students with higher allowances tend to have higher or lower net savings. In the scatter plot below, a slightly positive trend is visible. However, the points are quite scattered, indicating that while there may be a relationship, it is not overwhelmingly strong. Such visual insights might prompt further investigation, perhaps considering polynomial transformations or interaction terms if nonlinearity is suspected.</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Scatter plot of Monthly Allowance vs. Net Money</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">$</span><span class="va">Monthly_Allowance</span>, <span class="va">train_data</span><span class="op">$</span><span class="va">Net_Money</span>, </span>
<span>     main <span class="op">=</span> <span class="st">"Net Money vs. Monthly Allowance"</span>, </span>
<span>     xlab <span class="op">=</span> <span class="st">"Monthly Allowance"</span>, </span>
<span>     ylab <span class="op">=</span> <span class="st">"Net Money"</span>, </span>
<span>     col <span class="op">=</span> <span class="st">"blue"</span>, </span>
<span>     pch <span class="op">=</span> <span class="fl">19</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Net_Money</span> <span class="op">~</span> <span class="va">Monthly_Allowance</span>, data <span class="op">=</span> <span class="va">train_data</span><span class="op">)</span>, col <span class="op">=</span> <span class="st">"red"</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03-ols_files/figure-html/eda-scatterplot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="boxplots-for-categorical-variables" class="level5"><h5 class="anchored" data-anchor-id="boxplots-for-categorical-variables">Boxplots for Categorical Variables</h5>
<p>For categorical predictors, boxplots are an excellent tool to compare the distribution of the response variable across different groups. For instance, examining how Net_Money varies by Living_Situation can reveal whether students in different living arrangements experience different financial outcomes. In the boxplot below, the distributions of Net_Money across categories of Living_Situation appear quite similar. This similarity may suggest that Living_Situation has little impact on Net_Money in our dataset.</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Boxplot of Net Money by Living Situation</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/boxplot.html">boxplot</a></span><span class="op">(</span><span class="va">Net_Money</span> <span class="op">~</span> <span class="va">Living_Situation</span>, </span>
<span>        data <span class="op">=</span> <span class="va">train_data</span>, </span>
<span>        main <span class="op">=</span> <span class="st">"Net Money by Living Situation"</span>, </span>
<span>        xlab <span class="op">=</span> <span class="st">"Living Situation"</span>, </span>
<span>        ylab <span class="op">=</span> <span class="st">"Net Money"</span>, </span>
<span>        col <span class="op">=</span> <span class="st">"lightgreen"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03-ols_files/figure-html/eda-multiple-boxplots-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section></section><section id="summary-statistics" class="level4"><h4 class="anchored" data-anchor-id="summary-statistics">Summary Statistics</h4>
<p>In addition to visual exploration, descriptive statistics provide a numerical summary of the dataset that is especially useful for beginners. Summary statistics give you a snapshot of the central tendency and spread of your data, helping you quickly grasp its overall characteristics.</p>
<p>For instance, if you notice that the mean of Monthly_Earning is significantly higher than its median, it might suggest that a few high values (or outliers) are skewing the data.</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Summary statistics for numerical variables</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Net_Money"</span>, <span class="st">"Monthly_Allowance"</span>, <span class="st">"Monthly_Earnings"</span><span class="op">)</span><span class="op">]</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Net_Money        Monthly_Allowance Monthly_Earnings
 Min.   :-1587.52   Min.   :  51.33   Min.   :   0    
 1st Qu.: -399.87   1st Qu.: 402.50   1st Qu.:   0    
 Median :   78.36   Median : 500.55   Median : 291    
 Mean   :  120.74   Mean   : 501.85   Mean   : 502    
 3rd Qu.:  618.59   3rd Qu.: 603.46   3rd Qu.:1014    
 Max.   : 1932.42   Max.   :1088.94   Max.   :1763    </code></pre>
</div>
</div>
</section></section><section id="key-takeaways-from-eda" class="level3" data-number="3.6.3"><h3 data-number="3.6.3" class="anchored" data-anchor-id="key-takeaways-from-eda">
<span class="header-section-number">3.6.3</span> Key Takeaways from EDA</h3>
<p>Conducting Exploratory Data Analysis (EDA) allows us to gain an initial understanding of the data and its underlying patterns before moving on to model building. Through EDA, we identify the types of variables present, examine their distributions, and uncover potential issues such as skewness, outliers, or multicollinearity. This process helps to highlight which variables might be strong predictors and which may require additional transformation or treatment. For instance, a strong correlation between two variables, like Monthly_Earnings and Net_Money, signals that earnings are likely a key driver of net savings. At the same time, observing differences in distributions or spotting similar patterns across groups in boxplots can inform us about the impact of categorical factors like Living_Situation.</p>
<p>It is important to remember that the insights gained from EDA are preliminary and primarily serve to inform further analysis. When we explore relationships between only two variables, we might overlook the influence of other factors, which could lead to misleading conclusions if taken in isolation. EDA is a crucial step for forming initial hypotheses and guiding decisions regarding data transformations, feature engineering, and the overall modeling strategy. With this foundation, we are better prepared to build a robust Ordinary Least Squares (OLS) regression model on data that has been carefully examined and understood.</p>
</section></section><section id="data-modelling" class="level2" data-number="3.7"><h2 data-number="3.7" class="anchored" data-anchor-id="data-modelling">
<span class="header-section-number">3.7</span> Data Modelling</h2>
<p>After conducting Exploratory Data Analysis (EDA), we transition to the modeling stage, where we apply a structured approach to uncover relationships between variables and predict outcomes. In this section, we focus on Ordinary Least Squares (OLS) regression, a widely used statistical technique for modeling linear relationships.</p>
<p>OLS aims to estimate the effect of multiple predictors on an outcome variable by minimizing the sum of squared differences between observed and predicted values. This approach helps quantify financial behaviors, allowing us to interpret the impact of various factors on students’ net financial balance.</p>
<section id="choosing-a-suitable-regression-model" class="level3" data-number="3.7.1"><h3 data-number="3.7.1" class="anchored" data-anchor-id="choosing-a-suitable-regression-model">
<span class="header-section-number">3.7.1</span> Choosing a Suitable Regression Model</h3>
<p>The choice of regression model depends on the patterns identified in EDA and the objectives of our analysis. Regression techniques vary in complexity, with some handling simple linear relationships and others accounting for more nuanced effects. Below are common approaches:</p>
<ul>
<li>
<strong>Simple Linear Regression</strong> models the relationship between a single predictor and the response variable. This approach is suitable when we suspect a dominant factor driving financial balance.</li>
<li>
<strong>Multiple Linear Regression</strong> extends simple regression by incorporating multiple predictors, allowing us to account for various financial influences simultaneously.</li>
<li>
<strong>Polynomial Regression</strong> captures non-linear relationships by introducing polynomial terms of predictors, useful when relationships observed in scatter plots are curved rather than strictly linear.</li>
<li>
<strong>Log-Linear Models</strong> transform skewed distributions to improve interpretability and meet regression assumptions.</li>
<li>
<strong>Regularized Regression (Ridge and Lasso)</strong> applies penalties to regression coefficients to handle multicollinearity and enhance model generalization by reducing overfitting.</li>
</ul>
<p>Given that our goal is to examine how multiple factors—such as income, expenses, and living arrangements—affect students’ financial balance, we select Multiple Linear Regression via OLS. This method allows us to quantify the influence of each predictor while controlling for confounding effects.</p>
</section><section id="defining-modeling-parameters" class="level3" data-number="3.7.2"><h3 data-number="3.7.2" class="anchored" data-anchor-id="defining-modeling-parameters">
<span class="header-section-number">3.7.2</span> Defining Modeling Parameters</h3>
<p>Once we select OLS regression, we define the key modeling components: the response variable (dependent variable) and the predictor variables (independent variables).</p>
<section id="response-variable-y" class="level4"><h4 class="anchored" data-anchor-id="response-variable-y">Response Variable (Y):</h4>
<p>The response variable, also known as the dependent variable, represents the financial outcome we aim to explain:</p>
<ul>
<li>
<code>Net_Money</code>: The dependent variable representing financial balance.</li>
</ul></section><section id="predictor-variables-x" class="level4"><h4 class="anchored" data-anchor-id="predictor-variables-x">Predictor Variables (X):</h4>
<p>Each predictor variable is chosen based on its theoretical and statistical relevance in explaining financial behavior:</p>
<ul>
<li>
<code>Has_Job</code> (Binary) – Indicates whether the student has a job (1 = Yes, 0 = No).</li>
<li>
<code>Financially_Dependent</code> (Binary) – Identifies students who rely on external financial support.</li>
<li>
<code>Year_of_Study</code> (Ordinal) – Represents academic seniority (higher values indicate later years).</li>
<li>
<code>Goes_Out_Spends_Money</code> (Ordinal) – Measures spending behavior on a scale from 1 to 6.</li>
<li>
<code>Drinks_Alcohol</code> (Binary) – Identifies whether a student consumes alcohol, which may impact discretionary spending.</li>
<li>
<code>Monthly_Allowance</code> (Continuous) – Represents financial support received from family or scholarships.</li>
<li>
<code>Monthly_Earnings</code> (Continuous) – Reflects the student’s personal income from work.</li>
<li>
<code>Living_Situation</code> (Categorical) – Encodes different living arrangements (e.g., dormitory, shared apartment, living with family).</li>
<li>
<code>Housing_Type</code> (Categorical) – Further distinguishes between different types of housing situations.</li>
<li>
<code>Cooks_at_Home</code> (Binary) – Indicates whether the student regularly prepares meals at home.</li>
</ul>
<p>These predictors capture a mix of economic, behavioral, and lifestyle factors, providing a comprehensive view of the drivers of student financial balance.</p>
</section></section><section id="setting-up-the-modeling-equation" class="level3" data-number="3.7.3"><h3 data-number="3.7.3" class="anchored" data-anchor-id="setting-up-the-modeling-equation">
<span class="header-section-number">3.7.3</span> Setting Up the Modeling Equation</h3>
<p>With all predictors defined, the OLS regression equation models the relationship between Net_Money and the predictor variables:</p>
<p><span class="math display">\[
\begin{align}
\text{Net_Money} = \beta_0 \\
               &amp; + \beta_1 \times \text{Has_Job} \\
               &amp; + \beta_2 \times \text{Financially_Dependent} \\
               &amp; + \beta_3 \times \text{Year_of_Study} \\
               &amp; + \beta_4 \times \text{Goes_Out_Spends_Money} \\
               &amp; + \beta_5 \times \text{Drinks_Alcohol} \\
               &amp; + \beta_6 \times \text{Monthly_Allowance} \\
               &amp; + \beta_7 \times \text{Monthly_Earnings} \\
               &amp; + \beta_8 \times \text{Living_Situation} \\
               &amp; + \beta_9 \times \text{Housing_Type} \\
               &amp; + \beta_{10} \times \text{Cooks_at_Home} \\
               &amp; + \epsilon
\end{align}
\]</span></p>
<p>where:</p>
<ul>
<li>
<span class="math inline">\(\beta_0\)</span> represents the intercept, or the baseline Net Money when all predictors are set to zero.</li>
<li>
<span class="math inline">\(\beta_1, \beta_2, ..., \beta_{10}\)</span> are the regression coefficients, quantifying the impact of each predictor on financial balance.</li>
<li>
<span class="math inline">\(\epsilon\)</span> is the error term, accounting for unexplained variability and random noise.</li>
</ul>
<p>Each coefficient provides insight into how <code>Net_Money</code> changes when a specific predictor increases by one unit, holding all other factors constant. For example:</p>
<ul>
<li>
<span class="math inline">\(\beta_5\)</span> (Drinks Alcohol) measures the financial impact of alcohol consumption, which may reflect higher discretionary spending.</li>
<li>
<span class="math inline">\(\beta_6\)</span> (Monthly Allowance) quantifies the increase in Net_Money per additional dollar of allowance.</li>
<li>
<span class="math inline">\(\beta_10\)</span> (Cooks at Home) indicates how much more (or less) financially stable students are when they cook at home instead of eating out.</li>
</ul>
<p>If significant interaction effects exist—such as students who live independently having a different financial impact from increased earnings compared to those living with family—we can extend the model by adding interaction terms.</p>
</section></section><section id="estimation" class="level2" data-number="3.8"><h2 data-number="3.8" class="anchored" data-anchor-id="estimation">
<span class="header-section-number">3.8</span> Estimation</h2>
<p>With the data modeling stage completed, we now move to estimation, where we fit the Ordinary Least Squares (OLS) regression model to the data and obtain numerical estimates for the regression coefficients. These estimates quantify how much each predictor contributes to the response variable, allowing us to measure their individual effects on Net Money.</p>
<p>The goal of estimation is to determine the best-fitting regression line by minimizing the sum of squared residuals—the differences between the observed and predicted values. This step provides a mathematical basis for analyzing financial behaviors in students.</p>
<section id="fitting-the-model" class="level3" data-number="3.8.1"><h3 data-number="3.8.1" class="anchored" data-anchor-id="fitting-the-model">
<span class="header-section-number">3.8.1</span> Fitting the Model</h3>
<p>To estimate the regression coefficients, we fit the OLS model to the training data using Python (<code>statsmodels</code>) or R (<code>lm</code>). The model is trained using least squares estimation, which finds the coefficients that minimize the total squared error between observed values and predictions.</p>
<p>In R, we can fit the regression model using the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function:</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Load necessary library</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">stats</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Fit the OLS model</span></span>
<span><span class="va">ols_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Net_Money</span> <span class="op">~</span> <span class="va">Has_Job</span> <span class="op">+</span> <span class="va">Financially_Dependent</span> <span class="op">+</span> <span class="va">Year_of_Study</span> <span class="op">+</span> <span class="va">Goes_Out_Spends_Money</span> <span class="op">+</span> <span class="va">Drinks_Alcohol</span> <span class="op">+</span> <span class="va">Monthly_Allowance</span> <span class="op">+</span> <span class="va">Monthly_Earnings</span> <span class="op">+</span> <span class="va">Living_Situation</span> <span class="op">+</span> <span class="va">Housing_Type</span> <span class="op">+</span> <span class="va">Cooks_at_Home</span>, data <span class="op">=</span> <span class="va">train_data</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Display summary of model results</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">ols_model</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Net_Money ~ Has_Job + Financially_Dependent + Year_of_Study + 
    Goes_Out_Spends_Money + Drinks_Alcohol + Monthly_Allowance + 
    Monthly_Earnings + Living_Situation + Housing_Type + Cooks_at_Home, 
    data = train_data)

Residuals:
   Min     1Q Median     3Q    Max 
-742.4 -144.9   14.7  157.9  675.1 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            -595.37433   46.68928 -12.752  &lt; 2e-16 ***
Has_Job1                 73.93112   39.75871   1.859   0.0633 .  
Financially_Dependent1 -499.36309   15.42689 -32.370  &lt; 2e-16 ***
Year_of_Study           -96.51877    6.85478 -14.081  &lt; 2e-16 ***
Goes_Out_Spends_Money   -54.60494    3.93783 -13.867  &lt; 2e-16 ***
Drinks_Alcohol1        -145.10637   15.74322  -9.217  &lt; 2e-16 ***
Monthly_Allowance         1.47138    0.05200  28.295  &lt; 2e-16 ***
Monthly_Earnings          0.94906    0.03704  25.625  &lt; 2e-16 ***
Living_Situation        102.95241    9.32478  11.041  &lt; 2e-16 ***
Housing_Type             56.65388    9.72781   5.824 8.38e-09 ***
Cooks_at_Home1          -96.31098   15.83074  -6.084 1.83e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 216.4 on 786 degrees of freedom
Multiple R-squared:  0.9018,    Adjusted R-squared:  0.9006 
F-statistic: 722.1 on 10 and 786 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section><section id="interpreting-the-coefficients" class="level3" data-number="3.8.2"><h3 data-number="3.8.2" class="anchored" data-anchor-id="interpreting-the-coefficients">
<span class="header-section-number">3.8.2</span> Interpreting the Coefficients</h3>
<p>After fitting the model, we examine the estimated coefficients to understand their impact. Each coefficient obtained from the OLS regression represents the expected change in Net_Money for a one-unit increase in the corresponding predictor, holding all other variables constant. The estimated regression equation can be expressed as:</p>
<p><span class="math display">\[
\begin{align}
\text{Net_Money} = -595.37 \\
               &amp; + 73.93 \times \text{Has_Job} \\
               &amp; - 499.36 \times \text{Financially_Dependent} \\
               &amp; - 96.52 \times \text{Year_of_Study} \\
               &amp; - 54.60 \times \text{Goes_Out_Spends_Money} \\
               &amp; - 145.11 \times \text{Drinks_Alcohol} \\
               &amp; + 1.47 \times \text{Monthly_Allowance} \\
               &amp; + 0.95 \times \text{Monthly_Earnings} \\
               &amp; + 102.95 \times \text{Living_Situation} \\
               &amp; + 56.65 \times \text{Housing_Type} \\
               &amp; - 96.31 \times \text{Cooks_at_Home} \\
               &amp; + \epsilon
\end{align}
\]</span></p>
<p>For example:</p>
<ul>
<li>The intercept (<span class="math inline">\(\beta_0=-595.37\)</span>) represents the expected financial balance for a student who has zero income, allowance, and falls at the baseline category for all categorical variables.</li>
<li>A <span class="math inline">\(1 increase in Monthly Allowance (\)</span>_6=1.47$) is associated with a $1.47 increase in Net Money, meaning students with higher allowances tend to have a higher financial balance.</li>
</ul>
<p>These estimates provide an initial understanding of the direction and magnitude of relationships between predictors and financial balance. However, before drawing conclusions, we need to validate model assumptions and evaluate the statistical significance of each coefficient.</p>
</section></section><section id="goodness-of-fit" class="level2" data-number="3.9"><h2 data-number="3.9" class="anchored" data-anchor-id="goodness-of-fit">
<span class="header-section-number">3.9</span> Goodness of Fit</h2>
<p>After estimating the regression coefficients, the next step is to assess how well the model fits the data and whether it satisfies the assumptions of Ordinary Least Squares (OLS) regression. This evaluation ensures that the model is not only statistically valid but also generalizes well to unseen data. A well-fitting model should explain a substantial proportion of variation in the response variable while adhering to key statistical assumptions. If these assumptions are violated, model estimates may be biased, leading to misleading conclusions.</p>
<section id="checking-model-assumptions" class="level3" data-number="3.9.1"><h3 data-number="3.9.1" class="anchored" data-anchor-id="checking-model-assumptions">
<span class="header-section-number">3.9.1</span> Checking Model Assumptions</h3>
<p>OLS regression is built on several fundamental assumptions:</p>
<ul>
<li>linearity</li>
<li>independence of errors</li>
<li>homoscedasticity</li>
<li>normality of residuals</li>
</ul>
<p>If these assumptions hold, OLS provides unbiased, efficient, and consistent estimates. We assess each assumption through diagnostic plots and statistical tests.</p>
<section id="linearity" class="level4"><h4 class="anchored" data-anchor-id="linearity">Linearity</h4>
<p>A core assumption of OLS is that the relationship between each predictor and the response variable is linear. If this assumption is violated, the model may systematically under- or overestimate Net_Money, leading to biased predictions. The Residuals vs.&nbsp;Fitted values plot is a common diagnostic tool for checking linearity. In a well-specified linear model, residuals should be randomly scattered around zero, without any discernible patterns. If the residuals exhibit a U-shaped or curved pattern, this suggests a non-linear relationship, indicating that transformations such as logarithmic, square root, or polynomial terms may be necessary.</p>
<p>To visualize linearity, we plot the residuals against the fitted values:</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Residuals vs Fitted plot (R)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">ols_model</span><span class="op">$</span><span class="va">fitted.values</span>, <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">ols_model</span><span class="op">)</span>, </span>
<span>     main <span class="op">=</span> <span class="st">"Residuals vs Fitted"</span>, xlab <span class="op">=</span> <span class="st">"Fitted Values"</span>, ylab <span class="op">=</span> <span class="st">"Residuals"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span>h <span class="op">=</span> <span class="fl">0</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03-ols_files/figure-html/model-assumption-linearity-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>If the residual plot displays a clear trend, polynomial regression or feature engineering may be required to better capture the underlying data structure.</p>
</section><section id="independence-of-errors" class="level4"><h4 class="anchored" data-anchor-id="independence-of-errors">Independence of Errors</h4>
<p>The residuals, or errors, in an OLS model should be independent of one another. This assumption is particularly relevant in time-series or sequential data, where errors from one observation might influence subsequent observations, leading to autocorrelation. If the errors are correlated, the estimated standard errors will be biased, making hypothesis testing unreliable.</p>
<p>The Durbin-Watson test is commonly used to detect autocorrelation. This test produces a statistic that ranges between 0 and 4, where values close to 2 indicate no significant autocorrelation, while values near 0 or 4 suggest positive or negative correlation in the residuals.</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">dwtest</span><span class="op">(</span><span class="va">ols_model</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Durbin-Watson test

data:  ols_model
DW = 1.9581, p-value = 0.2777
alternative hypothesis: true autocorrelation is greater than 0</code></pre>
</div>
</div>
<p>If the test suggests autocorrelation, a possible solution is to use time-series regression models such as Autoregressive Integrated Moving Average (ARIMA) or introduce lagged predictors to account for dependencies in the data.</p>
</section><section id="homoscedasticity-constant-variance-of-errors" class="level4"><h4 class="anchored" data-anchor-id="homoscedasticity-constant-variance-of-errors">Homoscedasticity (Constant Variance of Errors)</h4>
<p>OLS regression assumes that the variance of residuals remains constant across all fitted values. If this assumption is violated, the model exhibits heteroscedasticity, where the spread of residuals increases or decreases systematically. This can result in inefficient coefficient estimates, making some predictors appear statistically significant when they are not.</p>
<p>To check for heteroscedasticity, we plot residuals against the fitted values and conduct a Breusch-Pagan test, which formally tests whether residual variance is constant.</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ncvTest</span><span class="op">(</span><span class="va">ols_model</span><span class="op">)</span>  <span class="co"># Test for homoscedasticity</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 0.4018794, Df = 1, p = 0.52612</code></pre>
</div>
</div>
<p>If heteroscedasticity is detected, solutions include applying weighted least squares (WLS) regression, transforming the dependent variable (e.g., using a log transformation), or computing robust standard errors to correct for variance instability.</p>
</section><section id="normality-of-residuals" class="level4"><h4 class="anchored" data-anchor-id="normality-of-residuals">Normality of Residuals</h4>
<p>For valid hypothesis testing and confidence interval estimation, OLS assumes that residuals follow a normal distribution. If residuals deviate significantly from normality, statistical inference may be unreliable, particularly for small sample sizes.</p>
<p>A Q-Q plot (Quantile-Quantile plot) is used to assess normality. If residuals are normally distributed, the points should lie along the reference line.</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqnorm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">ols_model</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqline</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">ols_model</span><span class="op">)</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03-ols_files/figure-html/model-assumption-normality-residuals-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>If the plot reveals heavy tails or skewness, potential solutions include applying log or Box-Cox transformations to normalize the distribution. In cases where normality is severely violated, using a non-parametric model or bootstrapping confidence intervals may be appropriate.</p>
</section></section><section id="evaluating-model-fit" class="level3" data-number="3.9.2"><h3 data-number="3.9.2" class="anchored" data-anchor-id="evaluating-model-fit">
<span class="header-section-number">3.9.2</span> Evaluating Model Fit</h3>
<p>A good model should explain a large proportion of variance in the response variable.</p>
<section id="r-squared" class="level4"><h4 class="anchored" data-anchor-id="r-squared">R-Squared</h4>
<p>Beyond checking assumptions, it is essential to assess how well the model explains variability in the response variable. One of the most commonly used metrics is R-Squared (<span class="math inline">\(R^2\)</span>), which measures the proportion of variance in Net_Money that is explained by the predictors. An <span class="math inline">\(R^2\)</span> value close to 1 indicates a strong model fit, whereas a low value suggests that important predictors may be missing or that the model is poorly specified.</p>
<p>We can retrieve the R-squared and Adjusted R-squared values from the model summary:</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">ols_model</span><span class="op">)</span><span class="op">$</span><span class="va">r.squared</span>  <span class="co"># R-squared value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9018396</code></pre>
</div>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">ols_model</span><span class="op">)</span><span class="op">$</span><span class="va">adj.r.squared</span>  <span class="co"># Adjusted R-squared</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9005907</code></pre>
</div>
</div>
<p>While <span class="math inline">\(R^2\)</span> provides insight into model fit, it has limitations. Adding more predictors will always increase <span class="math inline">\(R^2\)</span>, even if those predictors have little explanatory power. Adjusted R-squared accounts for this by penalizing unnecessary variables, making it a better indicator of true model performance.</p>
<p>A high <span class="math inline">\(R^2\)</span> does not imply causation, nor does it confirm that the model is free from omitted variable bias or multicollinearity. Therefore, a strong goodness-of-fit measure should be complemented by careful assessment of residual behavior and coefficient significance.</p>
</section><section id="identifying-outliers-and-influential-points" class="level4"><h4 class="anchored" data-anchor-id="identifying-outliers-and-influential-points">Identifying Outliers and Influential Points</h4>
<p>Outliers and influential observations can distort regression estimates, making it crucial to detect and address them appropriately. One way to identify extreme residuals is through residual plots, where large deviations from zero may indicate problematic data points.</p>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">ols_model</span><span class="op">)</span>, main <span class="op">=</span> <span class="st">"Residual Plot"</span>, ylab <span class="op">=</span> <span class="st">"Residuals"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span>h <span class="op">=</span> <span class="fl">0</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03-ols_files/figure-html/residual-plots-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Another important diagnostic tool is Cook’s Distance, which measures the influence of each observation on the regression results. Data points with Cook’s Distance values greater than 0.5 may significantly impact model estimates.</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cook_values</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/influence.measures.html">cooks.distance</a></span><span class="op">(</span><span class="va">ols_model</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">cook_values</span>, type <span class="op">=</span> <span class="st">"h"</span>, main <span class="op">=</span> <span class="st">"Cook's Distance"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03-ols_files/figure-html/cooks-distance-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>If influential points are identified, the next steps involve investigating data quality, testing robust regression techniques, or applying Winsorization, which involves replacing extreme values with more moderate ones to reduce their impact.</p>
</section></section></section><section id="results" class="level2" data-number="3.10"><h2 data-number="3.10" class="anchored" data-anchor-id="results">
<span class="header-section-number">3.10</span> Results</h2>
<p>After validating the goodness of fit, we now assess how well the model performs in both predictive analysis and inferential analysis. This step involves using the trained model to generate predictions on unseen data and evaluating how well it generalizes beyond the training set. Additionally, we analyze the estimated regression coefficients to draw meaningful conclusions about student financial behaviors.</p>
<section id="predictive-analysis" class="level3" data-number="3.10.1"><h3 data-number="3.10.1" class="anchored" data-anchor-id="predictive-analysis">
<span class="header-section-number">3.10.1</span> Predictive Analysis</h3>
<p>A key objective of regression modeling is to generate reliable predictions. To assess how well our model generalizes, we apply it to the test dataset—a portion of the original data that was not used for model training. If the model’s predictions align closely with actual outcomes, we can conclude that it has strong predictive power.</p>
<p>In R, we use the predict() function to apply the trained OLS model to the test dataset:</p>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Generate predictions on the test set</span></span>
<span><span class="va">y_pred</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">ols_model</span>, newdata<span class="op">=</span><span class="va">test_data</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once predictions are generated, we evaluate their accuracy using common regression error metrics.</p>
<section id="performance-metrics" class="level4"><h4 class="anchored" data-anchor-id="performance-metrics">Performance Metrics</h4>
<p>Model accuracy is assessed using four standard error metrics:</p>
<ol type="1">
<li>
<strong>Mean Absolute Error (MAE)</strong> measures the average absolute differences between predicted and actual values. A lower MAE indicates better model accuracy.</li>
<li>
<strong>Mean Squared Error (MSE)</strong> calculates the average squared differences between predicted and actual values, penalizing larger errors more heavily.</li>
<li>
<strong>Root Mean Squared Error (RMSE)</strong> is the square root of MSE, making it easier to interpret since it retains the same units as the dependent variable (Net_Money).</li>
<li>
<strong>R-squared (<span class="math inline">\(R^2\)</span>)</strong> quantifies the proportion of variance in Net_Money explained by the model. A higher <span class="math inline">\(R^2\)</span> value indicates better model performance.</li>
</ol>
<p>These metrics can be computed as follows:</p>
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Extract response variable from test data</span></span>
<span><span class="va">y_test</span> <span class="op">&lt;-</span> <span class="va">test_data</span><span class="op">$</span><span class="va">Net_Money</span></span>
<span></span>
<span><span class="co"># Calculate metrics in R</span></span>
<span><span class="va">mae</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">y_test</span> <span class="op">-</span> <span class="va">y_pred</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">mse</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="op">(</span><span class="va">y_test</span> <span class="op">-</span> <span class="va">y_pred</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span></span>
<span><span class="va">rmse</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">mse</span><span class="op">)</span></span>
<span><span class="va">r2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">ols_model</span><span class="op">)</span><span class="op">$</span><span class="va">r.squared</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sprintf.html">sprintf</a></span><span class="op">(</span><span class="st">"MAE: %.2f, MSE: %.2f, RMSE: %.2f, R-squared: %.2f"</span>, <span class="va">mae</span>, <span class="va">mse</span>, <span class="va">rmse</span>, <span class="va">r2</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>MAE: 183.76, MSE: 54660.22, RMSE: 233.80, R-squared: 0.90</code></pre>
</div>
</div>
<p>If the RMSE is significantly larger than MAE, it suggests that the model is highly sensitive to large prediction errors, meaning that certain extreme values are having a disproportionate impact on the model’s performance. If the R-squared value is low, it may indicate that important predictors are missing from the model or that the relationship between predictors and Net_Money is more complex than a linear relationship can capture.</p>
</section></section><section id="inferential-analysis" class="level3" data-number="3.10.2"><h3 data-number="3.10.2" class="anchored" data-anchor-id="inferential-analysis">
<span class="header-section-number">3.10.2</span> Inferential Analysis</h3>
<p>Beyond prediction, OLS regression allows us to interpret the estimated coefficients to uncover patterns in students’ financial behaviors. Each coefficient represents the expected change in Net_Money for a one-unit increase in the corresponding predictor, assuming all other variables remain constant.</p>
<section id="insights-from-regression-coefficients" class="level4"><h4 class="anchored" data-anchor-id="insights-from-regression-coefficients">Insights from Regression Coefficients</h4>
<p>Here are a few insights that we can extract from the regression model result:</p>
<ul>
<li>The intercept (-595.37) represents the estimated financial balance for a baseline student (someone with Has_Job = 0, Financially_Dependent = 0, Year_of_Study = 0, etc.). Since a zero value for Year_of_Study is not meaningful in our context, the intercept itself has limited interpretability but serves as the starting point for estimating Net_Money based on predictor values.</li>
<li>Financial Dependency (Financially_Dependent) has a strong negative effect (-499.36, p &lt; 2e-16), meaning that students who rely financially on others (e.g., parents, guardians) tend to have significantly lower Net_Money. This could be due to a lack of independent income sources or higher expenses associated with dependence on external financial support.</li>
<li>Social Spending Habits (Goes_Out_Spends_Money) also have a negative impact (-54.60, p &lt; 2e-16), meaning that students who frequently go out and spend money experience a decline in Net_Money. This result aligns with expectations, as higher discretionary spending directly reduces available financial balance.</li>
<li>Cooking at Home (Cooks_at_Home) has a negative effect (-96.31, p = 1.83e-09), which might seem counterintuitive at first. One possible explanation is that students who cook at home may already have lower budgets, leading them to adopt cost-saving habits, rather than the habit itself directly causing financial decline.</li>
<li>Overall, the model explains 90.18% of the variance in Net_Money (<span class="math inline">\(R^2\)</span> = 0.9018, Adjusted <span class="math inline">\(R^2\)</span> = 0.9006), suggesting a strong predictive capability. The F-statistic (722.1, p &lt; 2.2e-16) confirms that the model as a whole is statistically significant.</li>
</ul>
<p>These findings provide a comprehensive view of student financial behaviors, reinforcing expected relationships (such as the role of allowances and earnings) while also highlighting unexpected trends (such as the negative effect of cooking at home). The next step is to integrate these results into a cohesive narrative, translating statistical insights into actionable recommendations.</p>
</section></section></section><section id="storytelling" class="level2" data-number="3.11"><h2 data-number="3.11" class="anchored" data-anchor-id="storytelling">
<span class="header-section-number">3.11</span> Storytelling</h2>
<p>The final step in our data science workflow is storytelling, where we translate our analytical findings into actionable insights. This stage ensures that our results are clearly understood by both technical and non-technical audiences. Effective storytelling involves summarizing insights, using visuals for clarity, and making data-driven recommendations.</p>
<div class="Warning">
<div class="Warning-header">
<p>Fun fact!</p>
</div>
<div class="Warning-container">
<p><strong>Zestylicious!</strong> That mouth-puckering, lemon-squirted, totally tangy kick!</p>
</div>
</div>
<div id="fig-ols-regression" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-ols-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"></figure><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Regression 
  Analysis)
    Continuous &lt;br/&gt;Outcome Y
      {{Unbounded &lt;br/&gt;Outcome Y}}
        )Chapter 3: &lt;br/&gt;Ordinary &lt;br/&gt;Least Squares &lt;br/&gt;Regression(
          (Normal &lt;br/&gt;Outcome Y)
    Discrete &lt;br/&gt;Outcome Y
</pre>
</div>
<p></p>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-ols-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.2
</figcaption></figure>
</div>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/alexrod61\.github\.io\/regression-cookbook\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
          // default icon
          link.classList.add("external");
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><script src="https://giscus.app/client.js" data-repo="alexrod61/regression-cookbook" data-repo-id="R_kgDOMSJoUA" data-category="General" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><input type="hidden" id="giscus-base-theme" value="light"><input type="hidden" id="giscus-alt-theme" value="dark"><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../book/continuous-zone.html" class="pagination-link" aria-label="Continuous Cuisine">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Continuous Cuisine</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../book/04-gamma.html" class="pagination-link" aria-label="Smoketastic Gamma Regression">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Smoketastic Gamma Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2025; G. Alexi Rodríguez-Arelis, Andy Tai, and Ben Chen</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/alexrod61/regression-cookbook/edit/main/book/03-ols.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/alexrod61/regression-cookbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li><li><a href="https://github.com/alexrod61/regression-cookbook/blob/main/book/03-ols.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>