<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.53">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>5&nbsp; Beta Regression – The Regression Cookbook (in development)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../book/06-parametric-survival.html" rel="next">
<link href="../book/04-gamma.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><style>html{ scroll-behavior: smooth; }</style>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-7PRVEBE1EF"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  
  // Default to 'denied' if you want to be GDPR compliant
  gtag('consent', 'default', {
    'analytics_storage': 'denied'
  });

  gtag('js', new Date());
  gtag('config', 'G-7PRVEBE1EF'); //FILL THIS IN, AND ABOVE G-XXXXXXXXX 

  // Function to trigger when user accepts
  function acceptCookies() {
    gtag('consent', 'update', {
      'analytics_storage': 'granted'
    });
    // Hide your pop-up logic here
    document.getElementById('cookie-popup').style.display = 'none';
    localStorage.setItem('cookieConsent', 'granted');
  }
</script><script src="../site_libs/quarto-diagram/mermaid.min.js"></script><script src="../site_libs/quarto-diagram/mermaid-init.js"></script><link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="../custom.css">
</head>
<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">The Regression Cookbook (in development)</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
    <a href="https://github.com/alexrod61/regression-cookbook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://www.facebook.com/sharer/sharer.php?u=%7Curl%7C">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://www.linkedin.com/sharing/share-offsite/?url=%7Curl%7C">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../book/continuous-zone.html">Continuous Cuisine</a></li><li class="breadcrumb-item"><a href="../book/05-beta.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Beta Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../img/cookbook.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none"></a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/meet-the-team.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Meet the Team</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/privacy-policy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Website Privacy Policy</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/audience-scope.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Audience and Scope</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting Ready for Regression Cooking!</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/02-stats-review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Basic Cuisine: A Review on Probability and Frequentist Statistical Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../book/continuous-zone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Continuous Cuisine</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/03-ols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Ordinary Least-squares Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/04-gamma.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Gamma Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/05-beta.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Beta Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/06-parametric-survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Parametric Survival Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/07-semiparametric-survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Semiparametric Survival Regression</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../book/discrete-zone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Discrete Cuisine</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/08-binary-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Binary Logistic Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/09-binomial-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Binomial Logistic Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/10-classical-poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Classical Poisson Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/11-negative-binomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Negative Binomial Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/12-zero-inflated-poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Zero-Inflated Poisson Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/13-generalized-poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Generalized Poisson Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/14-multinomial-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Multinomial Logistic Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/15-ordinal-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Ordinal Logistic Regression</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/A-dictionary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">ML-Stats Dictionary</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/B-greek-alphabet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Greek Alphabet</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/C-distributional-mind-map.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Distributional Mind Map</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../book/D-regression-mind-map.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Regression Mind Map</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">The recipe</h2>
   
  <ul>
<li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">5.1</span> Introduction</a></li>
  <li><a href="#what-is-beta-regression" id="toc-what-is-beta-regression" class="nav-link" data-scroll-target="#what-is-beta-regression"><span class="header-section-number">5.2</span> What is Beta Regression</a></li>
  <li><a href="#the-beta-distribution" id="toc-the-beta-distribution" class="nav-link" data-scroll-target="#the-beta-distribution"><span class="header-section-number">5.3</span> The Beta Distribution</a></li>
  <li><a href="#linking-the-average-proportion-to-predictors" id="toc-linking-the-average-proportion-to-predictors" class="nav-link" data-scroll-target="#linking-the-average-proportion-to-predictors"><span class="header-section-number">5.4</span> Linking the Average Proportion to Predictors</a></li>
  <li><a href="#the-beta-regression-model" id="toc-the-beta-regression-model" class="nav-link" data-scroll-target="#the-beta-regression-model"><span class="header-section-number">5.5</span> The Beta Regression Model</a></li>
  <li>
<a href="#case-study-modeling-student-academic-performance" id="toc-case-study-modeling-student-academic-performance" class="nav-link" data-scroll-target="#case-study-modeling-student-academic-performance"><span class="header-section-number">5.6</span> Case Study: Modeling Student Academic Performance</a>
  <ul>
<li><a href="#the-dataset" id="toc-the-dataset" class="nav-link" data-scroll-target="#the-dataset"><span class="header-section-number">5.6.1</span> The Dataset</a></li>
  <li><a href="#the-problem-were-trying-to-solve" id="toc-the-problem-were-trying-to-solve" class="nav-link" data-scroll-target="#the-problem-were-trying-to-solve"><span class="header-section-number">5.6.2</span> The Problem We’re Trying to Solve</a></li>
  </ul>
</li>
  <li><a href="#study-design" id="toc-study-design" class="nav-link" data-scroll-target="#study-design"><span class="header-section-number">5.7</span> Study Design</a></li>
  <li>
<a href="#data-collection-and-wrangling" id="toc-data-collection-and-wrangling" class="nav-link" data-scroll-target="#data-collection-and-wrangling"><span class="header-section-number">5.8</span> Data Collection and Wrangling</a>
  <ul>
<li><a href="#data-collection" id="toc-data-collection" class="nav-link" data-scroll-target="#data-collection"><span class="header-section-number">5.8.1</span> Data Collection</a></li>
  <li>
<a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling"><span class="header-section-number">5.8.2</span> Data Wrangling</a>
  <ul class="collapse">
<li><a href="#preparing-and-validating-the-response-variable" id="toc-preparing-and-validating-the-response-variable" class="nav-link" data-scroll-target="#preparing-and-validating-the-response-variable">1. Preparing and Validating the Response Variable</a></li>
  <li><a href="#checking-for-boundary-values" id="toc-checking-for-boundary-values" class="nav-link" data-scroll-target="#checking-for-boundary-values">2. Checking for Boundary Values</a></li>
  <li><a href="#encoding-categorical-variables" id="toc-encoding-categorical-variables" class="nav-link" data-scroll-target="#encoding-categorical-variables">3. Encoding Categorical Variables</a></li>
  <li><a href="#checking-for-missing-values-and-inconsistencies" id="toc-checking-for-missing-values-and-inconsistencies" class="nav-link" data-scroll-target="#checking-for-missing-values-and-inconsistencies">4. Checking for Missing Values and Inconsistencies</a></li>
  </ul>
</li>
  </ul>
</li>
  <li>
<a href="#exploratory-data-analysis-eda" id="toc-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda"><span class="header-section-number">5.9</span> Exploratory Data Analysis (EDA)</a>
  <ul>
<li><a href="#distribution-of-the-response-variable" id="toc-distribution-of-the-response-variable" class="nav-link" data-scroll-target="#distribution-of-the-response-variable"><span class="header-section-number">5.9.1</span> Distribution of the Response Variable</a></li>
  <li>
<a href="#distribution-of-predictor-variables" id="toc-distribution-of-predictor-variables" class="nav-link" data-scroll-target="#distribution-of-predictor-variables"><span class="header-section-number">5.9.2</span> Distribution of Predictor Variables</a>
  <ul class="collapse">
<li><a href="#continuous-predictors" id="toc-continuous-predictors" class="nav-link" data-scroll-target="#continuous-predictors">Continuous Predictors</a></li>
  <li><a href="#categorical-predictors" id="toc-categorical-predictors" class="nav-link" data-scroll-target="#categorical-predictors">Categorical Predictors</a></li>
  </ul>
</li>
  <li>
<a href="#relationships-between-predictors-and-the-response" id="toc-relationships-between-predictors-and-the-response" class="nav-link" data-scroll-target="#relationships-between-predictors-and-the-response"><span class="header-section-number">5.9.3</span> Relationships Between Predictors and the Response</a>
  <ul class="collapse">
<li><a href="#continuous-predictors-and-the-response" id="toc-continuous-predictors-and-the-response" class="nav-link" data-scroll-target="#continuous-predictors-and-the-response">Continuous Predictors and the Response</a></li>
  <li><a href="#categorical-predictors-and-the-response" id="toc-categorical-predictors-and-the-response" class="nav-link" data-scroll-target="#categorical-predictors-and-the-response">Categorical Predictors and the Response</a></li>
  </ul>
</li>
  </ul>
</li>
  <li>
<a href="#data-modeling" id="toc-data-modeling" class="nav-link" data-scroll-target="#data-modeling"><span class="header-section-number">5.10</span> Data Modeling</a>
  <ul>
<li><a href="#choosing-a-suitable-regression-model" id="toc-choosing-a-suitable-regression-model" class="nav-link" data-scroll-target="#choosing-a-suitable-regression-model"><span class="header-section-number">5.10.1</span> Choosing a Suitable Regression Model</a></li>
  <li><a href="#defining-modeling-parameters" id="toc-defining-modeling-parameters" class="nav-link" data-scroll-target="#defining-modeling-parameters"><span class="header-section-number">5.10.2</span> Defining Modeling Parameters</a></li>
  <li><a href="#setting-up-the-modeling-equation" id="toc-setting-up-the-modeling-equation" class="nav-link" data-scroll-target="#setting-up-the-modeling-equation"><span class="header-section-number">5.10.3</span> Setting Up the Modeling Equation</a></li>
  </ul>
</li>
  <li>
<a href="#estimation" id="toc-estimation" class="nav-link" data-scroll-target="#estimation"><span class="header-section-number">5.11</span> Estimation</a>
  <ul>
<li><a href="#fitting-the-model" id="toc-fitting-the-model" class="nav-link" data-scroll-target="#fitting-the-model"><span class="header-section-number">5.11.1</span> Fitting the Model</a></li>
  <li><a href="#interpreting-the-coefficients" id="toc-interpreting-the-coefficients" class="nav-link" data-scroll-target="#interpreting-the-coefficients"><span class="header-section-number">5.11.2</span> Interpreting the Coefficients</a></li>
  </ul>
</li>
  <li>
<a href="#goodness-of-fit" id="toc-goodness-of-fit" class="nav-link" data-scroll-target="#goodness-of-fit"><span class="header-section-number">5.12</span> Goodness of Fit</a>
  <ul>
<li><a href="#log-likelihood-aic-and-bic" id="toc-log-likelihood-aic-and-bic" class="nav-link" data-scroll-target="#log-likelihood-aic-and-bic"><span class="header-section-number">5.12.1</span> Log-likelihood, AIC, and BIC</a></li>
  <li><a href="#pseudo-r2" id="toc-pseudo-r2" class="nav-link" data-scroll-target="#pseudo-r2"><span class="header-section-number">5.12.2</span> Pseudo-<span class="math inline">\(R^2\)</span></a></li>
  <li><a href="#precision-parameter" id="toc-precision-parameter" class="nav-link" data-scroll-target="#precision-parameter"><span class="header-section-number">5.12.3</span> Precision Parameter</a></li>
  </ul>
</li>
  <li>
<a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">5.13</span> Results</a>
  <ul>
<li><a href="#predictors-associated-with-final-grades" id="toc-predictors-associated-with-final-grades" class="nav-link" data-scroll-target="#predictors-associated-with-final-grades"><span class="header-section-number">5.13.1</span> Predictors Associated with Final Grades</a></li>
  <li><a href="#variables-without-strong-evidence-of-association" id="toc-variables-without-strong-evidence-of-association" class="nav-link" data-scroll-target="#variables-without-strong-evidence-of-association"><span class="header-section-number">5.13.2</span> Variables Without Strong Evidence of Association</a></li>
  </ul>
</li>
  <li>
<a href="#storytelling" id="toc-storytelling" class="nav-link" data-scroll-target="#storytelling"><span class="header-section-number">5.14</span> Storytelling</a>
  <ul>
<li><a href="#key-insights-from-the-model" id="toc-key-insights-from-the-model" class="nav-link" data-scroll-target="#key-insights-from-the-model"><span class="header-section-number">5.14.1</span> Key Insights From the Model</a></li>
  </ul>
</li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">5.15</span> Conclusion</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/alexrod61/regression-cookbook/edit/main/book/05-beta.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/alexrod61/regression-cookbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li><li><a href="https://github.com/alexrod61/regression-cookbook/blob/main/book/05-beta.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../book/continuous-zone.html">Continuous Cuisine</a></li><li class="breadcrumb-item"><a href="../book/05-beta.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Beta Regression</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-beta" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Beta Regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><!-- Google tag (gtag.js) --><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-7PRVEBE1EF"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-7PRVEBE1EF');
</script><div class="LO">
<div class="LO-header">
<p>Learning Objectives</p>
</div>
<div class="LO-container">
<p>By the end of this chapter, you will be able to:</p>
</div>
</div>
<section id="introduction" class="level2" data-number="5.1"><h2 data-number="5.1" class="anchored" data-anchor-id="introduction">
<span class="header-section-number">5.1</span> Introduction</h2>
<p>Many real world problems involve modeling proportions. A common example is a website conversion rate, where each page is associated with a value between zero and one that represents the fraction of visitors who complete a purchase. Some pages convert only a small share of visitors, while others perform much better. Although these values are numerical and continuous, they are also restricted to a fixed range. A suitable model must respect these limits and reflect the fact that variability often changes depending on the average level of the proportion.</p>
<p>Traditional linear regression is not well suited for this type of data. It can produce predictions outside the valid range and assumes that variability is constant across all observations. Problems like this call for a regression approach that is designed specifically for proportion outcomes. This is exactly where Beta regression comes to shine.</p>
</section><section id="what-is-beta-regression" class="level2" data-number="5.2"><h2 data-number="5.2" class="anchored" data-anchor-id="what-is-beta-regression">
<span class="header-section-number">5.2</span> What is Beta Regression</h2>
<p>Beta regression is a regression model designed for situations where the response variable is a proportion that takes values on the open interval between zero and one. Instead of modeling the response directly as a straight line, Beta regression assumes that the response follows a Beta distribution. This distribution is defined only on the zero to one interval and is flexible enough to represent many different shapes.</p>
<p>Because of this flexibility, Beta regression is well suited for data such as conversion rates, completion rates, coverage percentages, or any outcome that represents a fraction of a whole. The model naturally respects the bounds of the data and avoids unrealistic predictions.</p>
</section><section id="the-beta-distribution" class="level2" data-number="5.3"><h2 data-number="5.3" class="anchored" data-anchor-id="the-beta-distribution">
<span class="header-section-number">5.3</span> The Beta Distribution</h2>
<p>The Beta distribution is a continuous probability distribution defined on the interval between zero and one. A key feature of this distribution is its flexibility. Depending on its parameter values, it can take many shapes, including symmetric, left skewed, or right skewed forms, as well as distributions that place more mass near the boundaries.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>(0.0, 1.0)</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-beta_files/figure-html/beta-distribution-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p>The figure above shows several examples of Beta distributions with different parameter choices. Although the shapes vary widely, all distributions remain within the zero to one range, making the Beta distribution a natural choice for modeling proportion data.</p>
<p>The shape of a Beta distribution is controlled by two parameters, commonly called alpha and beta. When alpha is larger than beta, values tend to be closer to one. When beta is larger than alpha, values tend to be closer to zero. When the two parameters are similar, values cluster around the middle of the range. Together, alpha and beta also influence how spread out the data are, with smaller values producing more variability and larger values leading to tighter concentration around the average.</p>
<p>In practice, working directly with alpha and beta is not very convenient for regression modeling. These parameters describe the shape of the distribution, but they do not directly tell us how the average proportion changes when a predictor changes. To address this, Beta regression rewrites the distribution in terms of quantities that are easier to interpret, such as the <strong>average proportion</strong> and <strong>how tightly the data cluster around that average</strong>. This reexpression allows the model to relate the average proportion to predictor variables while still ensuring that all fitted values remain between zero and one. We explore this idea in more detail in the next section.</p>
</section><section id="linking-the-average-proportion-to-predictors" class="level2" data-number="5.4"><h2 data-number="5.4" class="anchored" data-anchor-id="linking-the-average-proportion-to-predictors">
<span class="header-section-number">5.4</span> Linking the Average Proportion to Predictors</h2>
<p>In the <a href="book/05-beta.qmd">Gamma regression chapter</a>, we introduced generalized linear models as a way to extend linear regression to response variables that do not follow a normal distribution. Beta regression follows the same framework and is another example of a generalized linear model, designed specifically for proportion data.</p>
<p>As with other generalized linear models, Beta regression does not model the response directly. Instead, it models the average of the response through a transformation that allows predictor variables to be related to the outcome using a familiar linear structure. This approach is especially important for proportion data, since the average must always remain between zero and one.</p>
<div class="Tip">
<div class="Tip-header">
<p>A Quick Refresh on GLMs</p>
</div>
<div class="Tip-container">
<p>Generalized linear models are built from three components.</p>
<ul>
<li>
<strong>Random component</strong> describes the distribution of the response variable<br>
</li>
<li>
<strong>Systematic component</strong> combines predictor variables through a linear predictor<br>
</li>
<li>
<strong>Link function</strong> connects the linear predictor to the average of the response</li>
</ul>
<p>These three pieces work together to extend linear regression to a wide range of response types.</p>
</div>
</div>
<p>For Beta regression, the three components of GLM take the following form.</p>
<ul>
<li><p><strong>Random component</strong>: The response variable is assumed to follow a Beta distribution. This choice reflects the fact that the outcome is continuous and bounded between zero and one.</p></li>
<li><p><strong>Systematic component</strong>: Predictor variables are combined through a linear predictor. This part of the model describes how changes in the predictors are associated with changes in the average proportion.</p></li>
<li><p><strong>Link function</strong>: The link function connects the linear predictor to the average proportion. Its role is to ensure that the modeled average remains between zero and one. A commonly used choice is the logit function, which maps proportions to the real line and is also used in logistic regression.</p></li>
</ul></section><section id="the-beta-regression-model" class="level2" data-number="5.5"><h2 data-number="5.5" class="anchored" data-anchor-id="the-beta-regression-model">
<span class="header-section-number">5.5</span> The Beta Regression Model</h2>
<p>Putting the three components together, the Beta regression model can be written in mathematical form.</p>
<p>For each observation <span class="math inline">\(i\)</span>, the response variable is assumed to follow a Beta distribution,</p>
<p><span class="math display">\[
Y_i \sim \text{Beta}(\mu_i \phi,\ (1 - \mu_i)\phi)
\]</span> Here, <span class="math inline">\(\mu_i\)</span> represents the average proportion for observation <span class="math inline">\(i\)</span>, and <span class="math inline">\(\phi\)</span> is a parameter that controls how tightly the data cluster around that average. Larger values of <span class="math inline">\(\phi\)</span> correspond to less variability, while smaller values allow for more spread.</p>
<p>The average proportion <span class="math inline">\(\mu_i\)</span> is then linked to the predictors through a linear predictor using a link function. With the logit link, this takes the form</p>
<p><span class="math display">\[
\begin{aligned}
\text{logit}(\mu_i) &amp;= \log\left(\frac{\mu_i}{1-\mu_i}\right) \\
                    &amp;= \eta_i \\
                    &amp;= \beta_0 + \beta_1 x_{i1} + \cdots + \beta_p x_{ip}
\end{aligned}
\]</span></p>
<p>Here, <span class="math inline">\(\beta_0\)</span> is the intercept and represents the baseline value of the transformed average proportion when all predictors are set to zero. The remaining coefficients <span class="math inline">\(\beta_1, ..., \beta_p\)</span> describe the association between each predictor and the average proportion on the logit scale, holding all other predictors constant. A positive coefficient indicates that larger values of the predictor are associated with a higher average proportion, while a negative coefficient indicates the opposite.</p>
<p>This formulation follows the same generalized linear model structure introduced in the <a href="book/05-beta.qmd">Gamma regression chapter</a>. The random component specifies the distribution of the response, the systematic component combines predictors through a linear predictor, and the link function connects the linear predictor to the average of the response. Together, these components allow Beta regression to model proportion data in a flexible and interpretable way, while ensuring that fitted values always remain between zero and one.</p>
</section><section id="case-study-modeling-student-academic-performance" class="level2" data-number="5.6"><h2 data-number="5.6" class="anchored" data-anchor-id="case-study-modeling-student-academic-performance">
<span class="header-section-number">5.6</span> Case Study: Modeling Student Academic Performance</h2>
<p>To demonstrate Beta regression in action, we will walk through a case study using a toy dataset that captures student academic performance. In this case study, our response variable is a final course grade, expressed as a percentage.</p>
<p>Because grades represent proportions that lie between zero and one hundred percent, they are naturally suited for Beta regression after being rescaled to the unit interval. Our goal is to understand how different aspects of a student’s academic life and daily habits are associated with their overall performance.</p>
<p>We will approach this case study using the data science workflow introduced in the <a href="book/01-intro.qmd">first chapter</a>. This ensures a structured approach to framing the problem, exploring the data, selecting an appropriate model, and interpreting the results.</p>
<section id="the-dataset" class="level3" data-number="5.6.1"><h3 data-number="5.6.1" class="anchored" data-anchor-id="the-dataset">
<span class="header-section-number">5.6.1</span> The Dataset</h3>
<p>The toy dataset used in this case study represents a group of university students. Each row corresponds to a single student and includes information about study habits, lifestyle factors, and academic support. Below is a summary of the variables included in the dataset.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 34%">
<col style="width: 65%">
</colgroup>
<thead><tr class="header">
<th><strong>Variable Name</strong></th>
<th><strong>Description</strong></th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Final Grade (%)</strong></td>
<td>Final course grade expressed as a percentage.</td>
</tr>
<tr class="even">
<td><strong>Café Location</strong></td>
<td>Primary café or study location used by the student.</td>
</tr>
<tr class="odd">
<td><strong>Study Time</strong></td>
<td>Self-reported amount of time spent studying.</td>
</tr>
<tr class="even">
<td><strong>Year in School</strong></td>
<td>Academic year of the student (e.g., 1st Year, 4th Year).</td>
</tr>
<tr class="odd">
<td><strong>Hobbies</strong></td>
<td>Primary hobby outside of school.</td>
</tr>
<tr class="even">
<td><strong>Primary Sport</strong></td>
<td>Main sport played by the student, if any.</td>
</tr>
<tr class="odd">
<td><strong>Living Arrangement</strong></td>
<td>Living situation (e.g., alone, with friends).</td>
</tr>
<tr class="even">
<td><strong>Part-time Work Hours</strong></td>
<td>Number of hours worked per week in a part-time job.</td>
</tr>
<tr class="odd">
<td><strong>Study Group Participation</strong></td>
<td>Whether the student participates in a study group.</td>
</tr>
<tr class="even">
<td><strong>Hours of Sleep per Night</strong></td>
<td>Average number of hours of sleep per night.</td>
</tr>
<tr class="odd">
<td><strong>Has a Tutor</strong></td>
<td>Whether the student receives tutoring support.</td>
</tr>
</tbody>
</table>
<p>Here is a snapshot of the dataset:</p>
<div style="overflow-x: auto;">
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 7%">
</colgroup>
<thead><tr class="header">
<th><strong>Final Grade (%)</strong></th>
<th><strong>Café Location</strong></th>
<th><strong>Study Time</strong></th>
<th><strong>Year in School</strong></th>
<th><strong>Hobbies</strong></th>
<th><strong>Primary Sport</strong></th>
<th><strong>Living Arrangement</strong></th>
<th><strong>Part-time Work Hours</strong></th>
<th><strong>Study Group Participation</strong></th>
<th><strong>Hours of Sleep per Night</strong></th>
<th><strong>Has a Tutor</strong></th>
</tr></thead>
<tbody>
<tr class="odd">
<td>96.99</td>
<td>Koerner’s Pub</td>
<td>5+ hours</td>
<td>1st Year</td>
<td>Sports</td>
<td>Soccer</td>
<td>With Friends</td>
<td>15</td>
<td>Yes</td>
<td>5.4</td>
<td>Yes</td>
</tr>
<tr class="even">
<td>94.62</td>
<td>Bean Around the World</td>
<td>5+ hours</td>
<td>4th Year</td>
<td>Gaming</td>
<td>Soccer</td>
<td>Alone</td>
<td>7</td>
<td>Yes</td>
<td>5.4</td>
<td>No</td>
</tr>
<tr class="odd">
<td>90.30</td>
<td>The Loop Café</td>
<td>5+ hours</td>
<td>2nd Year</td>
<td>Sports</td>
<td>None</td>
<td>Alone</td>
<td>6</td>
<td>No</td>
<td>5.6</td>
<td>Yes</td>
</tr>
<tr class="even">
<td>86.77</td>
<td>Bean Around the World</td>
<td>5+ hours</td>
<td>1st Year</td>
<td>Reading</td>
<td>Basketball</td>
<td>Alone</td>
<td>10</td>
<td>No</td>
<td>7.8</td>
<td>No</td>
</tr>
</tbody>
</table>
</div>
<p>This dataset allows us to examine how academic behaviors and lifestyle choices are associated with student performance, while respecting the proportional nature of the outcome.</p>
</section><section id="the-problem-were-trying-to-solve" class="level3" data-number="5.6.2"><h3 data-number="5.6.2" class="anchored" data-anchor-id="the-problem-were-trying-to-solve">
<span class="header-section-number">5.6.2</span> The Problem We’re Trying to Solve</h3>
<p>In this case study, our goal is to understand what factors are associated with higher or lower final grades. Since grades are continuous, bounded, and naturally interpreted as proportions, Beta regression is a suitable modeling choice.</p>
<p>The key question we aim to answer is:</p>
<blockquote class="blockquote">
<p><strong>Which academic and lifestyle factors are associated with differences in students’ final grades?</strong></p>
</blockquote>
<p>Rather than focusing only on prediction, we are interested in understanding how study habits, support systems, and daily routines relate to academic outcomes. In the next section, we clarify our study design and begin applying the data science workflow to this problem.</p>
</section></section><section id="study-design" class="level2" data-number="5.7"><h2 data-number="5.7" class="anchored" data-anchor-id="study-design">
<span class="header-section-number">5.7</span> Study Design</h2>
<p>Just like we discussed above, our goal is to understand how academic and lifestyle factors are associated with students’ final grades.</p>
<p>At this stage, we focus on clearly defining the type of question we are asking and how it fits into the data science workflow, rather than introducing new modeling details.</p>
<p>In particular, this is an inferential task. We are interested in describing and interpreting relationships between variables, rather than building a model purely for prediction. A predictive approach would be possible, but our primary objective here is to gain insight into how different factors relate to student performance.</p>
</section><section id="data-collection-and-wrangling" class="level2" data-number="5.8"><h2 data-number="5.8" class="anchored" data-anchor-id="data-collection-and-wrangling">
<span class="header-section-number">5.8</span> Data Collection and Wrangling</h2>
<p>With our statistical question clearly defined, the next step is to ensure that the data is suitable for analysis. Although the dataset is already provided, it is still useful to reflect briefly on how this type of data might have been collected. Doing so helps clarify what the data represents and highlights potential limitations before moving on to preparation and modeling.</p>
<section id="data-collection" class="level3" data-number="5.8.1"><h3 data-number="5.8.1" class="anchored" data-anchor-id="data-collection">
<span class="header-section-number">5.8.1</span> Data Collection</h3>
<p>For a study examining student academic performance, data like this could reasonably be collected through several common sources:</p>
<ul>
<li><p><strong>Academic Records</strong>: Final grades are typically recorded by instructors or academic departments at the end of a course. These records provide a standardized and reliable measure of student performance.</p></li>
<li><p><strong>Student Surveys</strong>: Information on study habits, sleep, part-time work, tutoring, and study group participation is often collected through self-reported surveys. While this data provides valuable context, it may be subject to reporting bias or measurement error.</p></li>
<li><p><strong>Institutional Data Systems</strong>: Universities often combine academic records with student support and enrollment information, such as year in school or participation in academic programs.</p></li>
</ul>
<p>Each of these sources comes with trade-offs. Academic records are objective but limited to performance outcomes, while survey-based variables may be noisy but offer insight into behaviors and lifestyle factors. Recognizing these limitations helps guide both exploratory analysis and interpretation later on.</p>
</section><section id="data-wrangling" class="level3" data-number="5.8.2"><h3 data-number="5.8.2" class="anchored" data-anchor-id="data-wrangling">
<span class="header-section-number">5.8.2</span> Data Wrangling</h3>
<p>Once the data has been collected, the next step is to prepare it for modeling. Even small, well-structured datasets often require preprocessing before they can be analyzed effectively.</p>
<p>For Beta regression, data wrangling typically involves:</p>
<ul>
<li>Validating that the response variable represents a proportion.</li>
<li>Rescaling the response variable so that it lies strictly between zero and one.</li>
<li>Checking for boundary values such as exact zeros or ones.</li>
<li>Converting categorical variables into numerical formats suitable for modeling.</li>
<li>Inspecting missing values and potential inconsistencies in self-reported data.</li>
</ul>
<p>Based on the data, there can, of course, be other things you may have to do but for now, let’s walk through these steps using our student performance dataset, demonstrating each step in both R and Python.</p>
<section id="preparing-and-validating-the-response-variable" class="level4"><h4 class="anchored" data-anchor-id="preparing-and-validating-the-response-variable">1. Preparing and Validating the Response Variable</h4>
<p>In this case study, the response variable is the final course grade, recorded as a percentage. While this variable is continuous, it is currently measured on a scale from 0 to 100. Since Beta regression models proportions, the response must first be rescaled to lie between zero and one.</p>
<p>Before rescaling, we begin by examining the distribution of final grades to confirm that the values are within a reasonable range.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">data</span><span class="op">$</span><span class="va">`Final Grade (%)`</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  50.30   70.10   79.00   78.63   87.17  100.00 </code></pre>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics for the response variable</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data.columns.tolist())</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data[<span class="st">"Final Grade (%)"</span>].describe())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>The summary confirms that all grades lie between 0 and 100, making them suitable for conversion to proportions. We therefore rescale the response by dividing each value by 100.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">data</span><span class="op">$</span><span class="va">final_grade_prop</span> <span class="op">&lt;-</span> <span class="va">data</span><span class="op">$</span><span class="va">`Final Grade (%)`</span> <span class="op">/</span> <span class="fl">100</span></span>
<span></span>
<span><span class="co"># Drop original percentage column</span></span>
<span><span class="va">data</span><span class="op">$</span><span class="va">`Final Grade (%)`</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">data</span><span class="op">$</span><span class="va">final_grade_prop</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.5030  0.7010  0.7900  0.7863  0.8717  1.0000 </code></pre>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Rescale grades to proportions</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>data[<span class="st">"final_grade_prop"</span>] <span class="op">=</span> data[<span class="st">"Final Grade (%)"</span>] <span class="op">/</span> <span class="dv">100</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop original percentage column</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> data.drop(columns<span class="op">=</span>[<span class="st">"Final Grade (%)"</span>])</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data[<span class="st">"final_grade_prop"</span>].describe())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<div class="Heads-up">
<div class="Heads-up-header">
<p>Heads-up!</p>
</div>
<div class="Heads-up-container">
<p>At this stage, the structure of the response variable already suggests that a proportion-based model, such as Beta regression, will be a good fit. With that in mind, we perform the preprocessing needed for such a model here. In practice, this decision is often informed by exploratory analysis and may be revisited later, but introducing it now helps keep the workflow clear and focused.</p>
</div>
</div>
<p>After rescaling, the response variable now lies on the unit interval. The next step is to check whether any values are exactly zero or one, since standard Beta regression assumes outcomes are strictly between these boundaries.</p>
</section><section id="checking-for-boundary-values" class="level4"><h4 class="anchored" data-anchor-id="checking-for-boundary-values">2. Checking for Boundary Values</h4>
<p>Beta regression requires that the response variable take values strictly between zero and one. We therefore check whether any rescaled grades are exactly equal to zero or one.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">data</span><span class="op">$</span><span class="va">final_grade_prop</span> <span class="op">&lt;=</span> <span class="fl">0</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">data</span><span class="op">$</span><span class="va">final_grade_prop</span> <span class="op">&gt;=</span> <span class="fl">1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for boundary values</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>((data[<span class="st">"final_grade_prop"</span>] <span class="op">&lt;=</span> <span class="dv">0</span>).<span class="bu">sum</span>())</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>((data[<span class="st">"final_grade_prop"</span>] <span class="op">&gt;=</span> <span class="dv">1</span>).<span class="bu">sum</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>Shoot! The checks reveal that there are several observations with values equal to one. While this is not unusual for percentage-based data, it poses a problem for standard Beta regression, which assumes the response lies strictly between zero and one.</p>
<div class="Heads-up">
<div class="Heads-up-header">
<p>Heads-up!</p>
</div>
<div class="Heads-up-container">
<p>When proportion data includes values exactly equal to zero or one, the assumptions of standard Beta regression are violated. This situation is common in practice, especially when proportions are derived from percentages or rounded measurements. There are several principled ways to handle boundary values, each with different trade-offs.</p>
<p>One approach is <strong>boundary adjustment</strong>, where values equal to zero or one are shifted slightly inward by a small amount. This method is simple, preserves the ordering of observations, and allows standard Beta regression to be applied without adding model complexity. It is often appropriate when boundary values arise from rounding or measurement limits rather than representing a fundamentally different process.</p>
<p>A second approach, proposed by Smithson and Verkuilen (2006), <strong>applies a systematic transformation to the response variable</strong>. Instead of only adjusting values at the boundaries, this method gently shifts all observations so that none of them are exactly zero or one.</p>
<p>Intuitively, the transformation treats the observed proportions as slightly uncertain and pulls extreme values a small distance toward the interior of the interval. This avoids hard cutoffs at zero and one while preserving the relative ordering of the data.</p>
<p>Mathematically, the transformation can be written as <span class="math display">\[
x' = \frac{x (N - 1) + s}{N}
\]</span></p>
<p>where <span class="math inline">\(N\)</span> is the sample size and <span class="math inline">\(s\)</span> is a small constant between 0 and 1, often chosen as <span class="math inline">\(s=0.5\)</span>.</p>
<p>One way to think about this adjustment is that it spreads the data evenly across the open interval <span class="math inline">\((0,1)\)</span>, ensuring that no observation lies exactly on the boundaries. From a Bayesian perspective (for the Bayesianists out there), the constant <span class="math inline">\(s\)</span> can be interpreted as introducing a weak prior that prevents extreme values from being taken at face value. In practice, this approach is often viewed as more principled than manually nudging boundary values, though it also adds an extra layer of abstraction.</p>
<p>Another option is to use <strong>zero–one–inflated Beta models</strong>, which explicitly treat boundary values as arising from a separate process. These models are more flexible and appropriate when zeros or ones occur frequently and carry substantive meaning, but they also introduce additional parameters and complexity.</p>
<p>Finally, boundary observations can be <strong>excluded</strong>, though this is generally discouraged unless there is a strong substantive justification, as it removes potentially informative data.</p>
</div>
</div>
<p>In this case study, our goal is to focus on the core ideas of Beta regression and to keep the workflow accessible. Because the number of boundary values is small and likely driven by rounding of high grades, we proceed with a simple boundary adjustment and continue with standard Beta regression.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">epsilon</span> <span class="op">&lt;-</span> <span class="fl">0.001</span></span>
<span><span class="va">data</span><span class="op">$</span><span class="va">final_grade_prop</span><span class="op">[</span><span class="va">data</span><span class="op">$</span><span class="va">final_grade_prop</span> <span class="op">&gt;=</span> <span class="fl">1</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">-</span> <span class="va">epsilon</span></span>
<span><span class="va">data</span><span class="op">$</span><span class="va">final_grade_prop</span><span class="op">[</span><span class="va">data</span><span class="op">$</span><span class="va">final_grade_prop</span> <span class="op">&lt;=</span> <span class="fl">0</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">epsilon</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">data</span><span class="op">$</span><span class="va">final_grade_prop</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.5030  0.7010  0.7900  0.7863  0.8717  0.9990 </code></pre>
</div>
</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>epsilon <span class="op">=</span> <span class="fl">0.001</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>data.loc[data[<span class="st">"final_grade_prop"</span>] <span class="op">&gt;=</span> <span class="dv">1</span>, <span class="st">"final_grade_prop"</span>] <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> epsilon</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>data.loc[data[<span class="st">"final_grade_prop"</span>] <span class="op">&lt;=</span> <span class="dv">0</span>, <span class="st">"final_grade_prop"</span>] <span class="op">=</span> epsilon</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data[<span class="st">"final_grade_prop"</span>].describe())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>After this adjustment, all response values lie strictly between zero and one, making the data suitable for Beta regression.</p>
</section><section id="encoding-categorical-variables" class="level4"><h4 class="anchored" data-anchor-id="encoding-categorical-variables">3. Encoding Categorical Variables</h4>
<p>Several variables in the dataset are categorical, such as café location, year in school, hobbies, living arrangement, study group participation, and tutoring status. Regression models, including Beta regression, require numerical inputs, so these variables must be converted into a suitable numerical representation. We use one-hot encoding for this purpose.</p>
<p>As a quick refresh, one-hot encoding represents each category as a binary indicator variable. For a given categorical feature, each level becomes its own column that takes the value 1 when an observation belongs to that category and 0 otherwise. To avoid redundancy, one category is typically omitted and treated as the reference level.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Convert categorical variables to factors</span></span>
<span><span class="va">categorical_vars</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  <span class="st">"Café Location"</span>,</span>
<span>  <span class="st">"Study Time"</span>,</span>
<span>  <span class="st">"Year in School"</span>,</span>
<span>  <span class="st">"Hobbies"</span>,</span>
<span>  <span class="st">"Primary Sport"</span>,</span>
<span>  <span class="st">"Living Arrangement"</span>,</span>
<span>  <span class="st">"Study Group Participation"</span>,</span>
<span>  <span class="st">"Has a Tutor"</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">data</span><span class="op">[</span><span class="va">categorical_vars</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">data</span><span class="op">[</span><span class="va">categorical_vars</span><span class="op">]</span>, <span class="va">as.factor</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Create design matrix with dummy variables</span></span>
<span><span class="va">design_matrix</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/model.matrix.html">model.matrix</a></span><span class="op">(</span></span>
<span>  <span class="va">final_grade_prop</span> <span class="op">~</span> <span class="va">.</span>,</span>
<span>  data <span class="op">=</span> <span class="va">data</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">design_matrix</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept) `Café Location`Bean Around the World `Café Location`Ike's Café
1           1                                    0                         0
2           1                                    1                         0
3           1                                    0                         0
4           1                                    1                         0
5           1                                    1                         0
6           1                                    0                         1
  `Café Location`Koerner's Pub `Café Location`The Loop Café
1                            1                            0
2                            0                            0
3                            0                            1
4                            0                            0
5                            0                            0
6                            0                            0
  `Study Time`1–3 hours `Study Time`3–5 hours `Study Time`5+ hours
1                     0                     0                    1
2                     0                     0                    1
3                     0                     0                    1
4                     0                     0                    1
5                     0                     0                    1
6                     0                     0                    0
  `Year in School`2nd Year `Year in School`3rd Year `Year in School`4th Year
1                        0                        0                        0
2                        0                        0                        1
3                        1                        0                        0
4                        0                        0                        0
5                        0                        0                        1
6                        0                        0                        1
  HobbiesMusic HobbiesReading HobbiesSports `Primary Sport`None
1            0              0             1                   0
2            0              0             0                   0
3            0              0             1                   1
4            0              1             0                   0
5            0              1             0                   1
6            0              0             0                   0
  `Primary Sport`Soccer `Living Arrangement`At Home
1                     1                           0
2                     1                           0
3                     0                           0
4                     0                           0
5                     0                           0
6                     1                           1
  `Living Arrangement`With Friends `Part-time Work Hours`
1                                1                     15
2                                0                      7
3                                0                      6
4                                0                     10
5                                0                      6
6                                0                      9
  `Study Group Participation`Yes `Hours of Sleep per Night` `Has a Tutor`Yes
1                              1                        5.4                1
2                              1                        5.4                0
3                              0                        5.6                1
4                              0                        7.8                0
5                              1                        9.0                1
6                              1                        7.5                0</code></pre>
</div>
</div>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>categorical_vars <span class="op">=</span> [</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Café Location"</span>,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Study Time"</span>,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Year in School"</span>,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Hobbies"</span>,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Primary Sport"</span>,</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Living Arrangement"</span>,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Study Group Participation"</span>,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Has a Tutor"</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>s <span class="op">=</span> data[<span class="st">"Study Time"</span>].astype(<span class="st">"string"</span>)</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace en dash/em dash/minus with normal hyphen</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>s <span class="op">=</span> s.<span class="bu">str</span>.replace(<span class="vs">r"[–—−]"</span>, <span class="st">"-"</span>, regex<span class="op">=</span><span class="va">True</span>).<span class="bu">str</span>.strip()</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>study_time_order <span class="op">=</span> [<span class="st">"&lt;1 hour"</span>, <span class="st">"1-3 hours"</span>, <span class="st">"3-5 hours"</span>, <span class="st">"5+ hours"</span>]</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>data[<span class="st">"Study Time"</span>] <span class="op">=</span> pd.Categorical(</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>    s,</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>    categories<span class="op">=</span>study_time_order,</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>    ordered<span class="op">=</span><span class="va">True</span></span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a><span class="co"># One-hot encode</span></span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>data_encoded <span class="op">=</span> pd.get_dummies(</span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a>    data,</span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a>    columns<span class="op">=</span>categorical_vars,</span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a>    drop_first<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a>    dtype<span class="op">=</span><span class="bu">float</span>  <span class="co"># or dtype=int</span></span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-34"><a href="#cb18-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-35"><a href="#cb18-35" aria-hidden="true" tabindex="-1"></a>data_encoded.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>After encoding, each categorical variable is represented numerically, making the dataset suitable for regression modeling. The resulting design matrix includes one column per predictor, with categorical effects interpreted relative to a reference category. We return to this point when interpreting the fitted model.</p>
</section><section id="checking-for-missing-values-and-inconsistencies" class="level4"><h4 class="anchored" data-anchor-id="checking-for-missing-values-and-inconsistencies">4. Checking for Missing Values and Inconsistencies</h4>
<p>A useful step before any analysis is to check for missing data. Missing values can affect model fitting and interpretation, especially when the dataset is small.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Check for missing values in each column</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colSums</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">data</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Café Location                Study Time            Year in School 
                        0                         0                         0 
                  Hobbies             Primary Sport        Living Arrangement 
                        0                         0                         0 
     Part-time Work Hours Study Group Participation  Hours of Sleep per Night 
                        0                         0                         0 
              Has a Tutor          final_grade_prop 
                        0                         0 </code></pre>
</div>
</div>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for missing values in each column</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data.isna().<span class="bu">sum</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>Fortunately, there are no missing values in this dataset. If missing values were present, several options would be available, including removing affected observations, imputing values, or revisiting how the data was collected. The appropriate choice depends on the extent and nature of the missingness, as well as the goals of the analysis.</p>
<div class="Heads-up">
<div class="Heads-up-header">
<p>Heads-up!</p>
</div>
<div class="Heads-up-container">
<p>In addition to missing values, it is also good practice to scan for obvious inconsistencies, such as unexpected category labels or implausible numeric values. Earlier steps have already verified that the response variable lies within the required range. In a larger or messier dataset, it would also be sensible to check whether predictors such as hours of sleep or part-time work hours fall within reasonable bounds. We omit these additional checks here to keep the example focused, but the same principles apply in more complex analyses.</p>
</div>
</div>
</section></section></section><section id="exploratory-data-analysis-eda" class="level2" data-number="5.9"><h2 data-number="5.9" class="anchored" data-anchor-id="exploratory-data-analysis-eda">
<span class="header-section-number">5.9</span> Exploratory Data Analysis (EDA)</h2>
<p>With the data cleaned and prepared, we now turn to our next step in our data science workflow: exploratory data analysis (EDA). The goal of this step is not to draw final conclusions, but to develop intuition about the response variable and its relationship with key predictors.</p>
<section id="distribution-of-the-response-variable" class="level3" data-number="5.9.1"><h3 data-number="5.9.1" class="anchored" data-anchor-id="distribution-of-the-response-variable">
<span class="header-section-number">5.9.1</span> Distribution of the Response Variable</h3>
<p>We begin by examining the distribution of the final grade, expressed as a proportion. This helps us assess whether the response is bounded, skewed, or clustered near the boundaries.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-7-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-1" role="tab" aria-controls="tabset-7-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-2" role="tab" aria-controls="tabset-7-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-7-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-7-1-tab">
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/hist.html">hist</a></span><span class="op">(</span></span>
<span>  <span class="va">data</span><span class="op">$</span><span class="va">final_grade_prop</span>,</span>
<span>  breaks <span class="op">=</span> <span class="fl">10</span>,</span>
<span>  main <span class="op">=</span> <span class="st">"Distribution of Final Grades"</span>,</span>
<span>  xlab <span class="op">=</span> <span class="st">"Final Grade (Proportion)"</span>,</span>
<span>  col <span class="op">=</span> <span class="st">"lightgray"</span>,</span>
<span>  border <span class="op">=</span> <span class="st">"white"</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-beta_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-7-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>plt.hist(</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  data[<span class="st">"final_grade_prop"</span>],</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  bins<span class="op">=</span><span class="dv">10</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Final Grade (Proportion)"</span>)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Frequency"</span>)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Distribution of Final Grades"</span>)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-beta_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The histogram, once again, shows that grades are continuous and bounded between zero and one, with the overall distribution being slightly left skewed. Great to see that students are mostly doing well here!</p>
</section><section id="distribution-of-predictor-variables" class="level3" data-number="5.9.2"><h3 data-number="5.9.2" class="anchored" data-anchor-id="distribution-of-predictor-variables">
<span class="header-section-number">5.9.2</span> Distribution of Predictor Variables</h3>
<p>Let’s also examine the distributions of the predictor variables. This helps us understand the range, balance, and structure of the inputs before moving on to modeling. For continuous predictors, we stick to histograms to inspect their spread and shape. For categorical predictors, bar charts are sufficient to show how observations are distributed across categories.</p>
<section id="continuous-predictors" class="level4"><h4 class="anchored" data-anchor-id="continuous-predictors">Continuous Predictors</h4>
<p>We begin with the continuous predictors: hours of sleep per night and part-time work hours.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-8-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-1" role="tab" aria-controls="tabset-8-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-8-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-2" role="tab" aria-controls="tabset-8-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-8-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-8-1-tab">
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">x</span> <span class="op">&lt;-</span> <span class="va">data</span><span class="op">$</span><span class="va">`Hours of Sleep per Night`</span></span>
<span><span class="va">br</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span>, length.out <span class="op">=</span> <span class="fl">11</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># bins 1..10, with last bin including the rightmost edge like NumPy</span></span>
<span><span class="va">bin_id</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/findInterval.html">findInterval</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">br</span>, rightmost.closed <span class="op">=</span> <span class="cn">TRUE</span>, all.inside <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">counts_like_numpy</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/tabulate.html">tabulate</a></span><span class="op">(</span><span class="va">bin_id</span>, nbins <span class="op">=</span> <span class="fl">10</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Plot the histogram manually so the bar heights match counts_like_numpy exactly</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="cn">NA</span>,</span>
<span>  xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/range.html">range</a></span><span class="op">(</span><span class="va">br</span><span class="op">)</span>,</span>
<span>  ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">counts_like_numpy</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  main <span class="op">=</span> <span class="st">"Hours of Sleep per Night"</span>,</span>
<span>  xlab <span class="op">=</span> <span class="st">"Hours"</span>,</span>
<span>  ylab <span class="op">=</span> <span class="st">"Frequency"</span>,</span>
<span>  xaxt <span class="op">=</span> <span class="st">"n"</span></span>
<span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/axis.html">axis</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/rect.html">rect</a></span><span class="op">(</span></span>
<span>  xleft   <span class="op">=</span> <span class="va">br</span><span class="op">[</span><span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">br</span><span class="op">)</span><span class="op">]</span>,</span>
<span>  ybottom <span class="op">=</span> <span class="fl">0</span>,</span>
<span>  xright  <span class="op">=</span> <span class="va">br</span><span class="op">[</span><span class="op">-</span><span class="fl">1</span><span class="op">]</span>,</span>
<span>  ytop    <span class="op">=</span> <span class="va">counts_like_numpy</span>,</span>
<span>  col     <span class="op">=</span> <span class="st">"lightgray"</span>,</span>
<span>  border  <span class="op">=</span> <span class="st">"white"</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/hist.html">hist</a></span><span class="op">(</span></span>
<span>  <span class="va">data</span><span class="op">$</span><span class="va">`Part-time Work Hours`</span>,</span>
<span>  breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">data</span><span class="op">$</span><span class="va">`Part-time Work Hours`</span><span class="op">)</span>,</span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">data</span><span class="op">$</span><span class="va">`Part-time Work Hours`</span><span class="op">)</span>,</span>
<span>    length.out <span class="op">=</span> <span class="fl">11</span></span>
<span>  <span class="op">)</span>,</span>
<span>  main <span class="op">=</span> <span class="st">"Part-time Work Hours"</span>,</span>
<span>  xlab <span class="op">=</span> <span class="st">"Hours per Week"</span>,</span>
<span>  col <span class="op">=</span> <span class="st">"lightgray"</span>,</span>
<span>  border <span class="op">=</span> <span class="st">"white"</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-beta_files/figure-html/unnamed-chunk-16-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-8-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-8-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">4</span>))</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].hist(data[<span class="st">"Hours of Sleep per Night"</span>], bins<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"Hours of Sleep per Night"</span>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">"Hours"</span>)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"Frequency"</span>)</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].hist(data[<span class="st">"Part-time Work Hours"</span>], bins<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"Part-time Work Hours"</span>)</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">"Hours per Week"</span>)</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-beta_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="Heads-up">
<div class="Heads-up-header">
<p>Heads-up!</p>
</div>
<div class="Heads-up-container">
<p>The R code for Hours of Sleep per Night is intentionally more detailed than usual. This alternative approach ensures that the histogram uses the same bin boundaries and bin-assignment rules as Python, so the two plots are directly comparable. In practice, R’s default hist() function is usually sufficient.</p>
</div>
</div>
<p>Overall, both hours of sleep per night and part-time work hours appear to be approximately uniformly distributed, with no strong skewness or extreme concentration in specific ranges. This suggests that neither predictor is dominated by a narrow subset of values, which is helpful for subsequent regression modeling.</p>
</section><section id="categorical-predictors" class="level4"><h4 class="anchored" data-anchor-id="categorical-predictors">Categorical Predictors</h4>
<p>For categorical predictors, histograms are no longer appropriate. Instead, we use bar charts to visualize how observations are distributed across categories. This allows us to quickly check whether certain groups are under-represented, over-represented, or potentially imbalanced.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-9-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-1" role="tab" aria-controls="tabset-9-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-9-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-2" role="tab" aria-controls="tabset-9-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-9-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-9-1-tab">
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">3</span><span class="op">)</span>, mar <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">7</span>, <span class="fl">4</span>, <span class="fl">3</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">categorical_vars</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  <span class="st">"Café Location"</span>,</span>
<span>  <span class="st">"Study Time"</span>,</span>
<span>  <span class="st">"Year in School"</span>,</span>
<span>  <span class="st">"Hobbies"</span>,</span>
<span>  <span class="st">"Primary Sport"</span>,</span>
<span>  <span class="st">"Living Arrangement"</span>,</span>
<span>  <span class="st">"Study Group Participation"</span>,</span>
<span>  <span class="st">"Has a Tutor"</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="kw">for</span> <span class="op">(</span><span class="va">v</span> <span class="kw">in</span> <span class="va">categorical_vars</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span><span class="op">(</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">data</span><span class="op">[[</span><span class="va">v</span><span class="op">]</span><span class="op">]</span><span class="op">)</span>,</span>
<span>  main <span class="op">=</span> <span class="va">v</span>,</span>
<span>  ylab <span class="op">=</span> <span class="st">"Count"</span>,</span>
<span>  col <span class="op">=</span> <span class="st">"lightgray"</span>,</span>
<span>  border <span class="op">=</span> <span class="st">"white"</span>,</span>
<span>  las <span class="op">=</span> <span class="fl">2</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-beta_files/figure-html/unnamed-chunk-18-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-9-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-9-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>categorical_vars <span class="op">=</span> [</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Café Location"</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Study Time"</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Year in School"</span>,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Hobbies"</span>,</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Primary Sport"</span>,</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Living Arrangement"</span>,</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Study Group Participation"</span>,</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Has a Tutor"</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">3</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">9</span>))</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>axes <span class="op">=</span> axes.flatten()</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, var <span class="kw">in</span> <span class="bu">enumerate</span>(categorical_vars):</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>  counts <span class="op">=</span> data[var].value_counts()</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>  axes[i].bar(counts.index.astype(<span class="bu">str</span>), counts.values)</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>  axes[i].set_title(var)</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>  axes[i].set_ylabel(<span class="st">"Count"</span>)</span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a>  axes[i].tick_params(axis<span class="op">=</span><span class="st">"x"</span>, rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Turn off unused panels (9 total, 8 used)</span></span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(categorical_vars), <span class="bu">len</span>(axes)):</span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a>  axes[j].axis(<span class="st">"off"</span>)</span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb28-29"><a href="#cb28-29" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-beta_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>Overall, the categorical predictors appear to be well balanced across their respective levels. No single category overwhelmingly dominates the dataset, and each level is represented by a reasonable number of observations. This balance is desirable in a regression setting, as it ensures that comparisons between categories are supported by sufficient data and reduces the risk of unstable or highly variable coefficient estimates.</p>
</section></section><section id="relationships-between-predictors-and-the-response" class="level3" data-number="5.9.3"><h3 data-number="5.9.3" class="anchored" data-anchor-id="relationships-between-predictors-and-the-response">
<span class="header-section-number">5.9.3</span> Relationships Between Predictors and the Response</h3>
<p>So far, we have examined each variable individually. While univariate visualizations are useful for understanding distributions and balance, they provide limited insight into how predictors relate to the response variable. To build intuition about these relationships, we now turn to bivariate exploratory analysis, where predictors and the response are examined together. In what follows, we explore the relationship between the response and continuous predictors, followed by the relationship between the response and categorical predictors.</p>
<section id="continuous-predictors-and-the-response" class="level4"><h4 class="anchored" data-anchor-id="continuous-predictors-and-the-response">Continuous Predictors and the Response</h4>
<p>When both the predictor and the response are continuous, scatterplots are a natural and effective visualization choice. Scatterplots allow us to inspect the form of the relationship, assess potential nonlinearity, and identify unusual observations or outliers.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-10-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-1" role="tab" aria-controls="tabset-10-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-10-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-2" role="tab" aria-controls="tabset-10-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-10-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-10-1-tab">
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span></span>
<span>  <span class="va">data</span><span class="op">$</span><span class="va">`Hours of Sleep per Night`</span>,</span>
<span>  <span class="va">data</span><span class="op">$</span><span class="va">final_grade_prop</span>,</span>
<span>  xlab <span class="op">=</span> <span class="st">"Hours of Sleep per Night"</span>,</span>
<span>  ylab <span class="op">=</span> <span class="st">"Final Grade (Proportion)"</span>,</span>
<span>  main <span class="op">=</span> <span class="st">"Sleep and Final Grade"</span>,</span>
<span>  pch <span class="op">=</span> <span class="fl">19</span>,</span>
<span>  col <span class="op">=</span> <span class="st">"gray"</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span></span>
<span>  <span class="va">data</span><span class="op">$</span><span class="va">`Part-time Work Hours`</span>,</span>
<span>  <span class="va">data</span><span class="op">$</span><span class="va">final_grade_prop</span>,</span>
<span>  xlab <span class="op">=</span> <span class="st">"Part-time Work Hours"</span>,</span>
<span>  ylab <span class="op">=</span> <span class="st">"Final Grade (Proportion)"</span>,</span>
<span>  main <span class="op">=</span> <span class="st">"Work Hours and Final Grade"</span>,</span>
<span>  pch <span class="op">=</span> <span class="fl">19</span>,</span>
<span>  col <span class="op">=</span> <span class="st">"gray"</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-beta_files/figure-html/unnamed-chunk-20-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-10-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-10-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">4</span>))</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].scatter(</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  data[<span class="st">"Hours of Sleep per Night"</span>],</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  data[<span class="st">"final_grade_prop"</span>],</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  color<span class="op">=</span><span class="st">"gray"</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">"Hours of Sleep per Night"</span>)</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"Final Grade (Proportion)"</span>)</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"Sleep and Final Grade"</span>)</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].scatter(</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>  data[<span class="st">"Part-time Work Hours"</span>],</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>  data[<span class="st">"final_grade_prop"</span>],</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>  color<span class="op">=</span><span class="st">"gray"</span></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">"Part-time Work Hours"</span>)</span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">"Final Grade (Proportion)"</span>)</span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"Work Hours and Final Grade"</span>)</span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-beta_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>At first glance, the scatterplots do not reveal a strong or obvious relationship between either continuous predictor and the final grade proportion. The points are widely dispersed, and no clear linear trend is immediately apparent. This suggests that, on their own, hours of sleep per night and part-time work hours may not have a simple or direct association with student performance.</p>
<p>However, this observation should be treated as hypothesis-generating rather than conclusive. Scatterplots reflect raw, unadjusted relationships and do not account for the influence of other variables in the dataset. It is therefore possible that these predictors matter only in combination with other factors, or that their effects become apparent after controlling for confounding variables in a regression model.</p>
</section><section id="categorical-predictors-and-the-response" class="level4"><h4 class="anchored" data-anchor-id="categorical-predictors-and-the-response">Categorical Predictors and the Response</h4>
<p>When the predictor is categorical and the response is continuous, scatterplots are no longer appropriate. Instead, we compare the distribution of the response across groups defined by the categorical variable. Boxplots are a convenient choice because they summarize the center, spread, and potential outliers of the response within each category.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-11-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-11-1" role="tab" aria-controls="tabset-11-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-11-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-11-2" role="tab" aria-controls="tabset-11-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-11-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-11-1-tab">
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">3</span><span class="op">)</span>, mar <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">7</span>, <span class="fl">4</span>, <span class="fl">3</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">categorical_vars</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  <span class="st">"Café Location"</span>,</span>
<span>  <span class="st">"Study Time"</span>,</span>
<span>  <span class="st">"Year in School"</span>,</span>
<span>  <span class="st">"Hobbies"</span>,</span>
<span>  <span class="st">"Primary Sport"</span>,</span>
<span>  <span class="st">"Living Arrangement"</span>,</span>
<span>  <span class="st">"Study Group Participation"</span>,</span>
<span>  <span class="st">"Has a Tutor"</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="kw">for</span> <span class="op">(</span><span class="va">v</span> <span class="kw">in</span> <span class="va">categorical_vars</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/graphics/boxplot.html">boxplot</a></span><span class="op">(</span></span>
<span>    <span class="va">data</span><span class="op">$</span><span class="va">final_grade_prop</span> <span class="op">~</span> <span class="va">data</span><span class="op">[[</span><span class="va">v</span><span class="op">]</span><span class="op">]</span>,</span>
<span>    main <span class="op">=</span> <span class="va">v</span>,</span>
<span>    ylab <span class="op">=</span> <span class="st">"Final Grade (Proportion)"</span>,</span>
<span>    xlab <span class="op">=</span> <span class="va">v</span>,</span>
<span>    col <span class="op">=</span> <span class="st">"lightgray"</span>,</span>
<span>    las <span class="op">=</span> <span class="fl">2</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-beta_files/figure-html/unnamed-chunk-22-3.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-11-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-11-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>categorical_vars <span class="op">=</span> [</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Café Location"</span>,</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Study Time"</span>,</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Year in School"</span>,</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Hobbies"</span>,</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Primary Sport"</span>,</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Living Arrangement"</span>,</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Study Group Participation"</span>,</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Has a Tutor"</span></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">3</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">9</span>))</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>axes <span class="op">=</span> axes.flatten()</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, var <span class="kw">in</span> <span class="bu">enumerate</span>(categorical_vars):</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>  data.boxplot(</span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>    column<span class="op">=</span><span class="st">"final_grade_prop"</span>,</span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>    by<span class="op">=</span>var,</span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>    ax<span class="op">=</span>axes[i],</span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>    grid<span class="op">=</span><span class="va">False</span></span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a>  axes[i].set_title(var)</span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a>  axes[i].set_xlabel(<span class="st">""</span>)</span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a>  axes[i].set_ylabel(<span class="st">"Final Grade (Proportion)"</span>)</span>
<span id="cb33-27"><a href="#cb33-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-28"><a href="#cb33-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Turn off unused panel</span></span>
<span id="cb33-29"><a href="#cb33-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-30"><a href="#cb33-30" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(categorical_vars), <span class="bu">len</span>(axes)):</span>
<span id="cb33-31"><a href="#cb33-31" aria-hidden="true" tabindex="-1"></a>  axes[j].axis(<span class="st">"off"</span>)</span>
<span id="cb33-32"><a href="#cb33-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-33"><a href="#cb33-33" aria-hidden="true" tabindex="-1"></a>plt.suptitle(<span class="st">""</span>)</span>
<span id="cb33-34"><a href="#cb33-34" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb33-35"><a href="#cb33-35" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-beta_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>From the plots, we observe that study time is the only predictor with a clearly visible positive association with final grade. This finding is largely unsurprising and aligns well with common intuition: students who devote more time to studying tend to perform better academically.</p>
<p>At the same time, it is somewhat unexpected that the remaining categorical variables show little evidence of a strong marginal relationship with the response. Factors such as tutoring status, study group participation, living arrangement, or extracurricular interests might reasonably be expected to influence academic performance, yet no clear or consistent differences emerge when these variables are examined in isolation.</p>
<p>These observations are intriguing but should be interpreted with caution. The analysis at this stage is purely exploratory and reflects only superficial, marginal relationships. While these insights help guide our expectations, no substantive conclusions can be drawn until formal modeling is conducted, where the effects of multiple predictors can be assessed simultaneously.</p>
</section></section></section><section id="data-modeling" class="level2" data-number="5.10"><h2 data-number="5.10" class="anchored" data-anchor-id="data-modeling">
<span class="header-section-number">5.10</span> Data Modeling</h2>
<p>After exploring the data and developing initial intuition through EDA, we now turn to the modeling stage. The purpose of this step is to formalize the relationships we observed and assess how different academic and lifestyle factors are associated with students’ final grades when considered jointly.</p>
<section id="choosing-a-suitable-regression-model" class="level3" data-number="5.10.1"><h3 data-number="5.10.1" class="anchored" data-anchor-id="choosing-a-suitable-regression-model">
<span class="header-section-number">5.10.1</span> Choosing a Suitable Regression Model</h3>
<p>The choice of regression model should follow directly from what we have learned about the response variable and from the goals of the analysis.</p>
<p>In this case, the response variable, <code>final_grade_prop</code>, represents a student’s final grade expressed as a proportion. After preprocessing, all values lie strictly between zero and one. The EDA also showed that grades are not symmetrically distributed and tend to cluster toward higher values, with variability that appears to depend on the average grade level.</p>
<p>Equally important, our goal is not to predict future grades as accurately as possible, but to understand how study habits, lifestyle factors, and forms of academic support are associated with students’ performance.</p>
<p>Taken together, these considerations point toward Beta regression as an appropriate modeling choice. Beta regression is designed specifically for proportion data and naturally respects the bounds of the response. It allows the mean of the response to depend on predictors while accommodating heteroskedasticity, which is common in proportional outcomes.</p>
<p>By contrast, Ordinary Least Squares assumes constant variance and does not constrain predictions to the unit interval. These assumptions are difficult to justify for grade data, making OLS a less suitable option for this analysis.</p>
</section><section id="defining-modeling-parameters" class="level3" data-number="5.10.2"><h3 data-number="5.10.2" class="anchored" data-anchor-id="defining-modeling-parameters">
<span class="header-section-number">5.10.2</span> Defining Modeling Parameters</h3>
<p>With the modeling framework selected, the next step is to specify which variables to include. In this case study, we include all available predictors to capture a broad and realistic picture of student life.</p>
<p>The predictors reflect multiple dimensions of a student’s experience, including time allocation (such as study time, sleep, and part-time work hours), academic context (such as year in school), and sources of support (such as tutoring and study group participation), as well as several categorical variables describing personal routines and preferences.</p>
<p>Including the full set of predictors allows us to examine the association between each factor and the average final grade while holding other variables constant. This multivariable perspective is especially important given that most predictors showed weak marginal relationships during EDA but may still play a role once considered together.</p>
</section><section id="setting-up-the-modeling-equation" class="level3" data-number="5.10.3"><h3 data-number="5.10.3" class="anchored" data-anchor-id="setting-up-the-modeling-equation">
<span class="header-section-number">5.10.3</span> Setting Up the Modeling Equation</h3>
<p>Using Beta regression with a logit link, we model the average final grade proportion as a function of the predictors.</p>
<p>For each student <span class="math inline">\(i\)</span>, the response is assumed to follow a Beta distribution,</p>
<p><span class="math display">\[
Y_i \sim \text{Beta}(\mu_i \phi,\ (1 - \mu_i)\phi)
\]</span></p>
<p>where <span class="math inline">\(\mu_i\)</span> denotes the average grade proportion and <span class="math inline">\(\phi\)</span> controls how concentrated grades are around that average.</p>
<p>The average proportion is linked to the predictors through the linear predictor:</p>
<div style="overflow-x: auto; white-space: nowrap;">
<p><span class="math display">\[
\begin{aligned}
\text{logit}(\mu_i) &amp;= \beta_0 \\
&amp;\quad + \beta_1 \times \text{part\_time\_work\_hours}_i \\
&amp;\quad + \beta_2 \times \text{hours\_of\_sleep}_i \\
&amp;\quad + \text{(terms for Study Time)} \\
&amp;\quad + \text{(terms for Café Location)} \\
&amp;\quad + \text{(terms for Year in School)} \\
&amp;\quad + \text{(terms for Hobbies)} \\
&amp;\quad + \text{(terms for Primary Sport)} \\
&amp;\quad + \text{(terms for Living Arrangement)} \\
&amp;\quad + \text{(terms for Study Group Participation)} \\
&amp;\quad + \text{(terms for Has a Tutor)}
\end{aligned}
\]</span></p>
</div>
<p>The logit link maps the average grade proportion to the real line, allowing predictors to enter the model in a familiar linear form. Once the linear predictor is computed, we can return to the original grade scale using the inverse-logit transformation,</p>
<p><span class="math display">\[
\mu_i = \frac{\exp(\eta_i)}{1 + \exp(\eta_i)}
\]</span></p>
<p>where <span class="math inline">\(\eta_i\)</span> represents the linear combination of predictors.</p>
<p>Under this model, each coefficient describes how a predictor is associated with changes in the average final grade, on the logit scale, holding all other variables constant. Positive coefficients correspond to higher expected grades, while negative coefficients correspond to lower expected grades.</p>
<p>With the model structure defined, we are now ready to estimate the model parameters and examine how these academic and lifestyle factors relate to student performance in practice.</p>
</section></section><section id="estimation" class="level2" data-number="5.11"><h2 data-number="5.11" class="anchored" data-anchor-id="estimation">
<span class="header-section-number">5.11</span> Estimation</h2>
<p>With the model structure clearly defined, we now move on to estimation. In this step, we fit the Beta regression model to the data and obtain numerical estimates for each coefficient. These estimates allow us to quantify how different academic and lifestyle factors are associated with students’ average final grades under the specified model.</p>
<div class="Tip">
<div class="Tip-header">
<p>How Beta Regression Is Fit</p>
</div>
<div class="Tip-container">
<p>Like Gamma regression, Beta regression is typically estimated using maximum likelihood estimation (MLE). Rather than minimizing squared errors, MLE finds the parameter values that make the observed proportions most likely under the assumed Beta distribution. This approach naturally accounts for the bounded nature of the response and the relationship between the mean and variability.</p>
</div>
</div>
<section id="fitting-the-model" class="level3" data-number="5.11.1"><h3 data-number="5.11.1" class="anchored" data-anchor-id="fitting-the-model">
<span class="header-section-number">5.11.1</span> Fitting the Model</h3>
<p>In R, Beta regression can be fit using the <code><a href="https://rdrr.io/pkg/betareg/man/betareg.html">betareg()</a></code> function, which is designed specifically for proportion outcomes. In Python, Beta regression is available through <code>statsmodels</code>, allowing us to specify the same link function and modeling structure.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-12-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-12-1" role="tab" aria-controls="tabset-12-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-12-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-12-2" role="tab" aria-controls="tabset-12-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-12-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-12-1-tab">
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://topmodels.R-Forge.R-project.org/betareg/">betareg</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Fit Beta regression model with logit link</span></span>
<span><span class="va">beta_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/betareg/man/betareg.html">betareg</a></span><span class="op">(</span></span>
<span>  <span class="va">final_grade_prop</span> <span class="op">~</span> <span class="va">.</span>,</span>
<span>  data <span class="op">=</span> <span class="va">data</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Display model summary</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">beta_model</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
betareg(formula = final_grade_prop ~ ., data = data)

Quantile residuals:
    Min      1Q  Median      3Q     Max 
-2.6021 -0.6404 -0.0795  0.4838  6.7978 

Coefficients (mean model with logit link):
                                       Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                           0.6665207  0.0888619   7.501 6.35e-14 ***
`Café Location`Bean Around the World  0.0504412  0.0372442   1.354    0.176    
`Café Location`Ike's Café             0.0065107  0.0370293   0.176    0.860    
`Café Location`Koerner's Pub          0.0047134  0.0362279   0.130    0.896    
`Café Location`The Loop Café          0.0055751  0.0375507   0.148    0.882    
`Study Time`1–3 hours                 0.4579250  0.0290849  15.744  &lt; 2e-16 ***
`Study Time`3–5 hours                 1.1301265  0.0327078  34.552  &lt; 2e-16 ***
`Study Time`5+ hours                  1.7063296  0.0385853  44.222  &lt; 2e-16 ***
`Year in School`2nd Year              0.0439984  0.0331393   1.328    0.184    
`Year in School`3rd Year              0.0260794  0.0338020   0.772    0.440    
`Year in School`4th Year              0.0161057  0.0332232   0.485    0.628    
HobbiesMusic                         -0.0213915  0.0337388  -0.634    0.526    
HobbiesReading                        0.0317771  0.0341174   0.931    0.352    
HobbiesSports                         0.0212625  0.0340996   0.624    0.533    
`Primary Sport`None                   0.0326562  0.0291631   1.120    0.263    
`Primary Sport`Soccer                 0.0245573  0.0291159   0.843    0.399    
`Living Arrangement`At Home          -0.0055100  0.0294296  -0.187    0.851    
`Living Arrangement`With Friends     -0.0119983  0.0287634  -0.417    0.677    
`Part-time Work Hours`               -0.0008363  0.0020272  -0.413    0.680    
`Study Group Participation`Yes        0.0234348  0.0237683   0.986    0.324    
`Hours of Sleep per Night`           -0.0144863  0.0102243  -1.417    0.157    
`Has a Tutor`Yes                      0.0240666  0.0239712   1.004    0.315    

Phi coefficients (precision model with identity link):
      Estimate Std. Error z value Pr(&gt;|z|)    
(phi)    43.98       1.96   22.44   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Type of estimator: ML (maximum likelihood)
Log-likelihood:  1475 on 23 Df
Pseudo R-squared: 0.6014
Number of iterations: 36 (BFGS) + 2 (Fisher scoring) </code></pre>
</div>
</div>
</div>
<div id="tabset-12-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-12-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.othermod.betareg <span class="im">import</span> BetaModel</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> data_encoded[<span class="st">"final_grade_prop"</span>].astype(<span class="bu">float</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> data_encoded.drop(columns<span class="op">=</span>[<span class="st">"final_grade_prop"</span>])</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(X, has_constant<span class="op">=</span><span class="st">"add"</span>) </span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>fit_py <span class="op">=</span> BetaModel(y, X).fit()</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(fit_py.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="interpreting-the-coefficients" class="level3" data-number="5.11.2"><h3 data-number="5.11.2" class="anchored" data-anchor-id="interpreting-the-coefficients">
<span class="header-section-number">5.11.2</span> Interpreting the Coefficients</h3>
<p>Based on the output, the (partially shown) fitted equation is:</p>
<div style="overflow-x: auto; white-space: nowrap;">
<p><span class="math display">\[
\begin{aligned}
\text{logit}(\mu_i) &amp;= 0.665 \\
&amp;\quad + -0.0008 \times \text{part_time_work_hours}_i \\
&amp;\quad + -0.0145 \times \text{hours_of_sleep}_i \\
&amp;\quad + \text{(terms for Study Time)} \\
&amp;\quad + \text{(terms for Café Location)} \\
&amp;\quad + \text{(terms for Year in School)} \\
&amp;\quad + \text{(terms for Hobbies)} \\
&amp;\quad + \text{(terms for Primary Sport)} \\
&amp;\quad + \text{(terms for Living Arrangement)} \\
&amp;\quad + \text{(terms for Study Group Participation)} \\
&amp;\quad + \text{(terms for Has a Tutor)}
\end{aligned}
\]</span></p>
</div>
<p>While we can interpret the numbers given here, but before that, we should always check goodness of fit first. If the goodness of fit is bad, then the interpretation of these numbers could be meaningless.</p>
</section></section><section id="goodness-of-fit" class="level2" data-number="5.12"><h2 data-number="5.12" class="anchored" data-anchor-id="goodness-of-fit">
<span class="header-section-number">5.12</span> Goodness of Fit</h2>
<p>Assessing goodness of fit for Beta regression is conceptually similar to other generalized linear models, but there are a few important differences compared to ordinary least squares regression.</p>
<section id="log-likelihood-aic-and-bic" class="level3" data-number="5.12.1"><h3 data-number="5.12.1" class="anchored" data-anchor-id="log-likelihood-aic-and-bic">
<span class="header-section-number">5.12.1</span> Log-likelihood, AIC, and BIC</h3>
<p>Because Beta regression is fit using maximum likelihood, overall model fit is commonly assessed using:</p>
<ul>
<li>Log-likelihood</li>
<li>Akaike Information Criterion (AIC)</li>
<li>Bayesian Information Criterion (BIC)</li>
</ul>
<p>Higher log-likelihood values indicate a better fit, while lower AIC and BIC values suggest a preferable balance between model fit and model complexity. These metrics are especially useful when comparing multiple Beta regression models fitted to the same response variable. In our fitted model, the log-likelihood is 1474.7, the AIC is −2903, and the BIC is −2791. Although we do not compare multiple models here, these metrics become especially informative when evaluating alternative model specifications.</p>
</section><section id="pseudo-r2" class="level3" data-number="5.12.2"><h3 data-number="5.12.2" class="anchored" data-anchor-id="pseudo-r2">
<span class="header-section-number">5.12.2</span> Pseudo-<span class="math inline">\(R^2\)</span>
</h3>
<p>When using R’s <code><a href="https://rdrr.io/pkg/betareg/man/betareg.html">betareg()</a></code>, the model summary reports a pseudo-<span class="math inline">\(R^2\)</span> value. This quantity is defined as:</p>
<p><span class="math display">\[
R^{2}_{\text{pseudo}} = 1 - \frac{\ell(\text{null model})}{\ell(\text{fitted model})}
\]</span></p>
<p>where <span class="math inline">\(\ell(\cdot)\)</span> denotes the log-likelihood. This measure quantifies how much the fitted model improves upon an intercept-only model. From the R output, the pseudo-<span class="math inline">\(R^2\)</span> for our model is 0.6014, indicating an improvement over the null model.</p>
<div class="Heads-up">
<div class="Heads-up-header">
<p>Notes on pseudo-<span class="math inline">\(R^2\)</span></p>
</div>
<div class="Heads-up-container">
<p>When interpreting pseudo-<span class="math inline">\(R^2\)</span>, it is important to keep the following points in mind:</p>
<ul>
<li>This pseudo-<span class="math inline">\(R^2\)</span> is not directly comparable to the <span class="math inline">\(R^2\)</span> from linear regression.</li>
<li>Values tend to be lower and should be interpreted relatively, not absolutely.</li>
<li>The pseudo-<span class="math inline">\(R^2\)</span> is most useful for comparing competing models, rather than judging fit in isolation.</li>
</ul>
<p>In contrast, Python’s <code>statsmodels.BetaModel</code> does not report a pseudo-<span class="math inline">\(R^2\)</span> by default, even though the same quantity could be computed manually from the log-likelihoods. This reflects a design choice rather than a difference in the underlying statistical model.</p>
</div>
</div>
</section><section id="precision-parameter" class="level3" data-number="5.12.3"><h3 data-number="5.12.3" class="anchored" data-anchor-id="precision-parameter">
<span class="header-section-number">5.12.3</span> Precision Parameter</h3>
<p>Beta regression models not only the mean of the response but also its dispersion through a precision parameter, commonly denoted by <span class="math inline">\(\phi\)</span>. As a result, assessing goodness of fit involves evaluating not only how well the model captures the mean structure, but also whether it represents the variability in the data reasonably. Under the standard mean–precision parameterization, the conditional variance of the response is given by:</p>
<p><span class="math display">\[
\mathrm{Var}(Y_i \mid X_i) = \dfrac{\mu_i (1 - \mu_i)}{1 + \phi}
\]</span></p>
<p>Larger values of <span class="math inline">\(\phi\)</span> indicate that observations are more tightly concentrated around the fitted mean, while smaller values correspond to greater variability. A poorly estimated precision parameter may suggest that the model does not fully capture the dispersion in the response, even if the fitted means appear reasonable.</p>
<p>In R’s <code><a href="https://rdrr.io/pkg/betareg/man/betareg.html">betareg()</a></code>, the precision parameter is estimated directly. In this example, the fitted model reports:</p>
<p><span class="math display">\[
\hat{\phi}=43.98
\]</span></p>
<p>In contrast, Python’s <code>statsmodels.BetaModel</code> reports the precision parameter on a transformed (log) scale. The reported value of 3.78 corresponds to:</p>
<p><span class="math display">\[
\exp(3.78) = 43.98
\]</span></p>
<p>which aligns closely with the estimate obtained from <code><a href="https://rdrr.io/pkg/betareg/man/betareg.html">betareg()</a></code>. Thus, although the numerical values appear different, both implementations are estimating the same underlying precision parameter, and the fitted models are consistent.</p>
<p>Once the precision parameter <span class="math inline">\(\phi\)</span> has been estimated, we can substitute it into the conditional variance formula to assess whether the implied variability is reasonable for the observed data. In practice, the precision parameter is best interpreted alongside residual diagnostics rather than judged by an absolute threshold. ​ ### Residual Diagnostics</p>
<p>As with other generalized linear models, residual diagnostics help us check whether a Beta regression model is capturing the main patterns in the data. In this section, we focus on Pearson residuals, which compare the observed values to the fitted mean values on a standardized scale.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-13-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-13-1" role="tab" aria-controls="tabset-13-1" aria-selected="true">R Code</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-13-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-13-2" role="tab" aria-controls="tabset-13-2" aria-selected="false">Python Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-13-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-13-1-tab">
<div class="cell">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://topmodels.R-Forge.R-project.org/betareg/">betareg</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Extract fitted means and residuals</span></span>
<span><span class="va">mu_hat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">beta_model</span><span class="op">)</span></span>
<span><span class="va">r_pearson</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">beta_model</span>, type <span class="op">=</span> <span class="st">"pearson"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">mu_hat</span>, <span class="va">r_pearson</span>,</span>
<span>     xlab <span class="op">=</span> <span class="st">"Fitted mean (mu_hat)"</span>,</span>
<span>     ylab <span class="op">=</span> <span class="st">"Pearson residual"</span>,</span>
<span>     main <span class="op">=</span> <span class="st">"Pearson residuals vs fitted"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span>h <span class="op">=</span> <span class="fl">0</span>, lty <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-beta_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-13-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-13-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>mu_hat <span class="op">=</span> fit_py.fittedvalues</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>pearson_resid <span class="op">=</span> fit_py.resid_pearson</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>plt.scatter(mu_hat, pearson_resid)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">0</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Fitted mean"</span>)</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Pearson residual"</span>)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Pearson residuals vs fitted"</span>)</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="05-beta_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The plots show Pearson residuals plotted against the fitted mean values. The residuals are centered around zero across the range of fitted values, indicating no systematic over- or under-prediction. The vertical banding reflects groups of observations with similar fitted means, often arising from categorical predictors. While residual variability increases slightly for fitted means close to one, this behavior is expected for Beta regression due to the bounded nature of the response. Overall, the diagnostics suggest that the model provides an adequate fit to the data.</p>
</section></section><section id="results" class="level2" data-number="5.13"><h2 data-number="5.13" class="anchored" data-anchor-id="results">
<span class="header-section-number">5.13</span> Results</h2>
<p>Great! Nothing seems particularly concerning with goodness of fit. Having established that the model fits the data reasonably well, we can now finally turn to the substantive findings, interpreting results and answering our central question:</p>
<blockquote class="blockquote">
<p>Which aspects of students’ academic and daily routines are associated with differences in final course grades?</p>
</blockquote>
<p>Recall that the model was fit using Beta regression with a logit link. As a result, coefficients describe changes in the log-odds of the mean grade proportion, rather than direct changes in grades themselves. Exponentiating a coefficient yields an odds ratio, which reflects how the odds of achieving a higher average grade change as a predictor increases, holding all other variables constant.</p>
<p>Because the logit link is nonlinear, these effects should be interpreted in relative terms rather than as fixed percentage-point increases. The same change in log-odds can correspond to different changes in grade proportions depending on where a student lies on the grade scale.</p>
<section id="predictors-associated-with-final-grades" class="level3" data-number="5.13.1"><h3 data-number="5.13.1" class="anchored" data-anchor-id="predictors-associated-with-final-grades">
<span class="header-section-number">5.13.1</span> Predictors Associated with Final Grades</h3>
<p>Among all variables included in the model, <em>Study Time</em> stands out as the dominant factor associated with academic performance.</p>
<p>Using students who study less than one hour as the reference group, we observe a clear and increasing association between reported study time and average grades:</p>
<ul>
<li>1–3 hours of study The estimated coefficient is 0.458, corresponding to an odds ratio of</li>
</ul>
<p><span class="math display">\[
e^0.458 \approx 1.58
\]</span></p>
<p>This indicates that students who study 1–3 hours have noticeably higher odds of achieving a higher average grade than those in the baseline group.</p>
<ul>
<li>3–5 hours of study With a coefficient of 1.130, the odds ratio increases to</li>
</ul>
<p><span class="math display">\[
e^1.130 \approx 3.10
\]</span></p>
<p>This suggests that students in this category have roughly three times the odds of a higher mean grade compared to the reference group.</p>
<ul>
<li>5+ hours of study The largest effect is observed here, with a coefficient of 1.706 and an odds ratio of</li>
</ul>
<p><span class="math display">\[
e^1.706 \approx 5.51
\]</span></p>
<p>Students who study five or more hours are therefore predicted to have substantially higher average grades than those who study less than one hour.</p>
<p>The pattern is monotonic and strong: as reported study time increases, the model consistently predicts higher average grade proportions. This relationship remains even after adjusting for sleep, work hours, academic year, and other lifestyle variables.</p>
</section><section id="variables-without-strong-evidence-of-association" class="level3" data-number="5.13.2"><h3 data-number="5.13.2" class="anchored" data-anchor-id="variables-without-strong-evidence-of-association">
<span class="header-section-number">5.13.2</span> Variables Without Strong Evidence of Association</h3>
<p>In contrast, the remaining predictors in the model do not show statistically significant associations with final grades at conventional significance levels.</p>
<p>These include:</p>
<ul>
<li>Part-time work hours</li>
<li>Hours of sleep per night</li>
<li>Café location</li>
<li>Year in school</li>
<li>Hobbies</li>
<li>Primary sport</li>
<li>Living arrangement</li>
<li>Study group participation</li>
<li>Tutoring status</li>
</ul>
<p>For example, the estimated effects of part-time work hours and sleep duration are small relative to their uncertainty, providing little evidence of a systematic relationship with grades once study time is accounted for. Similarly, variables describing where students study or whether they participate in academic support activities do not appear to differentiate average grades in this dataset.</p>
<div class="Tip">
<div class="Tip-header">
<p>Interpretation Reminder</p>
</div>
<div class="Tip-container">
<p>It is worth emphasizing that these findings are conditional on the model specification and the available data. Lack of statistical significance does not imply that these factors are unimportant in all settings, only that the present analysis does not provide strong evidence of an association.</p>
</div>
</div>
</section></section><section id="storytelling" class="level2" data-number="5.14"><h2 data-number="5.14" class="anchored" data-anchor-id="storytelling">
<span class="header-section-number">5.14</span> Storytelling</h2>
<p>To complete the data science workflow, we step back from coefficients and diagnostics and focus on how the results can be interpreted and applied in practice. This final stage, storytelling, is where statistical output is translated into insights that support real-world decision-making.</p>
<p>In this case study, the Beta regression model helps us understand how different aspects of students’ academic lives relate to their final course grades. Rather than treating grades as isolated numbers, the model allows us to view them as outcomes shaped by study habits, routines, and context. Below, we distill the key takeaways from the analysis and discuss what they imply for students, instructors, and academic support staff.</p>
<section id="key-insights-from-the-model" class="level3" data-number="5.14.1"><h3 data-number="5.14.1" class="anchored" data-anchor-id="key-insights-from-the-model">
<span class="header-section-number">5.14.1</span> Key Insights From the Model</h3>
<p>Study time stands out as the primary driver of academic performance. Across all model specifications, higher reported study time is consistently associated with higher average grades. The relationship is not only statistically significant, but also monotonic: students who study more tend to achieve better outcomes, even after accounting for sleep, work commitments, and other lifestyle factors. This reinforces a simple but powerful message—sustained study effort plays a central role in academic success.</p>
<p>From a practical perspective, this suggests that interventions aimed at improving time management, study planning, and sustained engagement with course material are likely to yield meaningful benefits. Academic advisors and instructors might focus less on where or how students study, and more on helping them build realistic, consistent study routines.</p>
<p>Many commonly discussed lifestyle factors show little evidence of association once study time is accounted for. Variables such as hours of sleep, part-time work hours, tutoring, study group participation, and living arrangement do not display strong independent associations with final grades in this model. While these factors are often assumed to influence academic outcomes, the analysis suggests that their effects may be indirect, context-dependent, or mediated through study time itself.</p>
<p>This does not mean that sleep or academic support are unimportant. Rather, it suggests that their influence may be more subtle than often assumed, or that they matter most when they enable students to study more effectively. In other words, these factors may support learning indirectly rather than directly translating into higher grades.</p>
<p>Environment and personal preferences appear less critical than effort in this dataset. Café location, hobbies, and sports participation show no clear relationship with grades once other variables are controlled for. This finding highlights an encouraging implication: students with very different routines and preferences can achieve similar outcomes, provided they invest sufficient time and effort into studying. Academic success does not appear to be tied to a specific lifestyle or environment, but rather to how students allocate their time.</p>
<div class="Tip">
<div class="Tip-header">
<p>Using the Results Responsibly</p>
</div>
<div class="Tip-container">
<p>It is important to remember that this analysis is associational, not causal. The model does not prove that increasing study time will automatically raise grades for every student. Instead, it shows that, in this dataset, higher study time tends to co-occur with higher average grades after accounting for other measured factors.</p>
<p>Nevertheless, the results provide a useful evidence-based starting point for discussion. They help prioritize which factors are most strongly linked to performance and which may play a smaller or more indirect role. For educators and institutions, this kind of insight can guide where limited resources and attention are most likely to have impact.</p>
</div>
</div>
</section></section><section id="conclusion" class="level2" data-number="5.15"><h2 data-number="5.15" class="anchored" data-anchor-id="conclusion">
<span class="header-section-number">5.15</span> Conclusion</h2>
<p>This chapter has walked through a complete data science workflow using Beta regression, from problem formulation and data preparation to modeling, diagnostics, and interpretation. Along the way, we have seen how Beta regression offers a principled and flexible framework for analyzing outcomes that are continuous, bounded between zero and one, and heteroskedastic.</p>
<p>More importantly, the chapter highlights that the value of Beta regression lies not just in fitting a model, but in using the model thoughtfully within a broader analytical process. Careful study design, appropriate preprocessing, exploratory analysis, model checking, and clear communication are what ultimately turn proportion data into actionable insight.</p>
<p>With these ideas in place, you are now equipped to apply Beta regression to a wide range of real-world problems, from academic performance and completion rates to conversion metrics and coverage proportions, and to communicate your findings in a way that supports informed decision-making.</p>
<div class="Warning">
<div class="Warning-header">
<p>Fun fact!</p>
</div>
<div class="Warning-container">
<p><strong>Soup-erb!</strong> Soup that’s so heartwarming it feels like a cozy hug.</p>
</div>
</div>
<div id="fig-beta-regression" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-beta-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"></figure><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Regression 
  Analysis)
    Continuous &lt;br/&gt;Outcome Y
      {{Unbounded &lt;br/&gt;Outcome Y}}
        )Chapter 3: &lt;br/&gt;Ordinary &lt;br/&gt;Least Squares &lt;br/&gt;Regression(
          (Normal &lt;br/&gt;Outcome Y)
      {{Nonnegative &lt;br/&gt;Outcome Y}}
        )Chapter 4: &lt;br/&gt;Gamma Regression(
          (Gamma &lt;br/&gt;Outcome Y)
      {{Bounded &lt;br/&gt;Outcome Y &lt;br/&gt; between 0 and 1}}
        )Chapter 5: Beta &lt;br/&gt;Regression(
          (Beta &lt;br/&gt;Outcome Y)
    Discrete &lt;br/&gt;Outcome Y
</pre>
</div>
<p></p>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-beta-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1
</figcaption></figure>
</div>


</section></main><!-- /main --><style>
  #cookie-popup {
    position: fixed;
    bottom: 30px;
    right: 30px;
    width: 340px;
    max-width: calc(100vw - 40px);
    background-color: #ffffff;
    padding: 24px 26px;
    border-radius: 12px;
    box-shadow: 0 10px 25px rgba(0, 0, 0, 0.14);
    border: 1px solid #f8c471;
    z-index: 9999;
    font-family: inherit;
    display: none;
  }

  #cookie-popup h4 {
    margin: 0 0 10px 0;
    font-size: 1.05rem;
    line-height: 1.3;
    font-weight: 700;
    color: #f35c24;
  }

  #cookie-popup p {
    margin: 0 0 20px 0;
    font-size: 0.9rem;
    line-height: 1.55;
    color: #808080;
  }

  #cookie-popup a {
    color: rgb(214, 122, 127);
    text-decoration: underline;
    text-underline-offset: 2px;
    font-weight: 600;
  }

  #cookie-popup a:hover {
    color: #f35c24;
  }

  .popup-button-container {
    display: flex;
    gap: 10px;
  }

  .btn-accept,
  .btn-decline {
    flex: 1;
    padding: 10px 12px;
    border-radius: 6px;
    cursor: pointer;
    font-weight: 700;
    font-family: inherit;
    font-size: 0.9rem;
    transition: background-color 0.15s ease, border-color 0.15s ease, color 0.15s ease;
  }

  .btn-accept {
    background-color: #f35c24;
    color: #ffffff;
    border: 1px solid #f35c24;
  }

  .btn-decline {
    background-color: #FCF3CF;
    color: #0b4b91;
    border: 1px solid #f8c471;
  }

  .btn-accept:hover {
    background-color: #d94d18;
    border-color: #d94d18;
  }

  .btn-decline:hover {
    background-color: #f8c471;
    color: #0b4b91;
  }

  @media (max-width: 600px) {
    #cookie-popup {
      left: 20px;
      right: 20px;
      bottom: 20px;
      width: auto;
    }

    .popup-button-container {
      flex-direction: column;
    }
  }
</style>
<div id="cookie-popup" role="dialog" aria-live="polite" aria-label="Cookie consent notice">
  <h4>We value your privacy.</h4>

  <p>
    Do you consent to the use of cookies to analyze website traffic?
    No personally identifying information is stored.
    See our <a href="https://alexrod61.github.io/regression-cookbook/book/privacy-policy.html">privacy policy here</a>.
  </p>

  <div class="popup-button-container">
    <button class="btn-accept" onclick="acceptCookies()">Accept</button>
    <button class="btn-decline" onclick="declineCookies()">Decline</button>
  </div>
</div>

<script>
  window.addEventListener('load', function() {
    const consent = localStorage.getItem('cookieConsent');

    if (!consent) {
      document.getElementById('cookie-popup').style.display = 'block';
    } else if (consent === 'granted') {
      activateAnalytics();
    }
  });

  function acceptCookies() {
    localStorage.setItem('cookieConsent', 'granted');
    activateAnalytics();
    closePopup();
  }

  function declineCookies() {
    localStorage.setItem('cookieConsent', 'denied');
    closePopup();
  }

  function closePopup() {
    document.getElementById('cookie-popup').style.display = 'none';
  }

  function activateAnalytics() {
    if (typeof gtag === 'function') {
      gtag('consent', 'update', {
        'analytics_storage': 'granted'
      });
    }
  }
</script><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/alexrod61\.github\.io\/regression-cookbook\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
          // default icon
          link.classList.add("external");
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><script src="https://giscus.app/client.js" data-repo="alexrod61/regression-cookbook" data-repo-id="R_kgDOMSJoUA" data-category="General" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><input type="hidden" id="giscus-base-theme" value="light"><input type="hidden" id="giscus-alt-theme" value="dark"><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../book/04-gamma.html" class="pagination-link" aria-label="Gamma Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Gamma Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../book/06-parametric-survival.html" class="pagination-link" aria-label="Parametric Survival Regression">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Parametric Survival Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2026; G. Alexi Rodríguez-Arelis, Andy Tai, Ben Chen, and Payman Nickchi.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/alexrod61/regression-cookbook/edit/main/book/05-beta.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/alexrod61/regression-cookbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li><li><a href="https://github.com/alexrod61/regression-cookbook/blob/main/book/05-beta.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>