<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-7PRVEBE1EF"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-7PRVEBE1EF');
</script>

# Gamma Regression {#sec-gamma}

```{r}
#| include: false

colourize <- function(x, color) {
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color,
      x)
  } else x
}
```

::: {.Warning}
::::{.Warning-header}
When to Use and Not Use Gamma Regression
::::
::::{.Warning-container}
Gamma regression is a type of generalized linear model that is appropriately used under the following conditions:

- The outcome variable is **continuous** and **non-negative** as shown in @fig-gamma-regression. Examples include insurance claim amounts, pollutant concentrations, and operational spending. Note that this outcome should not be a count variable.
- The distribution of the outcome is **right-skewed**. This means that as the mean of the outcome increases, the variance also increases at a faster rate.
- We intend to use the **logarithm of the mean** of the outcome as a **link function**, which ensures that our predictions are always positive.

However, Gamma regression should not be used in the following scenarios:

- The outcome variable includes zeros or negative values.
- The outcome variable is of the count type.
- The variance of the outcome increases at a constant rate relative to the corresponding mean.
::::
:::

::: {#fig-gamma-regression}
```{mermaid}
mindmap
  root((Regression 
  Analysis)
    Continuous <br/>Outcome Y
      {{Unbounded <br/>Outcome Y}}
        )Chapter 3: <br/>Ordinary <br/>Least Squares <br/>Regression(
          (Normal <br/>Outcome Y)
      {{Nonnegative <br/>Outcome Y}}
        )Chapter 4: <br/>Gamma Regression(
          (Gamma <br/>Outcome Y)
    Discrete <br/>Outcome Y
```
:::
