<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-7PRVEBE1EF"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-7PRVEBE1EF');
</script>

# Crunchified Parametric Survival Regression {#sec-parametric-survival}

```{r}
#| include: false

colourize <- function(x, color) {
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color,
      x)
  } else x
}
```

::: {.Warning}
::::{.Warning-header}
Fun fact!
::::
::::{.Warning-container}
**Crunchified!** Extra crunchy, borderline noisy; could probably shatter glass.
::::
:::

::: {#fig-parametric-survival-regression}
```{mermaid}
mindmap
  root((Regression 
  Analysis)
    Continuous <br/>Outcome Y
      {{Unbounded <br/>Outcome Y}}
        )Chapter 3: <br/>Ordinary <br/>Least Squares <br/>Regression(
          (Normal <br/>Outcome Y)
      {{Nonnegative <br/>Outcome Y}}
        )Chapter 4: <br/>Gamma Regression(
          (Gamma <br/>Outcome Y)
      {{Bounded <br/>Outcome Y <br/> between 0 and 1}}
        )Chapter 5: Beta <br/>Regression(
          (Beta <br/>Outcome Y)
      {{Nonnegative <br/>Survival <br/>Time Y}}
        )Chapter 6: <br/>Parametric <br/> Survival <br/>Regression(
          (Exponential <br/>Outcome Y)
          (Weibull <br/>Outcome Y)
          (Lognormal <br/>Outcome Y)
    Discrete <br/>Outcome Y
```
:::

::: {#Definition-cdf .definition}
::::{.definition-header}
Definition of cumulative distribution function 
::::
::::{.definition-container}
Let $Y$ be a `r colourize("random variable", "blue")` either `r colourize("discrete", "blue")` or `r colourize("continuous", "blue")`. Its `r colourize("cumulative distribution function (CDF)", "blue")` $F_Y(y)  : \mathbb{R} \rightarrow [0, 1]$ refers to the `r colourize("probability", "blue")` that $Y$ is less or equal than an observed value $y$:

$$
F_Y(y) = P(Y \leq y).
$${#eq-cdf}

Then, we have the following by type of  `r colourize("random variable", "blue")`:

- When $Y$ is `r colourize("discrete", "blue")`, whose support is $\mathcal{Y}$, suppose it has a `r colourize("PMF", "blue")` $P_Y(Y = y)$. Then, the `r colourize("CDF", "blue")` is mathematically represented as:

$$
F_Y(y) = \sum_{\substack{t \in \mathcal{Y} \\ t \leq y}} P_Y(Y = t).
$${#eq-cdf-discrete}

- When $Y$ is `r colourize("continuous", "blue")`, whose support is $\mathcal{Y}$, suppose it has a `r colourize("PDF", "blue")` $f_Y(y)$. Then, the `r colourize("CDF", "blue")` is mathematically represented as:

$$
F_Y(y) = \int_{-\infty}^y f_Y(t) \mathrm{d}t.
$${#eq-cdf-continuous}

Note that in @eq-cdf-discrete and @eq-cdf-continuous, we use the auxiliary variable $t$ since we do not compute the summation or integral over the observed $y$ given its role on either the `r colourize("PMF", "blue")` or `r colourize("PDF", "blue")`. Therefore, we use this auxiliary variable $t$.
::::
:::

::: {.Heads-up}
::::{.Heads-up-header}
Heads-up on the properties of the cumulative distribution function!
::::
::::{.Heads-up-container}
It is important to clarify that a **valid** `r colourize("CDF", "blue")` $F_Y(y)$ fulfils the following properties:

a. $F_Y(y)$ must **never** be a decreasing function.
b. Given that $F_Y(y)  : \mathbb{R} \rightarrow [0, 1]$, it must **never** evaluate to be $< 0$ or $> 1$. The output of a `r colourize("CDF", "blue")` is a **cumulative `r colourize("probability", "blue")`**, hence the previous bounds.
c. When $y \rightarrow -\infty$, if follows that $F_Y(y) \rightarrow 0$.
d. When $y \rightarrow \infty$, if follows that $F_Y(y) \rightarrow 1$.

Now, in the case of a `r colourize("CDF", "blue")` corresponding to a `r colourize("continuous random variable", "blue")` $Y$, there is an additional handy property that relates the `r colourize("CDF", "blue")` $F_Y(y)$ to the `r colourize("PDF", "blue")` $f_Y(y)$:

$$
f_Y(y) = \frac{\mathrm{d}}{\mathrm{d}y} F_Y(y).
$${#eq-cdf-to-pdf}

@eq-cdf-to-pdf indicates that the `r colourize("PDF", "blue")` of $Y$ can be obtained by taking the first derivative of the `r colourize("CDF", "blue")` with respect to $y$.
::::
:::
