# The ML-Stats Dictionary {#sec-dictionary}

```{r}
#| include: false

colourize <- function(x, color) {
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color,
      x)
  } else x
}
```

## D {.unnumbered}
 
### `r colourize("Dependent variable", "magenta")` {.unnumbered}

In supervised learning, it is the main variable of interest we are trying to **learn** or **predict**, or equivalently, the variable we are trying **explain** in a statistical inference framework.

::: {.callout-warning}
## Equivalent to:

`r colourize("Response", "magenta")`, `r colourize("outcome", "orange")`, `r colourize("output", "orange")` or `r colourize("target", "orange")`.
:::

## O {.unnumbered}

### `r colourize("Outcome", "orange")` {.unnumbered}

In supervised learning, it is the main variable of interest we are trying to **learn** or **predict**, or equivalently, the variable we are trying **explain** in a statistical inference framework.

::: {.callout-warning}
## Equivalent to:

`r colourize("Dependent variable", "magenta")`, `r colourize("response", "magenta")`, `r colourize("output", "orange")` or `r colourize("target", "orange")`.
:::

### `r colourize("Output", "orange")` {.unnumbered}

In supervised learning, it is the main variable of interest we are trying to **learn** or **predict**, or equivalently, the variable we are trying **explain** in a statistical inference framework.

::: {.callout-warning}
## Equivalent to:

`r colourize("Dependent variable", "magenta")`, `r colourize("response", "magenta")`, `r colourize("outcome", "orange")` or `r colourize("target", "orange")`.
:::

## P {.unnumbered}

### `r colourize("Parameter", "magenta")` {.unnumbered}

It is a characteristic (**numerical** or even **non-numerical**, such as a **distinctive category**) that **summarizes** the state of our `r colourize("population", "magenta")` or **system** of interest. Examples of a `r colourize("population parameter", "magenta")` can be described as follows:

- *The average weight of children between the ages of 5 and 10 years old in states of the American West Coast.*
- *The variability in the height of the mature açaí palm trees from the Brazilian Amazonian jungle.*
- *The proportion of defective items in the production of cellular phones in a set of manufacturing facilities.*
- *The average customer waiting time to get their order in the Vancouver franchises of a well-known ice cream parlour.*

Note the **standard mathematical notation** for a `r colourize("population parameters", "magenta")` are **Greek letters**. Moreover, in practice, these `r colourize("population parameter(s)", "magenta")` of interest will be **unknown** to the data scientist or researcher. Instead, they would use formal statistical inference to **estimate** them.

### `r colourize("Population", "magenta")` {.unnumbered}

It is a **whole collection of individuals or items** that share **distinctive attributes**. As data scientists or researchers, we are interested in studying these attributes, which we assume are **governed** by `r colourize("parameters", "magenta")`. In practice, we must be **as precise as possible** when defining our given `r colourize("population", "magenta")` such that we would frame our entire data modelling process since its very early stages. Examples of a `r colourize("population", "magenta")` could be the following:

- *Children between the ages of 5 and 10 years old in states of the American west coast.*
- *Customers of musical vinyl records in the Canadian provinces of British Columbia and Alberta.*
- *Avocado trees grown in the Mexican state of Michoacán.*
- *Adult giant pandas in the Southwestern Chinese province of Sichuan.*
- *Mature açaí palm trees from the Brazilian Amazonian jungle.*

Note that the term `r colourize("population", "magenta")` could be exchanged for the term **system**, given that certain contexts do not specifically refer to individuals or items. Instead, these contexts could refer to **processes** whose attributes are also governed by `r colourize("parameters", "magenta")`. Examples of a **system** could be the following:

- *The production of cellular phones in a set of manufacturing facilities.*
- *The sale process in the Vancouver franchises of a well-known ice cream parlour.*
- *The transit cycle of the twelve lines of Mexico City's subway.*

## R {.unnumbered}

### `r colourize("Response", "magenta")` {.unnumbered}

In supervised learning, it is the main variable of interest we are trying to **learn** or **predict**, or equivalently, the variable we are trying **explain** in a statistical inference framework.

::: {.callout-warning}
## Equivalent to:

`r colourize("Dependent variable", "magenta")`, `r colourize("outcome", "orange")`, `r colourize("outpur", "orange")` or `r colourize("target", "orange")`.
:::

## T {.unnumbered}

### `r colourize("Target", "orange")` {.unnumbered}

In supervised learning, it is the main variable of interest we are trying to **learn** or **predict**, or equivalently, the variable we are trying **explain** in a statistical inference framework.

::: {.callout-warning}
## Equivalent to:

`r colourize("Dependent variable", "magenta")`, `r colourize("response", "magenta")`, `r colourize("outcome", "orange")` or `r colourize("output", "orange")`.
:::
