# How this Book is Structured {.unnumbered}

This book is structured in three big pillars:

1.  The use of an ordered *Data Science workflow*,
2.  the correct use of an *appropriate regression model* for supervised learning based on the outcome of interest, and
3.  a constant common ground in terminology between Statistics and Machine Learning via a *dictionary*. Each one of these three pillars is heavily connected since the same Data Science workflow is applied in each one of the regression models, which aims to help the reader in their learning (i.e., we would be able to know what exact stage to expect in our data analysis regardless of the regression model we are being exposed to).

On the other hand, the dictionary will allow us to clarify any potential confusion between the two disciplines, Statistics and Machine Learning, in differences in terminology within supervised learning. As a side note, throughout the book, all statistical terms will be highlighted in [**purple**]{style="color: purple;"} whereas the common Machine Learning terms will be highlighted in [**blue**]{style="color: blue;"}. This colour scheme strives to combine this terminology so we can switch from one field to another in an easier way. With practice and time, the reader should be expected to jump back and forth when using these concepts.

## Data Science Workflow

A crucial aspect of the practice of supervised learning is the need for a systematic Data Science workflow that will allow us to solve our respective inquiries in a transparent and reproducible way. Hence, @sec-intro begins with the general definition of supervised learning and its two critical paradigms: *inference* and *prediction*. Moreover, its workflow is fully explained across seven sequential phases:

i.  **Design**.
ii. **Data collection**.
iii. **Exploratory data analysis**.
iv. **Modelling**.
v.  **Estimation**.
vi. **Results**.
vii. **Storytelling**.

Now, suppose we do not follow a predefined workflow in practice. In that case, we might be at risk of incorrectly addressing these inquiries, translating into meaningless results outside the context of the problem we aim to solve. This is why the formation of a Data Scientist must stress this workflow from the very introductory stages.

On the other hand, even though this book has prerequisites related to the basics of probability via different distributions and the fundamentals of frequentist statistical inference, @sec-intro also provides a handy summary of all these topics. We will check essential concepts such as *random variables*, *sampling*, *parameter estimation via maximum likelihood*, the process of *hypothesis testing*, delivery of *confidence intervals*, and how to obtain *outcome predictions*. Note these concepts are heavily related to the Data Science workflow depicted in @sec-ds-workflow across its different phases.


## Dictionary of Terminology

Finally, following the structure of the [MDS Stat-ML dictionary](https://ubc-mds.github.io/resources_pages/terminology/), @sec-dictionary contains a dictionary that follows the same format which contrasts the terminology a Data Scientist can find in Machine Learning and Statistics (indicated as [**ML**]{style="color: blue;"}/[**Stats**]{style="color: purple;"} throughout the book) when performing supervised learning in practice. Note that terms will be coloured depending on their [**Machine Learning**]{style="color: blue;"} or [**statistical**]{style="color: purple;"} nature.

::: {.callout-tip appearance="simple"}
## Heads-up!

Readers might be surprised that certain concepts refer to the same idea but with different terminology. Contrarily, in some other cases, the same terminology might refer to different concepts!
:::
