<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-7PRVEBE1EF"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-7PRVEBE1EF');
</script>

# Distributional Cheatsheet {#sec-distributional-cheatsheet}

```{r}
#| include: false

colourize <- function(x, color) {
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color,
      x)
  } else x
}
```

```{mermaid}
mindmap
  root((Univariate 
    Random
    Variable Y))
    Discrete
      Binary
        {{Y is a success or <br/>failure}}
          )Bernoulli(
      Count
        {{Y succeses in <br/>n trials}}
          )Binomial(
        {{Y events in <br/>a fixed interval <br/>of time or space}}
          )Poisson(
        {{Y failures <br/>before experiencing <br/>k successes}}
          )Negative Binomial(
      Categorical
        {{Y successes of a given category, <br/>among a set of k categories, <br/>in n trials}}
          )Multinomial(
    Continuous
      {{Unbounded Y}}
        )Normal(
      {{Nonnegative Y}}
        )Log Normal(
        )Exponential(
        )Gamma(
        )Weibull(
      {{Y is between limits <br/>a and b in general}}
        )Uniform(
      {{Y is between <br/>0 and 1}}
        )Beta(
        
```

# Discrete Random Variables

## Bernoulli

Let $Y$ be a `r colourize("discrete random variable", "blue")` that is part of a random process or system. This random variable can only take on the following values:

$$
Y =
\begin{cases}
1 \; \; \; \; \text{if there is a success},\\
0 \; \; \; \; \mbox{otherwise}.
\end{cases}
$${#eq-app-bernoulli-support}

Note that the support of $Y$ in @eq-app-bernoulli-support makes it binary with these outcomes: $1$ for *success* and $0$ for *failure*.  Then, $Y$ is said to have a Bernoulli distribution with `r colourize("parameter", "blue")` $\pi$:

$$Y \sim \text{Bernoulli}(\pi).$$

### Probability Mass Function

The `r colourize("probability mass function (PMF)", "blue")` of $Y$ is the following:

$$
P \left( Y = y \mid \pi \right) = \pi^y (1 - \pi)^{1 - y} \quad \text{for} \quad y = 0, 1.
$${#eq-app-bernoulli-pmf}

`r colourize("Parameter", "blue")` $\pi$ refers to the `r colourize("probability", "blue")` of success. We can verify @eq-app-bernoulli-pmf is a proper `r colourize("probability mass function PMF", "blue")` (i.e., all the standalone `r colourize("probabilities", "blue")` over the support of $Y$ add up to one) given that:

$$
\begin{align*} 
P \left( Y = y \mid \pi \right) &=  \sum_{y = 0}^1 \pi^y (1 - \pi)^{1 - y}  \\
&= \underbrace{\pi^0}_{1} (1 - \pi) + \pi \underbrace{(1 - \pi)^{0}}_{1} \\
&= (1 - \pi) + \pi \\
&= 1.
\end{align*}
$$

### Expected Value

The `r colourize("expected value", "blue")` or `r colourize("mean", "blue")` of a Bernoulli-distributed `r colourize("random variable", "blue")` $Y$ can be found as follows:

$$
\begin{align*} 
\mathbb{E}(Y) &= \sum_{y = 0}^1 y P \left( Y = y \mid \pi \right) \\
&= \sum_{y = 0}^1 y \left[ \pi^y (1 - \pi)^{1 - y} \right] \\
&= \underbrace{(0) \left[ \pi^0 (1 - \pi) \right]}_{0} + (1) \left[ \pi (1 - \pi)^{0} \right] \\
&= 0 + \pi \\
&= \pi.
\end{align*}
$$

### Variance

The `r colourize("variance", "blue")` of a Bernoulli-distributed `r colourize("random variable", "blue")` $Y$ can be found as follows:

::: {.proof}
$$
\begin{align*}
\text{Var} (Y) &= \mathbb{E}(Y^2) + \left[ \mathbb{E}(Y)\right]^2 \\
&= \mathbb{E}(Y^2) + \pi^2 \qquad \text{since} \qquad \mathbb{E}(Y) = \pi \\
&= \sum_{y = 0}^1 y^2 P \left( Y = y \mid \pi \right) + \pi^2 \\
&= \left\{ \underbrace{(0^2) \left[ \pi^0 (1 - \pi) \right]}_{0} + \underbrace{(1^2) \left[ \pi (1 - \pi)^{0} \right]}_{\pi} \right\} + \pi^2 \\
&= (0 + \pi) + \pi^2 \\
&= \pi + \pi^2 \\
&= \pi (1 + \pi).
\end{align*}
$$
:::

## Binomial

Suppose you execute $n$ `r colourize("independent", "blue")` Bernoulli trials, each one with a probability of success $0 \leq \pi \leq 1$. Let $Y$ be the number of successes obtained within these $n$ Bernoulli trials. Then, $Y$ is said to have a Binomial distribution with `r colourize("parameters", "blue")` $n$ and $\pi$:

$$Y \sim \text{Binomial}(n, \pi).$$

### Probability Mass Function

The `r colourize("PMF", "blue")` of $Y$ is the following:

$$
P \left( Y = y \mid n, \pi \right) = {n \choose y} \pi^y (1 - \pi)^{n - y} \quad \text{for} \quad y = 0, 1, \dots, n.
$${#eq-app-binomial-pmf}

`r colourize("Parameters", "blue")` $\pi$ and $n$ refer to the `r colourize("probability", "blue")` of success and number of trials, respectively. On the other hand, the term ${n \choose x}$ indicates the total number of possible combinations for $x$ successes out of our $n$ trials:

$$
{n \choose x} = \frac{n!}{x!(n - x)!}.
$${#eq-app-combination}

How can we verify that @eq-app-binomial-pmf is a proper `r colourize("PMF", "blue")` (i.e., all the standalone `r colourize("probabilities", "blue")` over the support of $Y$ add up to one)? To elaborate on this, we need to use a handy mathematical theorem from elementary algebra called the binomial theorem. This theorem originates from Pascal's triangle, which defines a pattern of coefficients in the expansion of a polynomial in the form $(u + v)^m$. More specifically, the binomial theorem indicates that if $m$ is a non-negative integer, then the polynomial $(u + v)^m$ can be expanded via the following series:

$$
\begin{align*}
(u + v)^m &= {m \choose 0} u^m + {m \choose 1} u^{m - 1} v + {m \choose 2} u^{m - 2} v^2 +  \dots + {m \choose m-1} u v^{m - 1} + {m \choose m} v^m \\
&= \sum_{i = 0}^m {m \choose i} u^{m - i} v^i \\
&= \sum_{i = 0}^m {m \choose i} v^i u^{m - i} \qquad \text{rearranging factors}.
\end{align*}
$${#eq-app-binomial-theorem}

::: {#Tip-pascal-triangle .Tip}
::::{.Tip-header}
Tip on the Pascal's triangle and binomial theorem
::::
::::{.Tip-container}
The Pascal's triangle heavily relies on the logic behind the combinations depicted in @eq-app-combination.
::::
:::

# Continuous Random Variables